# Setup

In [1]:
import os
from pathlib import Path
import statistics

import numpy as np
import pandas as pd
from scipy.stats import spearmanr
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score, KFold, StratifiedKFold, RepeatedStratifiedKFold

import catboost as cb
import optuna

In [2]:
INPUT_DATA_PATH = './data/'
OUTPUT_DATA_PATH = './output/'
SUBMISSION_PATH = './output/catboost/test/'
MODELS = [
    'deberta_nli',
    'deberta_nli_reverse',
    'roberta_nli',
    'roberta_nli_reverse',
    't5_nli',
    't5_nli_reverse',
    'st_roberta_nli',
    'openchat',
    ]

RANDOM_SEED = 424242

Path(SUBMISSION_PATH).mkdir(parents=True, exist_ok=True)

# Load data

In [3]:
X = {
    'val-agnostic': [],
    'val-aware': [],
    'test-agnostic': [],
    'test-aware': [],
    }
y = {}

# Add 'task' and 'model' features
file = INPUT_DATA_PATH + 'val/val.model-agnostic.json'
df = pd.read_json(file, orient='records')
df['DM'] = df['task'].map({'DM': 1, 'MT': 0, 'PG': 0})
df['MT'] = df['task'].map({'DM': 0, 'MT': 1, 'PG': 0})
df['hyp_len'] = df['hyp'].str.len()
df['tgt_len'] = df['tgt'].str.len()
df['src_len'] = df['src'].str.len()
X['val-agnostic'].append(df[['DM', 'MT', 'hyp_len', 'tgt_len', 'src_len']])

file = INPUT_DATA_PATH + 'val/val.model-aware.json'
df = pd.read_json(file, orient='records')
df['DM'] = df['task'].map({'DM': 1, 'MT': 0, 'PG': 0})
df['MT'] = df['task'].map({'DM': 0, 'MT': 1, 'PG': 0})
df['hyp_len'] = df['hyp'].str.len()
df['tgt_len'] = df['tgt'].str.len()
df['src_len'] = df['src'].str.len()
X['val-aware'].append(df[['DM', 'MT', 'hyp_len', 'tgt_len', 'src_len']])

file = INPUT_DATA_PATH + 'test/test.model-agnostic.json'
df = pd.read_json(file, orient='records')
df['DM'] = df['task'].map({'DM': 1, 'MT': 0, 'PG': 0})
df['MT'] = df['task'].map({'DM': 0, 'MT': 1, 'PG': 0})
df['hyp_len'] = df['hyp'].str.len()
df['tgt_len'] = df['tgt'].str.len()
df['src_len'] = df['src'].str.len()
df.set_index('id', drop=True, inplace=True)
X['test-agnostic'].append(df[['DM', 'MT', 'hyp_len', 'tgt_len', 'src_len']])

file = INPUT_DATA_PATH + 'test/test.model-aware.json'
df = pd.read_json(file, orient='records')
df['DM'] = df['task'].map({'DM': 1, 'MT': 0, 'PG': 0})
df['MT'] = df['task'].map({'DM': 0, 'MT': 1, 'PG': 0})
df['hyp_len'] = df['hyp'].str.len()
df['tgt_len'] = df['tgt'].str.len()
df['src_len'] = df['src'].str.len()
df.set_index('id', drop=True, inplace=True)
X['test-aware'].append(df[['DM', 'MT', 'hyp_len', 'tgt_len', 'src_len']])

# Load X
for model in MODELS:
    # validation agnostic
    file = OUTPUT_DATA_PATH + model + '/val/' + 'val.model-agnostic.json'
    df = pd.read_json(file, orient='records')
    df.rename(columns={"label": "label_" + model, "p(Hallucination)": "p_" + model}, inplace=True)
    X['val-agnostic'].append(df)
    print(file)
    
    # validation aware
    file = OUTPUT_DATA_PATH + model + '/val/' + 'val.model-aware.json'
    df = pd.read_json(file, orient='records')
    df.rename(columns={"label": "label_" + model, "p(Hallucination)": "p_" + model}, inplace=True)
    X['val-aware'].append(df)
    print(file)
    
    # test agnostic
    file = OUTPUT_DATA_PATH + model + '/test/' + 'test.model-agnostic.json'
    df = pd.read_json(file, orient='records')
    df.set_index('id', drop=True, inplace=True)
    df.rename(columns={"label": "label_" + model, "p(Hallucination)": "p_" + model}, inplace=True)
    X['test-agnostic'].append(df)
    print(file)
    
    # test aware
    file = OUTPUT_DATA_PATH + model + '/test/' + 'test.model-aware.json'
    df = pd.read_json(file, orient='records')
    df.set_index('id', drop=True, inplace=True)
    df.rename(columns={"label": "label_" + model, "p(Hallucination)": "p_" + model}, inplace=True)
    X['test-aware'].append(df)
    print(file)

# Load y for validation agnostic
file = INPUT_DATA_PATH + 'val/val.model-agnostic.json'
df = pd.read_json(file, orient='records')
df.rename(columns={"p(Hallucination)": "p"}, inplace=True)
y['val-agnostic'] = df[['label', 'p']]
print(file)

# Load y for validation aware
file = INPUT_DATA_PATH + 'val/val.model-aware.json'
df = pd.read_json(file, orient='records')
df.rename(columns={"p(Hallucination)": "p"}, inplace=True)
y['val-aware'] = df[['label', 'p']]
print(file)

../ivan-output/deberta_nli/val/val.model-agnostic.json
../ivan-output/deberta_nli/val/val.model-aware.json
../ivan-output/deberta_nli/test/test.model-agnostic.json
../ivan-output/deberta_nli/test/test.model-aware.json
../ivan-output/deberta_nli_reverse/val/val.model-agnostic.json
../ivan-output/deberta_nli_reverse/val/val.model-aware.json
../ivan-output/deberta_nli_reverse/test/test.model-agnostic.json
../ivan-output/deberta_nli_reverse/test/test.model-aware.json
../ivan-output/roberta_nli/val/val.model-agnostic.json
../ivan-output/roberta_nli/val/val.model-aware.json
../ivan-output/roberta_nli/test/test.model-agnostic.json
../ivan-output/roberta_nli/test/test.model-aware.json
../ivan-output/roberta_nli_reverse/val/val.model-agnostic.json
../ivan-output/roberta_nli_reverse/val/val.model-aware.json
../ivan-output/roberta_nli_reverse/test/test.model-agnostic.json
../ivan-output/roberta_nli_reverse/test/test.model-aware.json
../ivan-output/t5_nli/val/val.model-agnostic.json
../ivan-output/t5_nli/val/val.model-aware.json
../ivan-output/t5_nli/test/test.model-agnostic.json
../ivan-output/t5_nli/test/test.model-aware.json
../ivan-output/t5_nli_reverse/val/val.model-agnostic.json
../ivan-output/t5_nli_reverse/val/val.model-aware.json
../ivan-output/t5_nli_reverse/test/test.model-agnostic.json
../ivan-output/t5_nli_reverse/test/test.model-aware.json
../ivan-output/st_roberta_nli/val/val.model-agnostic.json
../ivan-output/st_roberta_nli/val/val.model-aware.json
../ivan-output/st_roberta_nli/test/test.model-agnostic.json
../ivan-output/st_roberta_nli/test/test.model-aware.json
../ivan-output/openchat/val/val.model-agnostic.json
../ivan-output/openchat/val/val.model-aware.json
../ivan-output/openchat/test/test.model-agnostic.json
../ivan-output/openchat/test/test.model-aware.json
../data/val/val.model-agnostic.json
../data/val/val.model-aware.json

In [4]:
# Concatenate dataframes by columns
X_ = {}
X_['val-agnostic'] = pd.concat(X['val-agnostic'], axis=1)
X_['val-aware'] = pd.concat(X['val-aware'], axis=1)
X_['test-agnostic'] = pd.concat(X['test-agnostic'], axis=1)
X_['test-aware'] = pd.concat(X['test-aware'], axis=1)
X = X_

# For X: drop columns with 'label' feature
for df_name in X:
    for column in X[df_name].columns:
        if column.startswith('label'):
            X[df_name].drop(columns=column, inplace=True)

# Print dataframe names
print('For X data:')
for df_name in X:
    print('\t', df_name)
print()
print('For y data:')
for df_name in y:
    print('\t', df_name)

For X data:
	 val-agnostic
	 val-aware
	 test-agnostic
	 test-aware

For y data:
	 val-agnostic
	 val-aware

In [7]:
X_['val-agnostic']

,DM,MT,hyp_len,tgt_len,src_len,p_deberta_nli,p_deberta_nli_reverse,p_roberta_nli,p_roberta_nli_reverse,p_t5_nli,p_t5_nli_reverse,p_st_roberta_nli,p_openchat
0,1,0,41,36,316,0.002097,0.027509,0.001844,0.003966,0,0,0.053903,0
1,1,0,32,1,451,0.643224,0.616778,0.289209,0.150303,1,0,0.955537,1
2,1,0,34,36,181,0.707190,0.608000,0.993463,0.932218,1,1,0.107394,0
3,1,0,17,100,149,0.008859,0.861013,0.094564,0.229191,0,1,0.428500,0
4,1,0,39,63,441,0.004337,0.934161,0.013538,0.723117,0,1,0.059323,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,0,1,32,39,30,0.000138,0.000098,0.001673,0.001751,0,0,0.014917,0
495,0,1,42,46,48,0.000263,0.000158,0.004702,0.015190,0,0,0.024462,0
496,0,1,43,42,43,0.000291,0.000118,0.001838,0.002023,0,0,0.016321,0
497,0,1,28,31,22,0.000053,0.000040,0.000960,0.000589,0,0,0.042848,0
498,0,1,43,43,39,0.000145,0.000201,0.005383,0.002978,0,0,0.024805,0

# CatBoost Classifier
## Find parameters

In [8]:
# Определение функции для оптимизации
def objective(trial):
    params = {
        'iterations': trial.suggest_int('iterations', 100, 400),
        'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
        'depth': trial.suggest_int('depth', 6, 12),
        'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
        'border_count': trial.suggest_int('border_count', 5, 200),
        'verbose': False,
        'random_seed': RANDOM_SEED
    }

    model = cb.CatBoostClassifier(**params)

    # Кросс-валидация
    cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=RANDOM_SEED)
    accuracy = cross_val_score(model, X[df_name], y[df_name]['label'], cv=cv, scoring='accuracy').mean()

    return accuracy

best_params_dict = {}
for df_name in ['val-agnostic', 'val-aware']:
    # Создание объекта study и запуск оптимизации
    study = optuna.create_study(direction='maximize')
    study.optimize(objective, n_trials=100)

    # Получение лучших параметров
    best_params_dict[df_name] = study.best_params

for df_name in ['val-agnostic', 'val-aware']:
    print("Best Params:", df_name.ljust(15), best_params_dict[df_name])

[I 2024-02-01 13:45:42,839] A new study created in memory with name: no-name-d4bfa143-1200-47e2-95d2-e1aa4f30c40c
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:45:57,968] Trial 0 finished with value: 0.8518367346938776 and parameters: {'iterations': 216, 'learning_rate': 0.0102019005543733, 'depth': 12, 'l2_leaf_reg': 0.09976943036124933, 'border_count': 39}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:46:00,895] Trial 1 finished with value: 0.8297551020408165 and parameters: {'iterations': 124, 'learning_rate': 0.015352623051451011, 'depth': 10, 'l2_leaf_reg': 0.05018129707954625, 'border_count': 21}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:46:07,911] Trial 2 finished with value: 0.8317959183673469 and parameters: {'iterations': 257, 'learning_rate': 0.0066299857516719215, 'depth': 8, 'l2_leaf_reg': 0.010059053767679318, 'border_count': 103}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:46:27,637] Trial 3 finished with value: 0.8197551020408165 and parameters: {'iterations': 363, 'learning_rate': 0.024482690302002272, 'depth': 10, 'l2_leaf_reg': 0.0205019375879514, 'border_count': 147}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:47:10,628] Trial 4 finished with value: 0.8378775510204083 and parameters: {'iterations': 377, 'learning_rate': 0.014373001124442902, 'depth': 12, 'l2_leaf_reg': 0.08736883157719197, 'border_count': 91}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:47:12,376] Trial 5 finished with value: 0.843795918367347 and parameters: {'iterations': 113, 'learning_rate': 0.07248253963608359, 'depth': 7, 'l2_leaf_reg': 6.694718516822428, 'border_count': 84}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:47:21,199] Trial 6 finished with value: 0.8258367346938776 and parameters: {'iterations': 319, 'learning_rate': 0.03738918699689321, 'depth': 9, 'l2_leaf_reg': 0.025412099109293665, 'border_count': 47}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:48:04,972] Trial 7 finished with value: 0.8377959183673468 and parameters: {'iterations': 228, 'learning_rate': 0.04722896693687696, 'depth': 12, 'l2_leaf_reg': 2.6574001856996956, 'border_count': 190}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:48:09,030] Trial 8 finished with value: 0.8317551020408164 and parameters: {'iterations': 180, 'learning_rate': 0.01113009003424564, 'depth': 8, 'l2_leaf_reg': 0.7997369878258292, 'border_count': 145}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:48:11,308] Trial 9 finished with value: 0.8317959183673469 and parameters: {'iterations': 139, 'learning_rate': 0.022092569015530077, 'depth': 8, 'l2_leaf_reg': 1.2692655396308388, 'border_count': 56}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:48:21,733] Trial 10 finished with value: 0.8418367346938777 and parameters: {'iterations': 265, 'learning_rate': 0.00514758135153344, 'depth': 11, 'l2_leaf_reg': 0.16615699778421947, 'border_count': 9}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:48:23,729] Trial 11 finished with value: 0.8438367346938775 and parameters: {'iterations': 184, 'learning_rate': 0.09856169113854388, 'depth': 6, 'l2_leaf_reg': 9.81882606765499, 'border_count': 69}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:48:25,710] Trial 12 finished with value: 0.8197959183673469 and parameters: {'iterations': 194, 'learning_rate': 0.08415800863889672, 'depth': 6, 'l2_leaf_reg': 0.39199884482639624, 'border_count': 45}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:48:27,725] Trial 13 finished with value: 0.8297551020408163 and parameters: {'iterations': 187, 'learning_rate': 0.009163552088668194, 'depth': 6, 'l2_leaf_reg': 0.2327991806708893, 'border_count': 74}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:48:42,354] Trial 14 finished with value: 0.8217551020408165 and parameters: {'iterations': 287, 'learning_rate': 0.04724153842045891, 'depth': 10, 'l2_leaf_reg': 8.010136578416159, 'border_count': 114}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:48:52,004] Trial 15 finished with value: 0.837795918367347 and parameters: {'iterations': 216, 'learning_rate': 0.026631203672594052, 'depth': 11, 'l2_leaf_reg': 2.281658607042039, 'border_count': 31}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:48:54,390] Trial 16 finished with value: 0.8317142857142856 and parameters: {'iterations': 167, 'learning_rate': 0.008296065448752922, 'depth': 7, 'l2_leaf_reg': 0.5331605360484369, 'border_count': 66}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:49:06,627] Trial 17 finished with value: 0.8317959183673469 and parameters: {'iterations': 309, 'learning_rate': 0.015449360215062416, 'depth': 9, 'l2_leaf_reg': 0.08817526553193193, 'border_count': 128}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:49:11,571] Trial 18 finished with value: 0.8438775510204083 and parameters: {'iterations': 155, 'learning_rate': 0.06434771358424438, 'depth': 11, 'l2_leaf_reg': 0.14585913984958082, 'border_count': 34}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:49:16,088] Trial 19 finished with value: 0.8438775510204083 and parameters: {'iterations': 148, 'learning_rate': 0.05493779683715557, 'depth': 11, 'l2_leaf_reg': 0.13256855299934917, 'border_count': 30}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:49:28,649] Trial 20 finished with value: 0.8298367346938778 and parameters: {'iterations': 231, 'learning_rate': 0.034104330664833725, 'depth': 12, 'l2_leaf_reg': 0.04653560707371855, 'border_count': 7}. Best is trial 0 with value: 0.8518367346938776.
/tmp/ipykernel_1382105/1930475677.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
/tmp/ipykernel_1382105/1930475677.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
[I 2024-02-01 13:49:33,312] Trial 21 finished with value: 0.8458367346938775 and parameters: {'iterations': 150, 'learning_rate': 0.059364303571451595, 'depth': 11, 'l2_leaf_reg': 0.12878528174466913, 'border_count': 30}. Best is trial 0 with value: 0.8518367346938776.

Best Params: val-agnostic    {'iterations': 216, 'learning_rate': 0.0102019005543733, 'depth': 12, 'l2_leaf_reg': 0.09976943036124933, 'border_count': 39}
Best Params: val-aware       {'iterations': 129, 'learning_rate': 0.005371920324746337, 'depth': 9, 'l2_leaf_reg': 0.6911690977933583, 'border_count': 186}

## Evaluate

In [9]:
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=RANDOM_SEED)

mean_accuracy_dict = {}
for df_name in ['val-agnostic', 'val-aware']:
    best_model = cb.CatBoostClassifier(**best_params_dict[df_name])
    accuracy = []
    for i, (train_index, test_index) in enumerate(cv.split(X[df_name], y[df_name]['label'])):
        # Train
        X_train = X[df_name].loc[train_index]
        y_train = y[df_name]['label'].loc[train_index]
        best_model.fit(X_train, y_train)

        # Predict
        X_test = X[df_name].loc[test_index]
        y_test = y[df_name]['label'].loc[test_index]
        y_pred = best_model.predict(X_test)

        # Calc metric
        accuracy.append(accuracy_score(y_test, y_pred))
        
    # Calc average metric
    mean_accuracy = statistics.fmean(accuracy)
    mean_accuracy_dict[df_name] = mean_accuracy

for df_name in ['val-agnostic', 'val-aware']:
    print('Accuracy:', df_name.ljust(15), mean_accuracy_dict[df_name])

0:	learn: 0.6780413	total: 8.4ms	remaining: 1.81s
1:	learn: 0.6599939	total: 16.8ms	remaining: 1.79s
2:	learn: 0.6461998	total: 23.3ms	remaining: 1.66s
3:	learn: 0.6320721	total: 30.7ms	remaining: 1.63s
4:	learn: 0.6185235	total: 38.4ms	remaining: 1.62s
5:	learn: 0.6063067	total: 45.3ms	remaining: 1.58s
6:	learn: 0.5932153	total: 51.9ms	remaining: 1.55s
7:	learn: 0.5818887	total: 58ms	remaining: 1.51s
8:	learn: 0.5679006	total: 65ms	remaining: 1.5s
9:	learn: 0.5565859	total: 71.6ms	remaining: 1.47s
10:	learn: 0.5483005	total: 73.3ms	remaining: 1.36s
11:	learn: 0.5366066	total: 80.1ms	remaining: 1.36s
12:	learn: 0.5257920	total: 87.4ms	remaining: 1.36s
13:	learn: 0.5131252	total: 93.8ms	remaining: 1.35s
14:	learn: 0.5038141	total: 101ms	remaining: 1.35s
15:	learn: 0.4932357	total: 107ms	remaining: 1.34s
16:	learn: 0.4841162	total: 113ms	remaining: 1.33s
17:	learn: 0.4755319	total: 121ms	remaining: 1.33s
18:	learn: 0.4634174	total: 129ms	remaining: 1.33s
19:	learn: 0.4611295	total: 130ms	remaining: 1.27s
20:	learn: 0.4567890	total: 131ms	remaining: 1.22s
21:	learn: 0.4480610	total: 138ms	remaining: 1.21s
22:	learn: 0.4388384	total: 145ms	remaining: 1.22s
23:	learn: 0.4298918	total: 152ms	remaining: 1.22s
24:	learn: 0.4200218	total: 159ms	remaining: 1.21s
25:	learn: 0.4124115	total: 165ms	remaining: 1.21s
26:	learn: 0.4032956	total: 172ms	remaining: 1.2s
27:	learn: 0.3936779	total: 179ms	remaining: 1.2s
28:	learn: 0.3858632	total: 185ms	remaining: 1.2s
29:	learn: 0.3779301	total: 192ms	remaining: 1.19s
30:	learn: 0.3741366	total: 194ms	remaining: 1.16s
31:	learn: 0.3679686	total: 198ms	remaining: 1.14s
32:	learn: 0.3610556	total: 204ms	remaining: 1.13s
33:	learn: 0.3549432	total: 211ms	remaining: 1.13s
34:	learn: 0.3484944	total: 218ms	remaining: 1.13s
35:	learn: 0.3430422	total: 224ms	remaining: 1.12s
36:	learn: 0.3407334	total: 225ms	remaining: 1.09s
37:	learn: 0.3331663	total: 231ms	remaining: 1.08s
38:	learn: 0.3268112	total: 237ms	remaining: 1.08s
39:	learn: 0.3215580	total: 243ms	remaining: 1.07s
40:	learn: 0.3155165	total: 250ms	remaining: 1.07s
41:	learn: 0.3094514	total: 257ms	remaining: 1.06s
42:	learn: 0.3046472	total: 263ms	remaining: 1.06s
43:	learn: 0.2996898	total: 269ms	remaining: 1.05s
44:	learn: 0.2956139	total: 273ms	remaining: 1.04s
45:	learn: 0.2897867	total: 279ms	remaining: 1.03s
46:	learn: 0.2858905	total: 286ms	remaining: 1.03s
47:	learn: 0.2805123	total: 293ms	remaining: 1.02s
48:	learn: 0.2752276	total: 300ms	remaining: 1.02s
49:	learn: 0.2701813	total: 306ms	remaining: 1.02s
50:	learn: 0.2654791	total: 312ms	remaining: 1.01s
51:	learn: 0.2603044	total: 319ms	remaining: 1s
52:	learn: 0.2554234	total: 325ms	remaining: 1s
53:	learn: 0.2513736	total: 332ms	remaining: 995ms
54:	learn: 0.2464099	total: 338ms	remaining: 991ms
55:	learn: 0.2420765	total: 345ms	remaining: 984ms
56:	learn: 0.2382867	total: 351ms	remaining: 979ms
57:	learn: 0.2344746	total: 357ms	remaining: 974ms
58:	learn: 0.2313988	total: 364ms	remaining: 970ms
59:	learn: 0.2280734	total: 371ms	remaining: 966ms
60:	learn: 0.2246225	total: 378ms	remaining: 960ms
61:	learn: 0.2214291	total: 384ms	remaining: 954ms
62:	learn: 0.2205687	total: 385ms	remaining: 935ms
63:	learn: 0.2178640	total: 388ms	remaining: 920ms
64:	learn: 0.2137510	total: 394ms	remaining: 914ms
65:	learn: 0.2114119	total: 400ms	remaining: 910ms
66:	learn: 0.2095252	total: 407ms	remaining: 904ms
67:	learn: 0.2066305	total: 414ms	remaining: 902ms
68:	learn: 0.2033904	total: 421ms	remaining: 898ms
69:	learn: 0.2002750	total: 428ms	remaining: 892ms
70:	learn: 0.1973451	total: 434ms	remaining: 886ms
71:	learn: 0.1941148	total: 440ms	remaining: 880ms
72:	learn: 0.1913353	total: 447ms	remaining: 875ms
73:	learn: 0.1880771	total: 453ms	remaining: 869ms
74:	learn: 0.1854900	total: 459ms	remaining: 863ms
75:	learn: 0.1826018	total: 466ms	remaining: 858ms
76:	learn: 0.1791673	total: 472ms	remaining: 852ms
77:	learn: 0.1767820	total: 479ms	remaining: 847ms
78:	learn: 0.1736578	total: 485ms	remaining: 842ms
79:	learn: 0.1710899	total: 491ms	remaining: 835ms
80:	learn: 0.1692621	total: 498ms	remaining: 830ms
81:	learn: 0.1675510	total: 504ms	remaining: 824ms
82:	learn: 0.1651904	total: 511ms	remaining: 818ms
83:	learn: 0.1632962	total: 517ms	remaining: 813ms
84:	learn: 0.1610448	total: 524ms	remaining: 807ms
85:	learn: 0.1586200	total: 530ms	remaining: 801ms
86:	learn: 0.1561367	total: 536ms	remaining: 795ms
87:	learn: 0.1539844	total: 543ms	remaining: 790ms
88:	learn: 0.1516829	total: 549ms	remaining: 784ms
89:	learn: 0.1499746	total: 555ms	remaining: 777ms
90:	learn: 0.1484043	total: 559ms	remaining: 768ms
91:	learn: 0.1460719	total: 565ms	remaining: 761ms
92:	learn: 0.1441419	total: 572ms	remaining: 756ms
93:	learn: 0.1421557	total: 579ms	remaining: 751ms
94:	learn: 0.1402838	total: 585ms	remaining: 745ms
95:	learn: 0.1378633	total: 591ms	remaining: 739ms
96:	learn: 0.1358973	total: 597ms	remaining: 733ms
97:	learn: 0.1342218	total: 603ms	remaining: 727ms
98:	learn: 0.1328454	total: 610ms	remaining: 721ms
99:	learn: 0.1311375	total: 618ms	remaining: 716ms
100:	learn: 0.1307903	total: 619ms	remaining: 705ms
101:	learn: 0.1293071	total: 626ms	remaining: 699ms
102:	learn: 0.1273561	total: 633ms	remaining: 694ms
103:	learn: 0.1260561	total: 639ms	remaining: 689ms
104:	learn: 0.1244856	total: 646ms	remaining: 683ms
105:	learn: 0.1231019	total: 654ms	remaining: 678ms
106:	learn: 0.1217276	total: 659ms	remaining: 671ms
107:	learn: 0.1200910	total: 667ms	remaining: 667ms
108:	learn: 0.1184495	total: 674ms	remaining: 661ms
109:	learn: 0.1173610	total: 680ms	remaining: 656ms
110:	learn: 0.1159105	total: 687ms	remaining: 650ms
111:	learn: 0.1145591	total: 694ms	remaining: 645ms
112:	learn: 0.1130755	total: 701ms	remaining: 639ms
113:	learn: 0.1114453	total: 708ms	remaining: 633ms
114:	learn: 0.1098473	total: 714ms	remaining: 627ms
115:	learn: 0.1096914	total: 715ms	remaining: 616ms
116:	learn: 0.1084561	total: 722ms	remaining: 611ms
117:	learn: 0.1068016	total: 728ms	remaining: 605ms
118:	learn: 0.1053678	total: 735ms	remaining: 599ms
119:	learn: 0.1040577	total: 742ms	remaining: 593ms
120:	learn: 0.1024197	total: 748ms	remaining: 588ms
121:	learn: 0.1010393	total: 756ms	remaining: 582ms
122:	learn: 0.0996714	total: 761ms	remaining: 576ms
123:	learn: 0.0988687	total: 767ms	remaining: 569ms
124:	learn: 0.0985973	total: 768ms	remaining: 559ms
125:	learn: 0.0974090	total: 775ms	remaining: 553ms
126:	learn: 0.0959766	total: 781ms	remaining: 547ms
127:	learn: 0.0948015	total: 787ms	remaining: 541ms
128:	learn: 0.0937343	total: 794ms	remaining: 536ms
129:	learn: 0.0929894	total: 800ms	remaining: 530ms
130:	learn: 0.0916673	total: 807ms	remaining: 524ms
131:	learn: 0.0907487	total: 814ms	remaining: 518ms
132:	learn: 0.0896550	total: 821ms	remaining: 512ms
133:	learn: 0.0889029	total: 827ms	remaining: 506ms
134:	learn: 0.0881263	total: 834ms	remaining: 500ms
135:	learn: 0.0872828	total: 841ms	remaining: 495ms
136:	learn: 0.0863672	total: 848ms	remaining: 489ms
137:	learn: 0.0855210	total: 854ms	remaining: 482ms
138:	learn: 0.0848945	total: 860ms	remaining: 477ms
139:	learn: 0.0841100	total: 866ms	remaining: 470ms
140:	learn: 0.0835600	total: 873ms	remaining: 464ms
141:	learn: 0.0827710	total: 880ms	remaining: 458ms
142:	learn: 0.0823329	total: 886ms	remaining: 452ms
143:	learn: 0.0814455	total: 892ms	remaining: 446ms
144:	learn: 0.0801972	total: 899ms	remaining: 440ms
145:	learn: 0.0792591	total: 906ms	remaining: 434ms
146:	learn: 0.0786684	total: 912ms	remaining: 428ms
147:	learn: 0.0778488	total: 919ms	remaining: 422ms
148:	learn: 0.0770282	total: 925ms	remaining: 416ms
149:	learn: 0.0763759	total: 932ms	remaining: 410ms
150:	learn: 0.0755815	total: 939ms	remaining: 404ms
151:	learn: 0.0749957	total: 945ms	remaining: 398ms
152:	learn: 0.0740007	total: 952ms	remaining: 392ms
153:	learn: 0.0733493	total: 957ms	remaining: 385ms
154:	learn: 0.0726687	total: 964ms	remaining: 379ms
155:	learn: 0.0719009	total: 970ms	remaining: 373ms
156:	learn: 0.0711849	total: 977ms	remaining: 367ms
157:	learn: 0.0705507	total: 983ms	remaining: 361ms
158:	learn: 0.0700425	total: 989ms	remaining: 355ms
159:	learn: 0.0693900	total: 996ms	remaining: 349ms
160:	learn: 0.0687441	total: 1s	remaining: 342ms
161:	learn: 0.0680160	total: 1.01s	remaining: 336ms
162:	learn: 0.0671739	total: 1.02s	remaining: 330ms
163:	learn: 0.0665694	total: 1.02s	remaining: 324ms
164:	learn: 0.0659822	total: 1.03s	remaining: 318ms
165:	learn: 0.0652088	total: 1.03s	remaining: 312ms
166:	learn: 0.0645480	total: 1.04s	remaining: 306ms
167:	learn: 0.0640195	total: 1.05s	remaining: 299ms
168:	learn: 0.0634993	total: 1.05s	remaining: 293ms
169:	learn: 0.0628396	total: 1.06s	remaining: 287ms
170:	learn: 0.0622417	total: 1.07s	remaining: 281ms
171:	learn: 0.0617764	total: 1.07s	remaining: 275ms
172:	learn: 0.0615572	total: 1.07s	remaining: 267ms
173:	learn: 0.0609215	total: 1.08s	remaining: 261ms
174:	learn: 0.0602770	total: 1.09s	remaining: 255ms
175:	learn: 0.0598419	total: 1.09s	remaining: 249ms
176:	learn: 0.0592721	total: 1.1s	remaining: 242ms
177:	learn: 0.0587046	total: 1.11s	remaining: 236ms
178:	learn: 0.0582410	total: 1.11s	remaining: 230ms
179:	learn: 0.0576653	total: 1.12s	remaining: 224ms
180:	learn: 0.0571251	total: 1.13s	remaining: 218ms
181:	learn: 0.0565539	total: 1.13s	remaining: 211ms
182:	learn: 0.0560847	total: 1.14s	remaining: 205ms
183:	learn: 0.0556702	total: 1.15s	remaining: 199ms
184:	learn: 0.0550742	total: 1.15s	remaining: 193ms
185:	learn: 0.0545229	total: 1.16s	remaining: 187ms
186:	learn: 0.0541900	total: 1.17s	remaining: 181ms
187:	learn: 0.0535350	total: 1.17s	remaining: 175ms
188:	learn: 0.0532110	total: 1.18s	remaining: 168ms
189:	learn: 0.0526359	total: 1.19s	remaining: 162ms
190:	learn: 0.0522007	total: 1.19s	remaining: 156ms
191:	learn: 0.0517406	total: 1.2s	remaining: 150ms
192:	learn: 0.0511562	total: 1.21s	remaining: 144ms
193:	learn: 0.0506766	total: 1.21s	remaining: 137ms
194:	learn: 0.0502051	total: 1.22s	remaining: 131ms
195:	learn: 0.0498895	total: 1.23s	remaining: 125ms
196:	learn: 0.0493678	total: 1.23s	remaining: 119ms
197:	learn: 0.0490408	total: 1.24s	remaining: 113ms
198:	learn: 0.0487863	total: 1.25s	remaining: 106ms
199:	learn: 0.0482075	total: 1.25s	remaining: 100ms
200:	learn: 0.0478987	total: 1.26s	remaining: 94ms
201:	learn: 0.0474327	total: 1.26s	remaining: 87.7ms
202:	learn: 0.0470489	total: 1.27s	remaining: 81.5ms
203:	learn: 0.0465765	total: 1.28s	remaining: 75.3ms
204:	learn: 0.0460618	total: 1.29s	remaining: 69ms
205:	learn: 0.0456651	total: 1.29s	remaining: 62.7ms
206:	learn: 0.0452808	total: 1.3s	remaining: 56.5ms
207:	learn: 0.0447606	total: 1.31s	remaining: 50.2ms
208:	learn: 0.0443512	total: 1.31s	remaining: 44ms
209:	learn: 0.0439605	total: 1.32s	remaining: 37.7ms
210:	learn: 0.0437208	total: 1.32s	remaining: 31.4ms
211:	learn: 0.0432882	total: 1.33s	remaining: 25.1ms
212:	learn: 0.0429154	total: 1.34s	remaining: 18.9ms
213:	learn: 0.0425424	total: 1.35s	remaining: 12.6ms
214:	learn: 0.0421062	total: 1.35s	remaining: 6.29ms
215:	learn: 0.0417790	total: 1.36s	remaining: 0us
0:	learn: 0.6776011	total: 7.42ms	remaining: 1.59s
1:	learn: 0.6595596	total: 14.5ms	remaining: 1.55s
2:	learn: 0.6470940	total: 21ms	remaining: 1.49s
3:	learn: 0.6299592	total: 27.7ms	remaining: 1.47s
4:	learn: 0.6164899	total: 34.7ms	remaining: 1.47s
5:	learn: 0.6029396	total: 41.7ms	remaining: 1.46s
6:	learn: 0.5895079	total: 47.6ms	remaining: 1.42s
7:	learn: 0.5770183	total: 53ms	remaining: 1.38s
8:	learn: 0.5642153	total: 59.8ms	remaining: 1.38s
9:	learn: 0.5513447	total: 65.5ms	remaining: 1.35s
10:	learn: 0.5407123	total: 72.3ms	remaining: 1.35s
11:	learn: 0.5314651	total: 79.4ms	remaining: 1.35s
12:	learn: 0.5220787	total: 86ms	remaining: 1.34s
13:	learn: 0.5104248	total: 92.8ms	remaining: 1.34s
14:	learn: 0.4983524	total: 99.4ms	remaining: 1.33s
15:	learn: 0.4874465	total: 106ms	remaining: 1.33s
16:	learn: 0.4780980	total: 112ms	remaining: 1.31s
17:	learn: 0.4701487	total: 118ms	remaining: 1.3s
18:	learn: 0.4593976	total: 125ms	remaining: 1.29s
19:	learn: 0.4503295	total: 130ms	remaining: 1.28s
20:	learn: 0.4408133	total: 137ms	remaining: 1.27s
21:	learn: 0.4315774	total: 143ms	remaining: 1.26s
22:	learn: 0.4219547	total: 150ms	remaining: 1.25s
23:	learn: 0.4131918	total: 156ms	remaining: 1.25s
24:	learn: 0.4052161	total: 160ms	remaining: 1.22s
25:	learn: 0.3979086	total: 167ms	remaining: 1.22s
26:	learn: 0.3898573	total: 174ms	remaining: 1.22s
27:	learn: 0.3822796	total: 181ms	remaining: 1.21s
28:	learn: 0.3757050	total: 187ms	remaining: 1.2s
29:	learn: 0.3673086	total: 193ms	remaining: 1.2s
30:	learn: 0.3609722	total: 200ms	remaining: 1.2s
31:	learn: 0.3547323	total: 206ms	remaining: 1.19s
32:	learn: 0.3479827	total: 212ms	remaining: 1.17s
33:	learn: 0.3406268	total: 217ms	remaining: 1.16s
34:	learn: 0.3329456	total: 223ms	remaining: 1.16s
35:	learn: 0.3279256	total: 227ms	remaining: 1.14s
36:	learn: 0.3226900	total: 234ms	remaining: 1.13s
37:	learn: 0.3172506	total: 240ms	remaining: 1.12s
38:	learn: 0.3104725	total: 247ms	remaining: 1.12s
39:	learn: 0.3050939	total: 253ms	remaining: 1.11s
40:	learn: 0.3003488	total: 260ms	remaining: 1.11s
41:	learn: 0.2945207	total: 267ms	remaining: 1.1s
42:	learn: 0.2891291	total: 273ms	remaining: 1.1s
43:	learn: 0.2835862	total: 279ms	remaining: 1.09s
44:	learn: 0.2788094	total: 285ms	remaining: 1.08s
45:	learn: 0.2741310	total: 292ms	remaining: 1.08s
46:	learn: 0.2688938	total: 298ms	remaining: 1.07s
47:	learn: 0.2645701	total: 304ms	remaining: 1.06s
48:	learn: 0.2600734	total: 311ms	remaining: 1.06s
49:	learn: 0.2559551	total: 317ms	remaining: 1.05s
50:	learn: 0.2543885	total: 318ms	remaining: 1.03s
51:	learn: 0.2503731	total: 325ms	remaining: 1.02s
52:	learn: 0.2464314	total: 331ms	remaining: 1.02s
53:	learn: 0.2424047	total: 338ms	remaining: 1.01s
54:	learn: 0.2376377	total: 344ms	remaining: 1.01s
55:	learn: 0.2336634	total: 351ms	remaining: 1s
56:	learn: 0.2292614	total: 357ms	remaining: 995ms
57:	learn: 0.2246679	total: 363ms	remaining: 988ms
58:	learn: 0.2201381	total: 369ms	remaining: 983ms
59:	learn: 0.2166162	total: 376ms	remaining: 978ms
60:	learn: 0.2129280	total: 383ms	remaining: 972ms
61:	learn: 0.2099344	total: 390ms	remaining: 968ms
62:	learn: 0.2072422	total: 396ms	remaining: 963ms
63:	learn: 0.2061057	total: 399ms	remaining: 947ms
64:	learn: 0.2032939	total: 404ms	remaining: 939ms
65:	learn: 0.2008850	total: 411ms	remaining: 935ms
66:	learn: 0.1979994	total: 417ms	remaining: 928ms
67:	learn: 0.1956024	total: 424ms	remaining: 922ms
68:	learn: 0.1924001	total: 430ms	remaining: 917ms
69:	learn: 0.1888149	total: 437ms	remaining: 912ms
70:	learn: 0.1872838	total: 439ms	remaining: 896ms
71:	learn: 0.1852437	total: 445ms	remaining: 889ms
72:	learn: 0.1835580	total: 451ms	remaining: 884ms
73:	learn: 0.1805605	total: 458ms	remaining: 878ms
74:	learn: 0.1769415	total: 464ms	remaining: 873ms
75:	learn: 0.1741251	total: 471ms	remaining: 868ms
76:	learn: 0.1715172	total: 477ms	remaining: 862ms
77:	learn: 0.1689048	total: 483ms	remaining: 855ms
78:	learn: 0.1662961	total: 489ms	remaining: 848ms
79:	learn: 0.1639451	total: 496ms	remaining: 843ms
80:	learn: 0.1615511	total: 503ms	remaining: 838ms
81:	learn: 0.1594520	total: 509ms	remaining: 833ms
82:	learn: 0.1570633	total: 516ms	remaining: 827ms
83:	learn: 0.1547097	total: 523ms	remaining: 822ms
84:	learn: 0.1524378	total: 530ms	remaining: 816ms
85:	learn: 0.1507676	total: 536ms	remaining: 811ms
86:	learn: 0.1485393	total: 543ms	remaining: 805ms
87:	learn: 0.1467261	total: 549ms	remaining: 799ms
88:	learn: 0.1442806	total: 556ms	remaining: 793ms
89:	learn: 0.1430295	total: 562ms	remaining: 787ms
90:	learn: 0.1411772	total: 568ms	remaining: 781ms
91:	learn: 0.1394312	total: 575ms	remaining: 775ms
92:	learn: 0.1373848	total: 581ms	remaining: 768ms
93:	learn: 0.1357283	total: 587ms	remaining: 762ms
94:	learn: 0.1338242	total: 594ms	remaining: 757ms
95:	learn: 0.1320217	total: 601ms	remaining: 751ms
96:	learn: 0.1303962	total: 608ms	remaining: 745ms
97:	learn: 0.1291181	total: 614ms	remaining: 740ms
98:	learn: 0.1277242	total: 620ms	remaining: 733ms
99:	learn: 0.1264114	total: 627ms	remaining: 727ms
100:	learn: 0.1250852	total: 634ms	remaining: 722ms
101:	learn: 0.1233486	total: 641ms	remaining: 716ms
102:	learn: 0.1217239	total: 648ms	remaining: 711ms
103:	learn: 0.1201317	total: 654ms	remaining: 704ms
104:	learn: 0.1183381	total: 660ms	remaining: 698ms
105:	learn: 0.1167997	total: 667ms	remaining: 692ms
106:	learn: 0.1157599	total: 673ms	remaining: 686ms
107:	learn: 0.1144074	total: 680ms	remaining: 680ms
108:	learn: 0.1131729	total: 686ms	remaining: 674ms
109:	learn: 0.1118879	total: 693ms	remaining: 668ms
110:	learn: 0.1101685	total: 700ms	remaining: 662ms
111:	learn: 0.1088738	total: 706ms	remaining: 656ms
112:	learn: 0.1074997	total: 713ms	remaining: 650ms
113:	learn: 0.1063465	total: 719ms	remaining: 644ms
114:	learn: 0.1054180	total: 726ms	remaining: 638ms
115:	learn: 0.1040728	total: 732ms	remaining: 631ms
116:	learn: 0.1029383	total: 739ms	remaining: 625ms
117:	learn: 0.1017845	total: 746ms	remaining: 619ms
118:	learn: 0.1006002	total: 753ms	remaining: 614ms
119:	learn: 0.0994664	total: 760ms	remaining: 608ms
120:	learn: 0.0980443	total: 766ms	remaining: 602ms
121:	learn: 0.0972407	total: 773ms	remaining: 596ms
122:	learn: 0.0958932	total: 780ms	remaining: 590ms
123:	learn: 0.0947092	total: 786ms	remaining: 583ms
124:	learn: 0.0934668	total: 793ms	remaining: 577ms
125:	learn: 0.0923209	total: 799ms	remaining: 570ms
126:	learn: 0.0911780	total: 806ms	remaining: 565ms
127:	learn: 0.0902739	total: 813ms	remaining: 559ms
128:	learn: 0.0892065	total: 820ms	remaining: 553ms
129:	learn: 0.0883823	total: 827ms	remaining: 547ms
130:	learn: 0.0873412	total: 833ms	remaining: 541ms
131:	learn: 0.0863875	total: 840ms	remaining: 534ms
132:	learn: 0.0853292	total: 846ms	remaining: 528ms
133:	learn: 0.0841928	total: 853ms	remaining: 522ms
134:	learn: 0.0834259	total: 859ms	remaining: 515ms
135:	learn: 0.0826786	total: 866ms	remaining: 509ms
136:	learn: 0.0820464	total: 872ms	remaining: 503ms
137:	learn: 0.0812332	total: 879ms	remaining: 497ms
138:	learn: 0.0804390	total: 885ms	remaining: 490ms
139:	learn: 0.0795772	total: 892ms	remaining: 484ms
140:	learn: 0.0788498	total: 899ms	remaining: 478ms
141:	learn: 0.0779353	total: 905ms	remaining: 471ms
142:	learn: 0.0769608	total: 912ms	remaining: 465ms
143:	learn: 0.0762351	total: 918ms	remaining: 459ms
144:	learn: 0.0752331	total: 925ms	remaining: 453ms
145:	learn: 0.0744815	total: 931ms	remaining: 446ms
146:	learn: 0.0737276	total: 937ms	remaining: 440ms
147:	learn: 0.0731509	total: 944ms	remaining: 434ms
148:	learn: 0.0722672	total: 951ms	remaining: 428ms
149:	learn: 0.0714582	total: 957ms	remaining: 421ms
150:	learn: 0.0706107	total: 964ms	remaining: 415ms
151:	learn: 0.0702237	total: 970ms	remaining: 408ms
152:	learn: 0.0696406	total: 976ms	remaining: 402ms
153:	learn: 0.0691231	total: 983ms	remaining: 396ms
154:	learn: 0.0683917	total: 990ms	remaining: 390ms
155:	learn: 0.0676763	total: 997ms	remaining: 383ms
156:	learn: 0.0672106	total: 1s	remaining: 377ms
157:	learn: 0.0667475	total: 1.01s	remaining: 370ms
158:	learn: 0.0662305	total: 1.01s	remaining: 364ms
159:	learn: 0.0654728	total: 1.02s	remaining: 358ms
160:	learn: 0.0647316	total: 1.03s	remaining: 351ms
161:	learn: 0.0640790	total: 1.03s	remaining: 345ms
162:	learn: 0.0634961	total: 1.04s	remaining: 339ms
163:	learn: 0.0628103	total: 1.05s	remaining: 332ms
164:	learn: 0.0621815	total: 1.05s	remaining: 326ms
165:	learn: 0.0617340	total: 1.06s	remaining: 320ms
166:	learn: 0.0613481	total: 1.06s	remaining: 312ms
167:	learn: 0.0606959	total: 1.07s	remaining: 306ms
168:	learn: 0.0599100	total: 1.08s	remaining: 300ms
169:	learn: 0.0595139	total: 1.08s	remaining: 293ms
170:	learn: 0.0589744	total: 1.09s	remaining: 287ms
171:	learn: 0.0584298	total: 1.1s	remaining: 281ms

## Train

In [10]:
best_models = {}
for df_name in ['val-agnostic', 'val-aware']:
    # Обучение модели с лучшими параметрами
    best_model = cb.CatBoostClassifier(**best_params_dict[df_name])
    best_model.fit(X[df_name], y[df_name]['label'])
    best_models[df_name] = best_model

0:	learn: 0.6751101	total: 8.31ms	remaining: 1.78s
1:	learn: 0.6571157	total: 16.2ms	remaining: 1.73s
2:	learn: 0.6452578	total: 23.8ms	remaining: 1.69s
3:	learn: 0.6291353	total: 30.8ms	remaining: 1.63s
4:	learn: 0.6155098	total: 37.7ms	remaining: 1.59s
5:	learn: 0.6031395	total: 44.4ms	remaining: 1.55s
6:	learn: 0.5891181	total: 51.9ms	remaining: 1.55s
7:	learn: 0.5758257	total: 58ms	remaining: 1.51s
8:	learn: 0.5641602	total: 64.6ms	remaining: 1.49s
9:	learn: 0.5522909	total: 71.1ms	remaining: 1.46s
10:	learn: 0.5452427	total: 72.9ms	remaining: 1.36s
11:	learn: 0.5325346	total: 79.7ms	remaining: 1.35s
12:	learn: 0.5289048	total: 80.6ms	remaining: 1.26s
13:	learn: 0.5174999	total: 87.5ms	remaining: 1.26s
14:	learn: 0.5134649	total: 88.5ms	remaining: 1.19s
15:	learn: 0.5022057	total: 95.4ms	remaining: 1.19s
16:	learn: 0.4994254	total: 96.1ms	remaining: 1.12s
17:	learn: 0.4880608	total: 102ms	remaining: 1.12s
18:	learn: 0.4850010	total: 103ms	remaining: 1.06s
19:	learn: 0.4757965	total: 109ms	remaining: 1.07s
20:	learn: 0.4648620	total: 116ms	remaining: 1.08s
21:	learn: 0.4552755	total: 122ms	remaining: 1.08s
22:	learn: 0.4452580	total: 129ms	remaining: 1.09s
23:	learn: 0.4361407	total: 137ms	remaining: 1.1s
24:	learn: 0.4269933	total: 144ms	remaining: 1.1s
25:	learn: 0.4191950	total: 151ms	remaining: 1.1s
26:	learn: 0.4093348	total: 158ms	remaining: 1.1s
27:	learn: 0.4007440	total: 164ms	remaining: 1.1s
28:	learn: 0.3926699	total: 171ms	remaining: 1.1s
29:	learn: 0.3852869	total: 178ms	remaining: 1.1s
30:	learn: 0.3778916	total: 185ms	remaining: 1.1s
31:	learn: 0.3707694	total: 191ms	remaining: 1.1s
32:	learn: 0.3634209	total: 199ms	remaining: 1.1s
33:	learn: 0.3561613	total: 208ms	remaining: 1.11s
34:	learn: 0.3489646	total: 214ms	remaining: 1.11s
35:	learn: 0.3423206	total: 220ms	remaining: 1.1s
36:	learn: 0.3371951	total: 226ms	remaining: 1.09s
37:	learn: 0.3306188	total: 233ms	remaining: 1.09s
38:	learn: 0.3249721	total: 239ms	remaining: 1.09s
39:	learn: 0.3204303	total: 246ms	remaining: 1.08s
40:	learn: 0.3139930	total: 253ms	remaining: 1.08s
41:	learn: 0.3079406	total: 260ms	remaining: 1.08s
42:	learn: 0.3030926	total: 267ms	remaining: 1.07s
43:	learn: 0.2983267	total: 273ms	remaining: 1.07s
44:	learn: 0.2943754	total: 280ms	remaining: 1.06s
45:	learn: 0.2891237	total: 287ms	remaining: 1.06s
46:	learn: 0.2842471	total: 294ms	remaining: 1.06s
47:	learn: 0.2790681	total: 300ms	remaining: 1.05s
48:	learn: 0.2741981	total: 306ms	remaining: 1.04s
49:	learn: 0.2700234	total: 312ms	remaining: 1.03s
50:	learn: 0.2652846	total: 318ms	remaining: 1.03s
51:	learn: 0.2609741	total: 324ms	remaining: 1.02s
52:	learn: 0.2565266	total: 330ms	remaining: 1.01s
53:	learn: 0.2526609	total: 336ms	remaining: 1.01s
54:	learn: 0.2486897	total: 343ms	remaining: 1s
55:	learn: 0.2447544	total: 349ms	remaining: 996ms
56:	learn: 0.2406014	total: 355ms	remaining: 989ms
57:	learn: 0.2360974	total: 361ms	remaining: 983ms
58:	learn: 0.2330446	total: 367ms	remaining: 977ms
59:	learn: 0.2295010	total: 374ms	remaining: 972ms
60:	learn: 0.2278241	total: 376ms	remaining: 956ms
61:	learn: 0.2240897	total: 383ms	remaining: 951ms
62:	learn: 0.2218776	total: 390ms	remaining: 947ms
63:	learn: 0.2179299	total: 394ms	remaining: 935ms
64:	learn: 0.2173373	total: 395ms	remaining: 917ms
65:	learn: 0.2150344	total: 402ms	remaining: 913ms
66:	learn: 0.2115458	total: 408ms	remaining: 908ms
67:	learn: 0.2089097	total: 415ms	remaining: 904ms
68:	learn: 0.2057243	total: 422ms	remaining: 900ms
69:	learn: 0.2051691	total: 423ms	remaining: 883ms
70:	learn: 0.2024861	total: 430ms	remaining: 878ms
71:	learn: 0.1998562	total: 437ms	remaining: 874ms
72:	learn: 0.1966694	total: 444ms	remaining: 869ms
73:	learn: 0.1936975	total: 450ms	remaining: 864ms
74:	learn: 0.1904433	total: 457ms	remaining: 858ms
75:	learn: 0.1875939	total: 462ms	remaining: 852ms
76:	learn: 0.1851085	total: 469ms	remaining: 847ms
77:	learn: 0.1820273	total: 475ms	remaining: 841ms
78:	learn: 0.1788058	total: 482ms	remaining: 835ms
79:	learn: 0.1764906	total: 488ms	remaining: 829ms
80:	learn: 0.1738488	total: 495ms	remaining: 824ms
81:	learn: 0.1711449	total: 501ms	remaining: 819ms
82:	learn: 0.1689689	total: 508ms	remaining: 814ms
83:	learn: 0.1669828	total: 514ms	remaining: 807ms
84:	learn: 0.1646751	total: 520ms	remaining: 802ms
85:	learn: 0.1627569	total: 527ms	remaining: 797ms
86:	learn: 0.1606549	total: 534ms	remaining: 792ms
87:	learn: 0.1582564	total: 540ms	remaining: 786ms
88:	learn: 0.1568359	total: 544ms	remaining: 776ms
89:	learn: 0.1550739	total: 550ms	remaining: 769ms
90:	learn: 0.1532307	total: 557ms	remaining: 765ms
91:	learn: 0.1529605	total: 558ms	remaining: 752ms
92:	learn: 0.1512356	total: 563ms	remaining: 745ms
93:	learn: 0.1494830	total: 569ms	remaining: 739ms
94:	learn: 0.1477341	total: 575ms	remaining: 733ms
95:	learn: 0.1460145	total: 581ms	remaining: 726ms
96:	learn: 0.1437896	total: 587ms	remaining: 720ms
97:	learn: 0.1417798	total: 593ms	remaining: 714ms
98:	learn: 0.1398445	total: 599ms	remaining: 708ms
99:	learn: 0.1382411	total: 606ms	remaining: 703ms
100:	learn: 0.1366237	total: 614ms	remaining: 699ms
101:	learn: 0.1347705	total: 621ms	remaining: 694ms
102:	learn: 0.1333205	total: 627ms	remaining: 688ms
103:	learn: 0.1317671	total: 634ms	remaining: 683ms
104:	learn: 0.1304629	total: 641ms	remaining: 677ms
105:	learn: 0.1290226	total: 648ms	remaining: 672ms
106:	learn: 0.1270005	total: 655ms	remaining: 667ms
107:	learn: 0.1251676	total: 661ms	remaining: 661ms
108:	learn: 0.1238249	total: 667ms	remaining: 655ms
109:	learn: 0.1222750	total: 675ms	remaining: 650ms
110:	learn: 0.1212410	total: 681ms	remaining: 644ms
111:	learn: 0.1199031	total: 688ms	remaining: 639ms
112:	learn: 0.1186287	total: 694ms	remaining: 633ms
113:	learn: 0.1172094	total: 701ms	remaining: 627ms
114:	learn: 0.1160144	total: 708ms	remaining: 621ms
115:	learn: 0.1145356	total: 713ms	remaining: 615ms
116:	learn: 0.1130852	total: 720ms	remaining: 609ms
117:	learn: 0.1116969	total: 727ms	remaining: 603ms
118:	learn: 0.1115533	total: 728ms	remaining: 593ms
119:	learn: 0.1103754	total: 734ms	remaining: 587ms
120:	learn: 0.1092506	total: 741ms	remaining: 582ms
121:	learn: 0.1079659	total: 748ms	remaining: 576ms
122:	learn: 0.1066645	total: 755ms	remaining: 571ms
123:	learn: 0.1052576	total: 761ms	remaining: 565ms
124:	learn: 0.1037623	total: 768ms	remaining: 559ms
125:	learn: 0.1026871	total: 775ms	remaining: 554ms
126:	learn: 0.1013469	total: 782ms	remaining: 548ms
127:	learn: 0.1000027	total: 789ms	remaining: 542ms
128:	learn: 0.0986688	total: 796ms	remaining: 537ms
129:	learn: 0.0976175	total: 801ms	remaining: 530ms
130:	learn: 0.0965871	total: 809ms	remaining: 525ms
131:	learn: 0.0955861	total: 816ms	remaining: 519ms
132:	learn: 0.0945377	total: 822ms	remaining: 513ms
133:	learn: 0.0935675	total: 829ms	remaining: 507ms
134:	learn: 0.0924959	total: 836ms	remaining: 502ms
135:	learn: 0.0915744	total: 842ms	remaining: 495ms
136:	learn: 0.0907381	total: 849ms	remaining: 489ms
137:	learn: 0.0896113	total: 856ms	remaining: 484ms
138:	learn: 0.0886013	total: 862ms	remaining: 478ms
139:	learn: 0.0878317	total: 870ms	remaining: 472ms
140:	learn: 0.0870212	total: 876ms	remaining: 466ms
141:	learn: 0.0864780	total: 883ms	remaining: 460ms
142:	learn: 0.0857495	total: 889ms	remaining: 454ms
143:	learn: 0.0851973	total: 896ms	remaining: 448ms
144:	learn: 0.0843665	total: 902ms	remaining: 442ms
145:	learn: 0.0835267	total: 909ms	remaining: 436ms
146:	learn: 0.0825085	total: 916ms	remaining: 430ms
147:	learn: 0.0814050	total: 922ms	remaining: 424ms
148:	learn: 0.0802133	total: 929ms	remaining: 418ms
149:	learn: 0.0794387	total: 936ms	remaining: 412ms
150:	learn: 0.0784604	total: 942ms	remaining: 406ms
151:	learn: 0.0775759	total: 949ms	remaining: 400ms
152:	learn: 0.0767048	total: 956ms	remaining: 394ms
153:	learn: 0.0760007	total: 962ms	remaining: 387ms
154:	learn: 0.0751270	total: 968ms	remaining: 381ms
155:	learn: 0.0744137	total: 975ms	remaining: 375ms
156:	learn: 0.0736891	total: 983ms	remaining: 369ms
157:	learn: 0.0727363	total: 989ms	remaining: 363ms
158:	learn: 0.0720683	total: 996ms	remaining: 357ms
159:	learn: 0.0714686	total: 1s	remaining: 351ms
160:	learn: 0.0711699	total: 1.01s	remaining: 345ms
161:	learn: 0.0704461	total: 1.01s	remaining: 338ms
162:	learn: 0.0698662	total: 1.02s	remaining: 332ms
163:	learn: 0.0693660	total: 1.03s	remaining: 326ms
164:	learn: 0.0688641	total: 1.04s	remaining: 320ms
165:	learn: 0.0681176	total: 1.04s	remaining: 314ms
166:	learn: 0.0674756	total: 1.05s	remaining: 308ms
167:	learn: 0.0666838	total: 1.06s	remaining: 302ms
168:	learn: 0.0659870	total: 1.06s	remaining: 295ms
169:	learn: 0.0652636	total: 1.07s	remaining: 289ms
170:	learn: 0.0645872	total: 1.07s	remaining: 283ms
171:	learn: 0.0640404	total: 1.08s	remaining: 277ms
172:	learn: 0.0634044	total: 1.09s	remaining: 271ms
173:	learn: 0.0628339	total: 1.1s	remaining: 265ms
174:	learn: 0.0622142	total: 1.1s	remaining: 258ms
175:	learn: 0.0617348	total: 1.11s	remaining: 252ms
176:	learn: 0.0610421	total: 1.12s	remaining: 246ms
177:	learn: 0.0602560	total: 1.12s	remaining: 240ms
178:	learn: 0.0596877	total: 1.13s	remaining: 233ms
179:	learn: 0.0590684	total: 1.14s	remaining: 227ms
180:	learn: 0.0586031	total: 1.14s	remaining: 221ms
181:	learn: 0.0580250	total: 1.15s	remaining: 215ms
182:	learn: 0.0574736	total: 1.16s	remaining: 208ms
183:	learn: 0.0572536	total: 1.16s	remaining: 201ms
184:	learn: 0.0568281	total: 1.16s	remaining: 195ms
185:	learn: 0.0562530	total: 1.17s	remaining: 189ms
186:	learn: 0.0559300	total: 1.18s	remaining: 183ms
187:	learn: 0.0554470	total: 1.18s	remaining: 176ms
188:	learn: 0.0549838	total: 1.19s	remaining: 170ms
189:	learn: 0.0544960	total: 1.2s	remaining: 164ms
190:	learn: 0.0541547	total: 1.2s	remaining: 158ms
191:	learn: 0.0536445	total: 1.21s	remaining: 151ms
192:	learn: 0.0532039	total: 1.22s	remaining: 145ms
193:	learn: 0.0527802	total: 1.23s	remaining: 139ms
194:	learn: 0.0523749	total: 1.23s	remaining: 133ms
195:	learn: 0.0519851	total: 1.24s	remaining: 126ms
196:	learn: 0.0515635	total: 1.24s	remaining: 120ms
197:	learn: 0.0510358	total: 1.25s	remaining: 114ms
198:	learn: 0.0505346	total: 1.26s	remaining: 107ms
199:	learn: 0.0500994	total: 1.26s	remaining: 101ms
200:	learn: 0.0495509	total: 1.27s	remaining: 94.9ms
201:	learn: 0.0491945	total: 1.28s	remaining: 88.5ms
202:	learn: 0.0488242	total: 1.28s	remaining: 82.2ms
203:	learn: 0.0483782	total: 1.29s	remaining: 75.9ms
204:	learn: 0.0479460	total: 1.3s	remaining: 69.6ms
205:	learn: 0.0476372	total: 1.3s	remaining: 63.3ms
206:	learn: 0.0472878	total: 1.31s	remaining: 57ms
207:	learn: 0.0468807	total: 1.32s	remaining: 50.6ms
208:	learn: 0.0464471	total: 1.32s	remaining: 44.3ms
209:	learn: 0.0460478	total: 1.33s	remaining: 38ms
210:	learn: 0.0455307	total: 1.34s	remaining: 31.7ms
211:	learn: 0.0451781	total: 1.34s	remaining: 25.3ms
212:	learn: 0.0448284	total: 1.35s	remaining: 19ms
213:	learn: 0.0444621	total: 1.36s	remaining: 12.7ms
214:	learn: 0.0441131	total: 1.36s	remaining: 6.35ms
215:	learn: 0.0438406	total: 1.37s	remaining: 0us
0:	learn: 0.6909624	total: 4.68ms	remaining: 599ms
1:	learn: 0.6887341	total: 8.41ms	remaining: 534ms
2:	learn: 0.6864828	total: 13.1ms	remaining: 548ms
3:	learn: 0.6842912	total: 16.2ms	remaining: 507ms
4:	learn: 0.6820542	total: 19ms	remaining: 470ms
5:	learn: 0.6798697	total: 21.8ms	remaining: 446ms
6:	learn: 0.6776459	total: 24.7ms	remaining: 431ms
7:	learn: 0.6755190	total: 27.5ms	remaining: 416ms
8:	learn: 0.6737782	total: 30.8ms	remaining: 411ms
9:	learn: 0.6716091	total: 34ms	remaining: 404ms
10:	learn: 0.6695445	total: 37.1ms	remaining: 398ms
11:	learn: 0.6675571	total: 39.6ms	remaining: 386ms
12:	learn: 0.6653586	total: 42.7ms	remaining: 381ms
13:	learn: 0.6634430	total: 45.6ms	remaining: 375ms
14:	learn: 0.6615717	total: 48.4ms	remaining: 368ms
15:	learn: 0.6595091	total: 50.8ms	remaining: 359ms
16:	learn: 0.6574817	total: 53.8ms	remaining: 354ms
17:	learn: 0.6555101	total: 56.8ms	remaining: 350ms
18:	learn: 0.6536575	total: 60ms	remaining: 347ms
19:	learn: 0.6518658	total: 62.3ms	remaining: 340ms
20:	learn: 0.6498666	total: 65.3ms	remaining: 336ms
21:	learn: 0.6478485	total: 68ms	remaining: 331ms
22:	learn: 0.6457646	total: 70.4ms	remaining: 325ms
23:	learn: 0.6438889	total: 73.5ms	remaining: 322ms
24:	learn: 0.6420604	total: 76.4ms	remaining: 318ms
25:	learn: 0.6400377	total: 78.7ms	remaining: 312ms
26:	learn: 0.6380044	total: 81.7ms	remaining: 309ms
27:	learn: 0.6359714	total: 84.8ms	remaining: 306ms
28:	learn: 0.6341450	total: 88ms	remaining: 303ms
29:	learn: 0.6322039	total: 91ms	remaining: 300ms
30:	learn: 0.6303453	total: 94.2ms	remaining: 298ms
31:	learn: 0.6283165	total: 96.7ms	remaining: 293ms
32:	learn: 0.6264733	total: 99.7ms	remaining: 290ms
33:	learn: 0.6246262	total: 103ms	remaining: 287ms
34:	learn: 0.6229391	total: 106ms	remaining: 284ms
35:	learn: 0.6211291	total: 108ms	remaining: 279ms
36:	learn: 0.6192092	total: 110ms	remaining: 274ms
37:	learn: 0.6175569	total: 113ms	remaining: 271ms
38:	learn: 0.6156843	total: 116ms	remaining: 268ms
39:	learn: 0.6139375	total: 119ms	remaining: 265ms
40:	learn: 0.6123204	total: 122ms	remaining: 261ms
41:	learn: 0.6106448	total: 125ms	remaining: 259ms
42:	learn: 0.6089517	total: 127ms	remaining: 255ms
43:	learn: 0.6070351	total: 130ms	remaining: 251ms
44:	learn: 0.6054684	total: 133ms	remaining: 248ms
45:	learn: 0.6038066	total: 136ms	remaining: 245ms
46:	learn: 0.6022112	total: 139ms	remaining: 242ms
47:	learn: 0.6005649	total: 142ms	remaining: 239ms
48:	learn: 0.5989114	total: 144ms	remaining: 235ms
49:	learn: 0.5973937	total: 147ms	remaining: 232ms
50:	learn: 0.5958215	total: 149ms	remaining: 228ms
51:	learn: 0.5941832	total: 152ms	remaining: 225ms
52:	learn: 0.5924831	total: 155ms	remaining: 222ms
53:	learn: 0.5908147	total: 157ms	remaining: 219ms
54:	learn: 0.5892053	total: 161ms	remaining: 216ms
55:	learn: 0.5877772	total: 163ms	remaining: 213ms
56:	learn: 0.5862405	total: 166ms	remaining: 210ms
57:	learn: 0.5845492	total: 169ms	remaining: 207ms
58:	learn: 0.5832342	total: 172ms	remaining: 204ms
59:	learn: 0.5815182	total: 175ms	remaining: 201ms
60:	learn: 0.5799443	total: 179ms	remaining: 199ms
61:	learn: 0.5783867	total: 182ms	remaining: 197ms
62:	learn: 0.5769650	total: 185ms	remaining: 193ms
63:	learn: 0.5754822	total: 187ms	remaining: 190ms
64:	learn: 0.5740796	total: 190ms	remaining: 187ms
65:	learn: 0.5726982	total: 193ms	remaining: 185ms
66:	learn: 0.5713807	total: 196ms	remaining: 182ms
67:	learn: 0.5699709	total: 199ms	remaining: 179ms
68:	learn: 0.5687282	total: 203ms	remaining: 176ms
69:	learn: 0.5671936	total: 206ms	remaining: 174ms
70:	learn: 0.5658969	total: 209ms	remaining: 171ms
71:	learn: 0.5646120	total: 212ms	remaining: 168ms
72:	learn: 0.5632482	total: 215ms	remaining: 165ms
73:	learn: 0.5616692	total: 217ms	remaining: 162ms
74:	learn: 0.5603190	total: 220ms	remaining: 159ms
75:	learn: 0.5590668	total: 223ms	remaining: 156ms
76:	learn: 0.5576541	total: 226ms	remaining: 153ms
77:	learn: 0.5561971	total: 230ms	remaining: 150ms
78:	learn: 0.5547796	total: 232ms	remaining: 147ms
79:	learn: 0.5534201	total: 235ms	remaining: 144ms
80:	learn: 0.5520230	total: 238ms	remaining: 141ms
81:	learn: 0.5507649	total: 240ms	remaining: 138ms
82:	learn: 0.5494090	total: 243ms	remaining: 135ms
83:	learn: 0.5480815	total: 247ms	remaining: 132ms
84:	learn: 0.5467741	total: 249ms	remaining: 129ms
85:	learn: 0.5455228	total: 252ms	remaining: 126ms
86:	learn: 0.5442551	total: 254ms	remaining: 123ms
87:	learn: 0.5429247	total: 258ms	remaining: 120ms
88:	learn: 0.5416327	total: 260ms	remaining: 117ms
89:	learn: 0.5404305	total: 264ms	remaining: 114ms
90:	learn: 0.5392086	total: 266ms	remaining: 111ms
91:	learn: 0.5378771	total: 269ms	remaining: 108ms
92:	learn: 0.5367633	total: 273ms	remaining: 105ms
93:	learn: 0.5354581	total: 276ms	remaining: 103ms
94:	learn: 0.5341501	total: 278ms	remaining: 99.5ms
95:	learn: 0.5328787	total: 281ms	remaining: 96.6ms
96:	learn: 0.5316238	total: 284ms	remaining: 93.7ms
97:	learn: 0.5302866	total: 287ms	remaining: 90.8ms
98:	learn: 0.5291404	total: 290ms	remaining: 87.9ms
99:	learn: 0.5279848	total: 293ms	remaining: 84.9ms
100:	learn: 0.5268096	total: 296ms	remaining: 82ms
101:	learn: 0.5256371	total: 299ms	remaining: 79.2ms
102:	learn: 0.5246266	total: 302ms	remaining: 76.3ms
103:	learn: 0.5233615	total: 305ms	remaining: 73.3ms
104:	learn: 0.5220919	total: 308ms	remaining: 70.4ms
105:	learn: 0.5209833	total: 311ms	remaining: 67.5ms
106:	learn: 0.5199897	total: 314ms	remaining: 64.6ms
107:	learn: 0.5187569	total: 317ms	remaining: 61.7ms
108:	learn: 0.5176776	total: 321ms	remaining: 58.8ms
109:	learn: 0.5164798	total: 323ms	remaining: 55.8ms
110:	learn: 0.5155364	total: 324ms	remaining: 52.5ms
111:	learn: 0.5144992	total: 326ms	remaining: 49.5ms
112:	learn: 0.5133022	total: 329ms	remaining: 46.6ms
113:	learn: 0.5120029	total: 332ms	remaining: 43.7ms
114:	learn: 0.5109842	total: 335ms	remaining: 40.8ms
115:	learn: 0.5098414	total: 338ms	remaining: 37.9ms
116:	learn: 0.5086451	total: 341ms	remaining: 35ms
117:	learn: 0.5074471	total: 344ms	remaining: 32.1ms
118:	learn: 0.5062734	total: 347ms	remaining: 29.1ms
119:	learn: 0.5052909	total: 350ms	remaining: 26.2ms
120:	learn: 0.5043167	total: 353ms	remaining: 23.3ms
121:	learn: 0.5032139	total: 356ms	remaining: 20.4ms
122:	learn: 0.5021113	total: 359ms	remaining: 17.5ms
123:	learn: 0.5010889	total: 362ms	remaining: 14.6ms
124:	learn: 0.5000888	total: 365ms	remaining: 11.7ms
125:	learn: 0.4991509	total: 366ms	remaining: 8.71ms
126:	learn: 0.4984441	total: 366ms	remaining: 5.77ms
127:	learn: 0.4974518	total: 370ms	remaining: 2.89ms
128:	learn: 0.4965281	total: 373ms	remaining: 0us

## Predict

In [11]:
preds_label = {}
for task in ['agnostic', 'aware']:
    preds_label['test-' + task] = best_models['val-' + task].predict(X['test-' + task])
    print(f'test-{task} - done!')

test-agnostic - done!
test-aware - done!

# CatBoost Regressor
## Find parameters

In [20]:
# Определение функции для оптимизации
def objective(trial):
    params = {
        'iterations': trial.suggest_int('iterations', 50, 400),
        'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
        'depth': trial.suggest_int('depth', 4, 14),
        'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
        'border_count': trial.suggest_int('border_count', 5, 200),
        'verbose': False,
        'random_seed': RANDOM_SEED
    }

    model = cb.CatBoostRegressor(**params)

    # Кросс-валидация
    cv = KFold(n_splits=10, shuffle=True, random_state=RANDOM_SEED)
    mse = - cross_val_score(model, X[df_name], y[df_name]['p'], cv=cv, scoring='neg_mean_squared_error').mean()

    return mse

best_params_dict = {}
for df_name in ['val-agnostic', 'val-aware']:
    # Создание объекта study и запуск оптимизации
    study = optuna.create_study(direction='minimize')
    study.optimize(objective, n_trials=50)

    # Получение лучших параметров
    best_params_dict[df_name] = study.best_params

for df_name in ['val-agnostic', 'val-aware']:
    print("Best Params:", df_name.ljust(15), best_params_dict[df_name])

[I 2024-02-01 14:29:39,519] A new study created in memory with name: no-name-049829cf-3f10-4d75-affa-e50f5a419b97
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:29:40,809] Trial 0 finished with value: 0.0512660899058172 and parameters: {'iterations': 106, 'learning_rate': 0.030194066922146594, 'depth': 7, 'l2_leaf_reg': 0.07505738236497708, 'border_count': 5}. Best is trial 0 with value: 0.0512660899058172.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:30:40,822] Trial 1 finished with value: 0.05679613608179819 and parameters: {'iterations': 354, 'learning_rate': 0.00516838738005228, 'depth': 14, 'l2_leaf_reg': 0.27455451967441685, 'border_count': 39}. Best is trial 0 with value: 0.0512660899058172.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:30:50,417] Trial 2 finished with value: 0.05020186543416495 and parameters: {'iterations': 352, 'learning_rate': 0.014759869457313647, 'depth': 9, 'l2_leaf_reg': 1.2906531129699628, 'border_count': 141}. Best is trial 2 with value: 0.05020186543416495.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:30:53,949] Trial 3 finished with value: 0.07950741934458781 and parameters: {'iterations': 91, 'learning_rate': 0.006722639990092632, 'depth': 10, 'l2_leaf_reg': 1.6143359107425277, 'border_count': 17}. Best is trial 2 with value: 0.05020186543416495.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:31:00,799] Trial 4 finished with value: 0.05130618408100799 and parameters: {'iterations': 259, 'learning_rate': 0.025837038121048483, 'depth': 10, 'l2_leaf_reg': 1.2988258882468535, 'border_count': 35}. Best is trial 2 with value: 0.05020186543416495.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:31:12,785] Trial 5 finished with value: 0.05418985517776298 and parameters: {'iterations': 150, 'learning_rate': 0.0795302909584736, 'depth': 13, 'l2_leaf_reg': 0.06501533342420074, 'border_count': 19}. Best is trial 2 with value: 0.05020186543416495.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:31:28,882] Trial 6 finished with value: 0.05356070049035224 and parameters: {'iterations': 149, 'learning_rate': 0.12990233209509083, 'depth': 12, 'l2_leaf_reg': 0.0039082403142123275, 'border_count': 83}. Best is trial 2 with value: 0.05020186543416495.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:31:30,220] Trial 7 finished with value: 0.05076403592326101 and parameters: {'iterations': 185, 'learning_rate': 0.019124258965951685, 'depth': 4, 'l2_leaf_reg': 0.012987047643576258, 'border_count': 84}. Best is trial 2 with value: 0.05020186543416495.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:31:56,589] Trial 8 finished with value: 0.0582482007803982 and parameters: {'iterations': 150, 'learning_rate': 0.40327434006166646, 'depth': 12, 'l2_leaf_reg': 0.00436583318335275, 'border_count': 191}. Best is trial 2 with value: 0.05020186543416495.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:32:26,904] Trial 9 finished with value: 0.053167826937693875 and parameters: {'iterations': 379, 'learning_rate': 0.09363182767729201, 'depth': 13, 'l2_leaf_reg': 0.45754387006863684, 'border_count': 15}. Best is trial 2 with value: 0.05020186543416495.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:32:31,937] Trial 10 finished with value: 0.051525287040832715 and parameters: {'iterations': 295, 'learning_rate': 0.012113948121436078, 'depth': 7, 'l2_leaf_reg': 8.540096957690729, 'border_count': 168}. Best is trial 2 with value: 0.05020186543416495.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:32:36,686] Trial 11 finished with value: 0.05117581532399752 and parameters: {'iterations': 214, 'learning_rate': 0.014493754554424554, 'depth': 4, 'l2_leaf_reg': 0.011434852780099874, 'border_count': 133}. Best is trial 2 with value: 0.05020186543416495.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:32:39,104] Trial 12 finished with value: 0.04977235120626057 and parameters: {'iterations': 313, 'learning_rate': 0.03219512631102687, 'depth': 4, 'l2_leaf_reg': 0.025026321407717884, 'border_count': 99}. Best is trial 12 with value: 0.04977235120626057.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:32:44,188] Trial 13 finished with value: 0.0519581201344001 and parameters: {'iterations': 315, 'learning_rate': 0.03655154573700328, 'depth': 7, 'l2_leaf_reg': 0.030580111232726852, 'border_count': 123}. Best is trial 12 with value: 0.04977235120626057.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:32:49,210] Trial 14 finished with value: 0.050867293096194664 and parameters: {'iterations': 394, 'learning_rate': 0.061384339911571266, 'depth': 6, 'l2_leaf_reg': 6.849846647240862, 'border_count': 144}. Best is trial 12 with value: 0.04977235120626057.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:32:57,112] Trial 15 finished with value: 0.050814001274237394 and parameters: {'iterations': 325, 'learning_rate': 0.009282236507902128, 'depth': 9, 'l2_leaf_reg': 0.24896534730729591, 'border_count': 106}. Best is trial 12 with value: 0.04977235120626057.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:32:59,589] Trial 16 finished with value: 0.05946447261796552 and parameters: {'iterations': 270, 'learning_rate': 0.20901789273140403, 'depth': 5, 'l2_leaf_reg': 0.0010779234879559388, 'border_count': 73}. Best is trial 12 with value: 0.04977235120626057.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:33:11,370] Trial 17 finished with value: 0.05168571198308046 and parameters: {'iterations': 351, 'learning_rate': 0.0469078895706317, 'depth': 9, 'l2_leaf_reg': 2.0916397646280895, 'border_count': 162}. Best is trial 12 with value: 0.04977235120626057.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:33:12,544] Trial 18 finished with value: 0.06263571379518919 and parameters: {'iterations': 50, 'learning_rate': 0.020489356250028807, 'depth': 8, 'l2_leaf_reg': 0.16210450137332846, 'border_count': 107}. Best is trial 12 with value: 0.04977235120626057.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:33:22,743] Trial 19 finished with value: 0.05241845266797431 and parameters: {'iterations': 246, 'learning_rate': 0.010345629457856338, 'depth': 11, 'l2_leaf_reg': 0.603309664025752, 'border_count': 61}. Best is trial 12 with value: 0.04977235120626057.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:33:25,637] Trial 20 finished with value: 0.050874246832600035 and parameters: {'iterations': 293, 'learning_rate': 0.04194933466964669, 'depth': 5, 'l2_leaf_reg': 0.03055032820180176, 'border_count': 163}. Best is trial 12 with value: 0.04977235120626057.
/tmp/ipykernel_1382105/2108142599.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
/tmp/ipykernel_1382105/2108142599.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2024-02-01 14:33:27,198] Trial 21 finished with value: 0.050637082305971325 and parameters: {'iterations': 203, 'learning_rate': 0.017423316203376265, 'depth': 4, 'l2_leaf_reg': 0.013437525323675646, 'border_count': 89}. Best is trial 12 with value: 0.04977235120626057.

Best Params: val-agnostic    {'iterations': 394, 'learning_rate': 0.021608465544161754, 'depth': 4, 'l2_leaf_reg': 0.007156537267301533, 'border_count': 98}
Best Params: val-aware       {'iterations': 135, 'learning_rate': 0.025526913154005487, 'depth': 4, 'l2_leaf_reg': 0.12536020060626074, 'border_count': 118}

## Evaluate

In [21]:
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=RANDOM_SEED)

mean_corr_dict = {}
for df_name in ['val-agnostic', 'val-aware']:
    best_model = cb.CatBoostRegressor(**best_params_dict[df_name])
    correlation = []
    for i, (train_index, test_index) in enumerate(cv.split(X[df_name], y[df_name]['label'])):
        # Train
        X_train = X[df_name].loc[train_index]
        y_train = y[df_name]['p'].loc[train_index]
        best_model.fit(X_train, y_train)

        # Predict
        X_test = X[df_name].loc[test_index]
        y_test = y[df_name]['p'].loc[test_index]
        y_pred = best_model.predict(X_test)

        # Postprocessing
        np.clip(y_pred, 0.0, 1.0, out=y_pred)

        # Calc metric
        correlation.append(spearmanr(y_pred, y_test)[0])
        
    # Calc average metric
    mean_corr = statistics.fmean(correlation)
    mean_corr_dict[df_name] = mean_corr

for df_name in ['val-agnostic', 'val-aware']:
    print('Correlation:', df_name.ljust(15), mean_corr_dict[df_name])

0:	learn: 0.3472925	total: 955us	remaining: 376ms
1:	learn: 0.3436611	total: 1.74ms	remaining: 341ms
2:	learn: 0.3398770	total: 2.26ms	remaining: 295ms
3:	learn: 0.3361701	total: 2.84ms	remaining: 277ms
4:	learn: 0.3325002	total: 3.46ms	remaining: 269ms
5:	learn: 0.3296156	total: 3.94ms	remaining: 255ms
6:	learn: 0.3259535	total: 4.42ms	remaining: 244ms
7:	learn: 0.3227199	total: 5.69ms	remaining: 275ms
8:	learn: 0.3194918	total: 6.18ms	remaining: 264ms
9:	learn: 0.3165222	total: 6.65ms	remaining: 255ms
10:	learn: 0.3135420	total: 7.12ms	remaining: 248ms
11:	learn: 0.3110538	total: 7.55ms	remaining: 240ms
12:	learn: 0.3078641	total: 8ms	remaining: 234ms
13:	learn: 0.3051488	total: 8.43ms	remaining: 229ms
14:	learn: 0.3023948	total: 8.87ms	remaining: 224ms
15:	learn: 0.2997565	total: 9.32ms	remaining: 220ms
16:	learn: 0.2975000	total: 9.77ms	remaining: 217ms
17:	learn: 0.2951402	total: 10.2ms	remaining: 214ms
18:	learn: 0.2928885	total: 10.7ms	remaining: 211ms
19:	learn: 0.2905418	total: 11.1ms	remaining: 208ms
20:	learn: 0.2881760	total: 11.6ms	remaining: 205ms
21:	learn: 0.2860016	total: 12ms	remaining: 203ms
22:	learn: 0.2839100	total: 12.5ms	remaining: 201ms
23:	learn: 0.2819644	total: 12.9ms	remaining: 199ms
24:	learn: 0.2797783	total: 13.3ms	remaining: 197ms
25:	learn: 0.2779934	total: 13.8ms	remaining: 195ms
26:	learn: 0.2760924	total: 14.2ms	remaining: 193ms
27:	learn: 0.2741597	total: 14.6ms	remaining: 191ms
28:	learn: 0.2722642	total: 15.1ms	remaining: 190ms
29:	learn: 0.2704542	total: 15.5ms	remaining: 188ms
30:	learn: 0.2686503	total: 15.9ms	remaining: 187ms
31:	learn: 0.2668147	total: 16.4ms	remaining: 185ms
32:	learn: 0.2650883	total: 16.8ms	remaining: 184ms
33:	learn: 0.2636124	total: 17.3ms	remaining: 183ms
34:	learn: 0.2618151	total: 17.8ms	remaining: 183ms
35:	learn: 0.2604718	total: 18.2ms	remaining: 181ms
36:	learn: 0.2592316	total: 18.6ms	remaining: 180ms
37:	learn: 0.2578708	total: 19.1ms	remaining: 179ms
38:	learn: 0.2564432	total: 19.5ms	remaining: 177ms
39:	learn: 0.2551007	total: 19.9ms	remaining: 176ms
40:	learn: 0.2538522	total: 20.3ms	remaining: 175ms
41:	learn: 0.2524033	total: 20.8ms	remaining: 174ms
42:	learn: 0.2512222	total: 21.2ms	remaining: 173ms
43:	learn: 0.2500865	total: 21.6ms	remaining: 172ms
44:	learn: 0.2490252	total: 22.1ms	remaining: 171ms
45:	learn: 0.2478533	total: 22.5ms	remaining: 170ms
46:	learn: 0.2467372	total: 23ms	remaining: 170ms
47:	learn: 0.2457449	total: 23.4ms	remaining: 169ms
48:	learn: 0.2445731	total: 23.8ms	remaining: 168ms
49:	learn: 0.2437011	total: 24.3ms	remaining: 167ms
50:	learn: 0.2428243	total: 24.7ms	remaining: 166ms
51:	learn: 0.2419063	total: 25.1ms	remaining: 165ms
52:	learn: 0.2409982	total: 25.5ms	remaining: 164ms
53:	learn: 0.2401730	total: 25.9ms	remaining: 163ms
54:	learn: 0.2391913	total: 26.4ms	remaining: 162ms
55:	learn: 0.2382450	total: 26.8ms	remaining: 162ms
56:	learn: 0.2374530	total: 27.2ms	remaining: 161ms
57:	learn: 0.2366633	total: 27.6ms	remaining: 160ms
58:	learn: 0.2357833	total: 28ms	remaining: 159ms
59:	learn: 0.2350478	total: 28.4ms	remaining: 158ms
60:	learn: 0.2342504	total: 28.9ms	remaining: 158ms
61:	learn: 0.2335512	total: 29.4ms	remaining: 157ms
62:	learn: 0.2328664	total: 29.8ms	remaining: 156ms
63:	learn: 0.2320497	total: 30.2ms	remaining: 156ms
64:	learn: 0.2312723	total: 30.6ms	remaining: 155ms
65:	learn: 0.2305063	total: 31.1ms	remaining: 154ms
66:	learn: 0.2297598	total: 31.5ms	remaining: 154ms
67:	learn: 0.2292273	total: 31.9ms	remaining: 153ms
68:	learn: 0.2283116	total: 32.3ms	remaining: 152ms
69:	learn: 0.2276767	total: 32.7ms	remaining: 151ms
70:	learn: 0.2268508	total: 33.1ms	remaining: 151ms
71:	learn: 0.2263076	total: 33.6ms	remaining: 150ms
72:	learn: 0.2258037	total: 34ms	remaining: 149ms
73:	learn: 0.2251804	total: 34.4ms	remaining: 149ms
74:	learn: 0.2247472	total: 34.8ms	remaining: 148ms
75:	learn: 0.2241183	total: 35.2ms	remaining: 147ms
76:	learn: 0.2235670	total: 35.8ms	remaining: 147ms
77:	learn: 0.2230815	total: 36.2ms	remaining: 147ms
78:	learn: 0.2225242	total: 36.6ms	remaining: 146ms
79:	learn: 0.2218852	total: 37ms	remaining: 145ms
80:	learn: 0.2210613	total: 37.4ms	remaining: 145ms
81:	learn: 0.2206009	total: 37.8ms	remaining: 144ms
82:	learn: 0.2202549	total: 38.3ms	remaining: 143ms
83:	learn: 0.2196461	total: 38.7ms	remaining: 143ms
84:	learn: 0.2190125	total: 39.1ms	remaining: 142ms
85:	learn: 0.2185821	total: 39.5ms	remaining: 142ms
86:	learn: 0.2180903	total: 40ms	remaining: 141ms
87:	learn: 0.2175444	total: 40.4ms	remaining: 140ms
88:	learn: 0.2171707	total: 40.8ms	remaining: 140ms
89:	learn: 0.2167210	total: 41.2ms	remaining: 139ms
90:	learn: 0.2161952	total: 41.6ms	remaining: 139ms
91:	learn: 0.2156617	total: 42ms	remaining: 138ms
92:	learn: 0.2151868	total: 42.4ms	remaining: 137ms
93:	learn: 0.2148527	total: 42.8ms	remaining: 137ms
94:	learn: 0.2146084	total: 43.2ms	remaining: 136ms
95:	learn: 0.2142806	total: 43.6ms	remaining: 135ms
96:	learn: 0.2139746	total: 44.1ms	remaining: 135ms
97:	learn: 0.2136806	total: 44.5ms	remaining: 134ms
98:	learn: 0.2134184	total: 44.9ms	remaining: 134ms
99:	learn: 0.2130103	total: 45.3ms	remaining: 133ms
100:	learn: 0.2126071	total: 45.7ms	remaining: 133ms
101:	learn: 0.2123834	total: 46.1ms	remaining: 132ms
102:	learn: 0.2120647	total: 46.5ms	remaining: 131ms
103:	learn: 0.2117263	total: 46.9ms	remaining: 131ms
104:	learn: 0.2114591	total: 47.3ms	remaining: 130ms
105:	learn: 0.2111891	total: 47.7ms	remaining: 130ms
106:	learn: 0.2108970	total: 48.1ms	remaining: 129ms
107:	learn: 0.2106237	total: 48.5ms	remaining: 129ms
108:	learn: 0.2103547	total: 48.9ms	remaining: 128ms
109:	learn: 0.2100441	total: 49.3ms	remaining: 127ms
110:	learn: 0.2096978	total: 49.7ms	remaining: 127ms
111:	learn: 0.2092436	total: 50.1ms	remaining: 126ms
112:	learn: 0.2088861	total: 50.5ms	remaining: 126ms
113:	learn: 0.2086331	total: 50.9ms	remaining: 125ms
114:	learn: 0.2082584	total: 51.3ms	remaining: 124ms
115:	learn: 0.2080108	total: 51.7ms	remaining: 124ms
116:	learn: 0.2075770	total: 52.1ms	remaining: 123ms
117:	learn: 0.2073829	total: 52.5ms	remaining: 123ms
118:	learn: 0.2070671	total: 52.9ms	remaining: 122ms
119:	learn: 0.2067756	total: 53.3ms	remaining: 122ms
120:	learn: 0.2065913	total: 53.7ms	remaining: 121ms
121:	learn: 0.2061303	total: 54.1ms	remaining: 121ms
122:	learn: 0.2058893	total: 54.5ms	remaining: 120ms
123:	learn: 0.2055993	total: 54.9ms	remaining: 119ms
124:	learn: 0.2053236	total: 55.3ms	remaining: 119ms
125:	learn: 0.2051488	total: 55.7ms	remaining: 118ms
126:	learn: 0.2049572	total: 56.1ms	remaining: 118ms
127:	learn: 0.2048038	total: 56.5ms	remaining: 117ms
128:	learn: 0.2045712	total: 56.9ms	remaining: 117ms
129:	learn: 0.2043039	total: 57.3ms	remaining: 116ms
130:	learn: 0.2040382	total: 57.7ms	remaining: 116ms
131:	learn: 0.2038627	total: 58.1ms	remaining: 115ms
132:	learn: 0.2035892	total: 58.5ms	remaining: 115ms
133:	learn: 0.2033766	total: 58.9ms	remaining: 114ms
134:	learn: 0.2031442	total: 59.3ms	remaining: 114ms
135:	learn: 0.2028823	total: 59.7ms	remaining: 113ms
136:	learn: 0.2026625	total: 60.1ms	remaining: 113ms
137:	learn: 0.2022949	total: 60.6ms	remaining: 112ms
138:	learn: 0.2021176	total: 61ms	remaining: 112ms
139:	learn: 0.2018443	total: 61.4ms	remaining: 111ms
140:	learn: 0.2016805	total: 61.8ms	remaining: 111ms
141:	learn: 0.2014871	total: 62.2ms	remaining: 110ms
142:	learn: 0.2012190	total: 62.6ms	remaining: 110ms
143:	learn: 0.2010291	total: 63ms	remaining: 109ms
144:	learn: 0.2008336	total: 63.6ms	remaining: 109ms
145:	learn: 0.2005605	total: 64ms	remaining: 109ms
146:	learn: 0.2003346	total: 64.4ms	remaining: 108ms
147:	learn: 0.2000589	total: 64.8ms	remaining: 108ms
148:	learn: 0.1998813	total: 65.2ms	remaining: 107ms
149:	learn: 0.1997205	total: 65.6ms	remaining: 107ms
150:	learn: 0.1995970	total: 66ms	remaining: 106ms
151:	learn: 0.1993849	total: 66.4ms	remaining: 106ms
152:	learn: 0.1991417	total: 66.8ms	remaining: 105ms
153:	learn: 0.1989341	total: 67.2ms	remaining: 105ms
154:	learn: 0.1988000	total: 67.6ms	remaining: 104ms
155:	learn: 0.1986492	total: 68ms	remaining: 104ms
156:	learn: 0.1985139	total: 68.4ms	remaining: 103ms
157:	learn: 0.1982208	total: 68.8ms	remaining: 103ms
158:	learn: 0.1980735	total: 69.2ms	remaining: 102ms
159:	learn: 0.1979345	total: 69.6ms	remaining: 102ms
160:	learn: 0.1976582	total: 70ms	remaining: 101ms
161:	learn: 0.1974014	total: 70.4ms	remaining: 101ms
162:	learn: 0.1971229	total: 70.8ms	remaining: 100ms
163:	learn: 0.1970004	total: 71.2ms	remaining: 99.8ms
164:	learn: 0.1968484	total: 71.6ms	remaining: 99.3ms
165:	learn: 0.1966551	total: 72ms	remaining: 98.9ms
166:	learn: 0.1964684	total: 72.4ms	remaining: 98.4ms
167:	learn: 0.1962219	total: 72.8ms	remaining: 97.9ms
168:	learn: 0.1960006	total: 73.2ms	remaining: 97.4ms
169:	learn: 0.1958242	total: 73.6ms	remaining: 96.9ms
170:	learn: 0.1955914	total: 74ms	remaining: 96.5ms
171:	learn: 0.1954913	total: 74.4ms	remaining: 96ms
172:	learn: 0.1953693	total: 74.8ms	remaining: 95.5ms
173:	learn: 0.1951589	total: 75.2ms	remaining: 95ms
174:	learn: 0.1951042	total: 75.6ms	remaining: 94.6ms
175:	learn: 0.1949815	total: 76ms	remaining: 94.1ms
176:	learn: 0.1947722	total: 76.4ms	remaining: 93.7ms
177:	learn: 0.1946038	total: 76.8ms	remaining: 93.2ms
178:	learn: 0.1944598	total: 77.2ms	remaining: 92.7ms
179:	learn: 0.1943107	total: 77.5ms	remaining: 92.2ms
180:	learn: 0.1940945	total: 77.9ms	remaining: 91.7ms
181:	learn: 0.1938063	total: 78.3ms	remaining: 91.2ms
182:	learn: 0.1936635	total: 78.8ms	remaining: 90.8ms
183:	learn: 0.1935576	total: 79.2ms	remaining: 90.4ms
184:	learn: 0.1933506	total: 79.6ms	remaining: 89.9ms
185:	learn: 0.1931301	total: 80ms	remaining: 89.4ms
186:	learn: 0.1929164	total: 80.4ms	remaining: 89ms
187:	learn: 0.1928047	total: 80.8ms	remaining: 88.5ms
188:	learn: 0.1927022	total: 81.2ms	remaining: 88ms
189:	learn: 0.1925196	total: 81.6ms	remaining: 87.6ms
190:	learn: 0.1923531	total: 81.9ms	remaining: 87.1ms
191:	learn: 0.1922154	total: 82.3ms	remaining: 86.6ms
192:	learn: 0.1920460	total: 82.7ms	remaining: 86.2ms
193:	learn: 0.1918997	total: 83.1ms	remaining: 85.7ms
194:	learn: 0.1916742	total: 83.5ms	remaining: 85.2ms
195:	learn: 0.1914927	total: 83.9ms	remaining: 84.8ms
196:	learn: 0.1913390	total: 84.3ms	remaining: 84.3ms
197:	learn: 0.1911797	total: 84.7ms	remaining: 83.8ms
198:	learn: 0.1910556	total: 85.1ms	remaining: 83.4ms
199:	learn: 0.1909204	total: 85.4ms	remaining: 82.9ms
200:	learn: 0.1907278	total: 85.8ms	remaining: 82.4ms
201:	learn: 0.1905655	total: 86.2ms	remaining: 82ms
202:	learn: 0.1904110	total: 86.6ms	remaining: 81.5ms
203:	learn: 0.1902439	total: 87ms	remaining: 81ms
204:	learn: 0.1901035	total: 87.4ms	remaining: 80.6ms
205:	learn: 0.1899116	total: 87.8ms	remaining: 80.1ms
206:	learn: 0.1896248	total: 88.2ms	remaining: 79.6ms
207:	learn: 0.1894895	total: 88.6ms	remaining: 79.2ms
208:	learn: 0.1893751	total: 89ms	remaining: 78.7ms
209:	learn: 0.1892718	total: 89.3ms	remaining: 78.3ms
210:	learn: 0.1890358	total: 89.7ms	remaining: 77.8ms
211:	learn: 0.1888462	total: 90.1ms	remaining: 77.4ms
212:	learn: 0.1887598	total: 90.5ms	remaining: 76.9ms
213:	learn: 0.1885824	total: 90.9ms	remaining: 76.4ms
214:	learn: 0.1885075	total: 91.3ms	remaining: 76ms
215:	learn: 0.1882493	total: 91.6ms	remaining: 75.5ms
216:	learn: 0.1880714	total: 92ms	remaining: 75.1ms
217:	learn: 0.1879375	total: 92.4ms	remaining: 74.6ms
218:	learn: 0.1877830	total: 92.8ms	remaining: 74.2ms
219:	learn: 0.1876800	total: 93.2ms	remaining: 73.7ms
220:	learn: 0.1874747	total: 93.6ms	remaining: 73.3ms
221:	learn: 0.1873403	total: 94ms	remaining: 72.8ms
222:	learn: 0.1872669	total: 94.3ms	remaining: 72.3ms
223:	learn: 0.1871942	total: 94.7ms	remaining: 71.9ms
224:	learn: 0.1870570	total: 95.1ms	remaining: 71.4ms
225:	learn: 0.1869289	total: 95.4ms	remaining: 70.9ms
226:	learn: 0.1867328	total: 95.9ms	remaining: 70.5ms
227:	learn: 0.1864583	total: 96.4ms	remaining: 70.2ms
228:	learn: 0.1863210	total: 96.9ms	remaining: 69.8ms
229:	learn: 0.1861507	total: 97.3ms	remaining: 69.4ms
230:	learn: 0.1860566	total: 97.7ms	remaining: 69ms
231:	learn: 0.1859963	total: 98.1ms	remaining: 68.5ms
232:	learn: 0.1857916	total: 98.5ms	remaining: 68.1ms
233:	learn: 0.1856390	total: 98.9ms	remaining: 67.6ms
234:	learn: 0.1855435	total: 99.3ms	remaining: 67.2ms
235:	learn: 0.1853735	total: 99.7ms	remaining: 66.7ms
236:	learn: 0.1852270	total: 100ms	remaining: 66.3ms
237:	learn: 0.1851378	total: 133ms	remaining: 87ms
238:	learn: 0.1849615	total: 133ms	remaining: 86.3ms
239:	learn: 0.1848193	total: 134ms	remaining: 85.7ms
240:	learn: 0.1847035	total: 134ms	remaining: 85ms
241:	learn: 0.1845047	total: 134ms	remaining: 84.3ms
242:	learn: 0.1843925	total: 135ms	remaining: 83.7ms
243:	learn: 0.1842307	total: 135ms	remaining: 83ms
244:	learn: 0.1841361	total: 135ms	remaining: 82.3ms
245:	learn: 0.1839053	total: 136ms	remaining: 81.7ms
246:	learn: 0.1838021	total: 136ms	remaining: 81.1ms
247:	learn: 0.1835953	total: 137ms	remaining: 80.4ms
248:	learn: 0.1834870	total: 137ms	remaining: 79.8ms
249:	learn: 0.1832231	total: 137ms	remaining: 79.1ms
250:	learn: 0.1829281	total: 138ms	remaining: 78.5ms
251:	learn: 0.1828193	total: 138ms	remaining: 77.8ms
252:	learn: 0.1827528	total: 138ms	remaining: 77.2ms
253:	learn: 0.1826758	total: 139ms	remaining: 76.5ms
254:	learn: 0.1824842	total: 139ms	remaining: 75.9ms
255:	learn: 0.1823737	total: 140ms	remaining: 75.3ms
256:	learn: 0.1822925	total: 140ms	remaining: 74.6ms
257:	learn: 0.1822130	total: 140ms	remaining: 74ms
258:	learn: 0.1820086	total: 141ms	remaining: 73.4ms
259:	learn: 0.1819001	total: 141ms	remaining: 72.8ms
260:	learn: 0.1817301	total: 142ms	remaining: 72.2ms
261:	learn: 0.1816168	total: 142ms	remaining: 71.5ms
262:	learn: 0.1815344	total: 142ms	remaining: 70.9ms
263:	learn: 0.1813999	total: 143ms	remaining: 70.3ms
264:	learn: 0.1812646	total: 143ms	remaining: 69.7ms
265:	learn: 0.1811508	total: 143ms	remaining: 69ms
266:	learn: 0.1810477	total: 144ms	remaining: 68.4ms
267:	learn: 0.1809571	total: 144ms	remaining: 67.8ms
268:	learn: 0.1808056	total: 145ms	remaining: 67.2ms
269:	learn: 0.1806739	total: 145ms	remaining: 66.6ms
270:	learn: 0.1805169	total: 145ms	remaining: 66ms
271:	learn: 0.1803573	total: 146ms	remaining: 65.4ms
272:	learn: 0.1802455	total: 146ms	remaining: 64.8ms
273:	learn: 0.1801642	total: 147ms	remaining: 64.2ms
274:	learn: 0.1800328	total: 147ms	remaining: 63.6ms
275:	learn: 0.1798000	total: 147ms	remaining: 63ms
276:	learn: 0.1796892	total: 148ms	remaining: 62.4ms
277:	learn: 0.1795310	total: 148ms	remaining: 61.8ms
278:	learn: 0.1793108	total: 148ms	remaining: 61.2ms
279:	learn: 0.1791726	total: 149ms	remaining: 60.6ms
280:	learn: 0.1790274	total: 149ms	remaining: 60.1ms
281:	learn: 0.1789032	total: 150ms	remaining: 59.5ms
282:	learn: 0.1787549	total: 150ms	remaining: 58.9ms
283:	learn: 0.1786666	total: 150ms	remaining: 58.3ms
284:	learn: 0.1785844	total: 151ms	remaining: 57.7ms
285:	learn: 0.1784132	total: 151ms	remaining: 57.1ms
286:	learn: 0.1782391	total: 152ms	remaining: 56.5ms
287:	learn: 0.1780884	total: 152ms	remaining: 56ms
288:	learn: 0.1780099	total: 152ms	remaining: 55.4ms
289:	learn: 0.1777539	total: 153ms	remaining: 54.8ms
290:	learn: 0.1776662	total: 153ms	remaining: 54.2ms
291:	learn: 0.1774798	total: 154ms	remaining: 53.6ms
292:	learn: 0.1773402	total: 154ms	remaining: 53.1ms
293:	learn: 0.1772304	total: 154ms	remaining: 52.5ms
294:	learn: 0.1769909	total: 155ms	remaining: 51.9ms
295:	learn: 0.1768394	total: 155ms	remaining: 51.3ms
296:	learn: 0.1766637	total: 155ms	remaining: 50.8ms
297:	learn: 0.1764173	total: 156ms	remaining: 50.2ms
298:	learn: 0.1763245	total: 156ms	remaining: 49.6ms
299:	learn: 0.1761001	total: 157ms	remaining: 49.1ms
300:	learn: 0.1759101	total: 157ms	remaining: 48.5ms
301:	learn: 0.1757591	total: 157ms	remaining: 47.9ms
302:	learn: 0.1755021	total: 158ms	remaining: 47.4ms
303:	learn: 0.1753485	total: 158ms	remaining: 46.8ms
304:	learn: 0.1750891	total: 158ms	remaining: 46.2ms
305:	learn: 0.1749107	total: 159ms	remaining: 45.7ms
306:	learn: 0.1747306	total: 159ms	remaining: 45.1ms
307:	learn: 0.1745382	total: 160ms	remaining: 44.5ms
308:	learn: 0.1741973	total: 160ms	remaining: 44ms
309:	learn: 0.1740715	total: 160ms	remaining: 43.4ms
310:	learn: 0.1739296	total: 161ms	remaining: 42.9ms
311:	learn: 0.1737822	total: 161ms	remaining: 42.3ms
312:	learn: 0.1737132	total: 161ms	remaining: 41.8ms
313:	learn: 0.1736544	total: 162ms	remaining: 41.2ms
314:	learn: 0.1735687	total: 162ms	remaining: 40.7ms
315:	learn: 0.1734275	total: 163ms	remaining: 40.2ms
316:	learn: 0.1732275	total: 163ms	remaining: 39.6ms
317:	learn: 0.1729866	total: 163ms	remaining: 39.1ms
318:	learn: 0.1728879	total: 164ms	remaining: 38.5ms
319:	learn: 0.1726744	total: 164ms	remaining: 38ms
320:	learn: 0.1725293	total: 165ms	remaining: 37.4ms
321:	learn: 0.1723015	total: 165ms	remaining: 36.9ms
322:	learn: 0.1721577	total: 165ms	remaining: 36.3ms
323:	learn: 0.1720179	total: 166ms	remaining: 35.8ms
324:	learn: 0.1718812	total: 166ms	remaining: 35.2ms
325:	learn: 0.1717237	total: 166ms	remaining: 34.7ms
326:	learn: 0.1716400	total: 167ms	remaining: 34.2ms
327:	learn: 0.1714442	total: 167ms	remaining: 33.6ms
328:	learn: 0.1711897	total: 167ms	remaining: 33.1ms
329:	learn: 0.1709531	total: 168ms	remaining: 32.6ms
330:	learn: 0.1708730	total: 168ms	remaining: 32ms
331:	learn: 0.1706571	total: 169ms	remaining: 31.5ms
332:	learn: 0.1704664	total: 169ms	remaining: 31ms
333:	learn: 0.1702406	total: 169ms	remaining: 30.4ms
334:	learn: 0.1701225	total: 170ms	remaining: 29.9ms
335:	learn: 0.1699751	total: 170ms	remaining: 29.4ms
336:	learn: 0.1698447	total: 171ms	remaining: 28.9ms
337:	learn: 0.1697011	total: 171ms	remaining: 28.3ms
338:	learn: 0.1695276	total: 171ms	remaining: 27.8ms
339:	learn: 0.1694664	total: 172ms	remaining: 27.3ms
340:	learn: 0.1693818	total: 172ms	remaining: 26.8ms
341:	learn: 0.1692729	total: 173ms	remaining: 26.2ms
342:	learn: 0.1691323	total: 173ms	remaining: 25.7ms
343:	learn: 0.1689766	total: 173ms	remaining: 25.2ms
344:	learn: 0.1688407	total: 174ms	remaining: 24.7ms
345:	learn: 0.1685723	total: 174ms	remaining: 24.1ms
346:	learn: 0.1683781	total: 174ms	remaining: 23.6ms
347:	learn: 0.1681501	total: 175ms	remaining: 23.1ms
348:	learn: 0.1678794	total: 175ms	remaining: 22.6ms
349:	learn: 0.1676775	total: 176ms	remaining: 22.1ms
350:	learn: 0.1674803	total: 176ms	remaining: 21.6ms
351:	learn: 0.1674225	total: 176ms	remaining: 21ms
352:	learn: 0.1673120	total: 177ms	remaining: 20.5ms
353:	learn: 0.1670793	total: 178ms	remaining: 20.1ms
354:	learn: 0.1668358	total: 178ms	remaining: 19.6ms
355:	learn: 0.1666674	total: 179ms	remaining: 19.1ms
356:	learn: 0.1665394	total: 179ms	remaining: 18.5ms
357:	learn: 0.1663809	total: 179ms	remaining: 18ms
358:	learn: 0.1663311	total: 180ms	remaining: 17.5ms
359:	learn: 0.1662312	total: 180ms	remaining: 17ms
360:	learn: 0.1660750	total: 180ms	remaining: 16.5ms
361:	learn: 0.1659747	total: 181ms	remaining: 16ms
362:	learn: 0.1658429	total: 181ms	remaining: 15.5ms
363:	learn: 0.1657494	total: 182ms	remaining: 15ms
364:	learn: 0.1655233	total: 182ms	remaining: 14.5ms
365:	learn: 0.1654159	total: 182ms	remaining: 14ms
366:	learn: 0.1652596	total: 183ms	remaining: 13.4ms
367:	learn: 0.1649929	total: 183ms	remaining: 12.9ms
368:	learn: 0.1649166	total: 183ms	remaining: 12.4ms
369:	learn: 0.1647424	total: 184ms	remaining: 11.9ms
370:	learn: 0.1645929	total: 187ms	remaining: 11.6ms
371:	learn: 0.1643719	total: 188ms	remaining: 11.1ms
372:	learn: 0.1643065	total: 224ms	remaining: 12.6ms
373:	learn: 0.1641995	total: 225ms	remaining: 12ms
374:	learn: 0.1639818	total: 225ms	remaining: 11.4ms
375:	learn: 0.1637236	total: 225ms	remaining: 10.8ms
376:	learn: 0.1635365	total: 226ms	remaining: 10.2ms
377:	learn: 0.1633571	total: 226ms	remaining: 9.57ms
378:	learn: 0.1632664	total: 227ms	remaining: 8.97ms

## Train

In [22]:
best_models = {}
for df_name in ['val-agnostic', 'val-aware']:
    # Обучение модели с лучшими параметрами
    best_model = cb.CatBoostRegressor(**best_params_dict[df_name])
    best_model.fit(X[df_name], y[df_name]['p'])
    best_models[df_name] = best_model

0:	learn: 0.3473506	total: 820us	remaining: 323ms
1:	learn: 0.3434880	total: 1.52ms	remaining: 298ms
2:	learn: 0.3396337	total: 3.62ms	remaining: 471ms
3:	learn: 0.3358682	total: 4.08ms	remaining: 398ms
4:	learn: 0.3320848	total: 4.57ms	remaining: 355ms
5:	learn: 0.3290572	total: 4.99ms	remaining: 323ms
6:	learn: 0.3253565	total: 5.42ms	remaining: 300ms
7:	learn: 0.3220641	total: 5.83ms	remaining: 281ms
8:	learn: 0.3186425	total: 6.22ms	remaining: 266ms
9:	learn: 0.3154447	total: 6.61ms	remaining: 254ms
10:	learn: 0.3123588	total: 7.01ms	remaining: 244ms
11:	learn: 0.3094876	total: 7.4ms	remaining: 236ms
12:	learn: 0.3063810	total: 7.79ms	remaining: 228ms
13:	learn: 0.3039051	total: 8.18ms	remaining: 222ms
14:	learn: 0.3012857	total: 8.58ms	remaining: 217ms
15:	learn: 0.2985234	total: 8.98ms	remaining: 212ms
16:	learn: 0.2959165	total: 9.37ms	remaining: 208ms
17:	learn: 0.2933185	total: 9.76ms	remaining: 204ms
18:	learn: 0.2909656	total: 10.1ms	remaining: 200ms
19:	learn: 0.2885684	total: 10.6ms	remaining: 198ms
20:	learn: 0.2862009	total: 11ms	remaining: 195ms
21:	learn: 0.2838597	total: 11.3ms	remaining: 191ms
22:	learn: 0.2817225	total: 11.6ms	remaining: 187ms
23:	learn: 0.2798726	total: 12ms	remaining: 184ms
24:	learn: 0.2776553	total: 12.3ms	remaining: 181ms
25:	learn: 0.2759164	total: 12.7ms	remaining: 179ms
26:	learn: 0.2739964	total: 13ms	remaining: 177ms
27:	learn: 0.2719574	total: 13.4ms	remaining: 175ms
28:	learn: 0.2700376	total: 13.8ms	remaining: 174ms
29:	learn: 0.2682839	total: 14.2ms	remaining: 172ms
30:	learn: 0.2666157	total: 14.6ms	remaining: 171ms
31:	learn: 0.2649289	total: 15ms	remaining: 169ms
32:	learn: 0.2632146	total: 15.4ms	remaining: 168ms
33:	learn: 0.2616905	total: 15.7ms	remaining: 167ms
34:	learn: 0.2599794	total: 16.1ms	remaining: 165ms
35:	learn: 0.2587871	total: 16.5ms	remaining: 164ms
36:	learn: 0.2575583	total: 16.9ms	remaining: 163ms
37:	learn: 0.2562125	total: 17.3ms	remaining: 162ms
38:	learn: 0.2549154	total: 17.7ms	remaining: 161ms
39:	learn: 0.2535524	total: 18.1ms	remaining: 160ms
40:	learn: 0.2522321	total: 18.4ms	remaining: 159ms
41:	learn: 0.2507946	total: 18.8ms	remaining: 158ms
42:	learn: 0.2495857	total: 19.2ms	remaining: 157ms
43:	learn: 0.2484670	total: 19.6ms	remaining: 156ms
44:	learn: 0.2473831	total: 20ms	remaining: 155ms
45:	learn: 0.2461678	total: 20.4ms	remaining: 154ms
46:	learn: 0.2449765	total: 20.8ms	remaining: 153ms
47:	learn: 0.2440142	total: 21.2ms	remaining: 153ms
48:	learn: 0.2430888	total: 21.6ms	remaining: 152ms
49:	learn: 0.2422291	total: 22ms	remaining: 151ms
50:	learn: 0.2413202	total: 22.3ms	remaining: 150ms
51:	learn: 0.2403346	total: 22.7ms	remaining: 149ms
52:	learn: 0.2394547	total: 23.1ms	remaining: 149ms
53:	learn: 0.2386190	total: 23.5ms	remaining: 148ms
54:	learn: 0.2376704	total: 23.9ms	remaining: 147ms
55:	learn: 0.2368082	total: 24.3ms	remaining: 147ms
56:	learn: 0.2359154	total: 24.7ms	remaining: 146ms
57:	learn: 0.2352116	total: 25.1ms	remaining: 145ms
58:	learn: 0.2344235	total: 25.5ms	remaining: 145ms
59:	learn: 0.2336462	total: 25.9ms	remaining: 144ms
60:	learn: 0.2329631	total: 26.3ms	remaining: 143ms
61:	learn: 0.2321719	total: 26.7ms	remaining: 143ms
62:	learn: 0.2314986	total: 27ms	remaining: 142ms
63:	learn: 0.2307406	total: 27.4ms	remaining: 141ms
64:	learn: 0.2298547	total: 27.8ms	remaining: 141ms
65:	learn: 0.2290695	total: 28.2ms	remaining: 140ms
66:	learn: 0.2282996	total: 28.6ms	remaining: 139ms
67:	learn: 0.2277910	total: 28.9ms	remaining: 139ms
68:	learn: 0.2269916	total: 29.3ms	remaining: 138ms
69:	learn: 0.2261888	total: 29.7ms	remaining: 137ms
70:	learn: 0.2255683	total: 30.1ms	remaining: 137ms
71:	learn: 0.2250856	total: 30.5ms	remaining: 136ms
72:	learn: 0.2246756	total: 30.9ms	remaining: 136ms
73:	learn: 0.2238777	total: 31.2ms	remaining: 135ms
74:	learn: 0.2232622	total: 31.6ms	remaining: 134ms
75:	learn: 0.2226277	total: 32ms	remaining: 134ms
76:	learn: 0.2220610	total: 32.4ms	remaining: 133ms
77:	learn: 0.2215009	total: 32.8ms	remaining: 133ms
78:	learn: 0.2210812	total: 33.1ms	remaining: 132ms
79:	learn: 0.2206525	total: 33.5ms	remaining: 132ms
80:	learn: 0.2200347	total: 33.9ms	remaining: 131ms
81:	learn: 0.2195446	total: 34.3ms	remaining: 130ms
82:	learn: 0.2191804	total: 34.7ms	remaining: 130ms
83:	learn: 0.2187699	total: 35.1ms	remaining: 129ms
84:	learn: 0.2184119	total: 35.5ms	remaining: 129ms
85:	learn: 0.2179456	total: 35.8ms	remaining: 128ms
86:	learn: 0.2176551	total: 36.1ms	remaining: 128ms
87:	learn: 0.2172946	total: 36.5ms	remaining: 127ms
88:	learn: 0.2170280	total: 36.9ms	remaining: 126ms
89:	learn: 0.2166585	total: 37.3ms	remaining: 126ms
90:	learn: 0.2161462	total: 37.7ms	remaining: 125ms
91:	learn: 0.2157622	total: 38ms	remaining: 125ms
92:	learn: 0.2153466	total: 38.4ms	remaining: 124ms
93:	learn: 0.2150347	total: 38.8ms	remaining: 124ms
94:	learn: 0.2147880	total: 39.2ms	remaining: 123ms
95:	learn: 0.2143562	total: 39.6ms	remaining: 123ms
96:	learn: 0.2139507	total: 40ms	remaining: 122ms
97:	learn: 0.2135695	total: 40.4ms	remaining: 122ms
98:	learn: 0.2132944	total: 40.8ms	remaining: 121ms
99:	learn: 0.2129197	total: 41.1ms	remaining: 121ms
100:	learn: 0.2125572	total: 41.5ms	remaining: 120ms
101:	learn: 0.2122455	total: 41.9ms	remaining: 120ms
102:	learn: 0.2119690	total: 42.3ms	remaining: 119ms
103:	learn: 0.2116296	total: 42.7ms	remaining: 119ms
104:	learn: 0.2113211	total: 43ms	remaining: 118ms
105:	learn: 0.2110271	total: 43.4ms	remaining: 118ms
106:	learn: 0.2107547	total: 43.8ms	remaining: 118ms
107:	learn: 0.2105022	total: 44.2ms	remaining: 117ms
108:	learn: 0.2102354	total: 44.8ms	remaining: 117ms
109:	learn: 0.2099240	total: 45.2ms	remaining: 117ms
110:	learn: 0.2096729	total: 45.5ms	remaining: 116ms
111:	learn: 0.2093277	total: 45.9ms	remaining: 116ms
112:	learn: 0.2091138	total: 46.3ms	remaining: 115ms
113:	learn: 0.2088511	total: 46.7ms	remaining: 115ms
114:	learn: 0.2085780	total: 47.1ms	remaining: 114ms
115:	learn: 0.2081313	total: 47.5ms	remaining: 114ms
116:	learn: 0.2078631	total: 47.8ms	remaining: 113ms
117:	learn: 0.2077406	total: 48.2ms	remaining: 113ms
118:	learn: 0.2075378	total: 48.6ms	remaining: 112ms
119:	learn: 0.2073048	total: 49ms	remaining: 112ms
120:	learn: 0.2070573	total: 49.3ms	remaining: 111ms
121:	learn: 0.2068679	total: 49.7ms	remaining: 111ms
122:	learn: 0.2065473	total: 50.1ms	remaining: 110ms
123:	learn: 0.2063598	total: 50.5ms	remaining: 110ms
124:	learn: 0.2061808	total: 50.9ms	remaining: 110ms
125:	learn: 0.2059663	total: 51.3ms	remaining: 109ms
126:	learn: 0.2056498	total: 51.6ms	remaining: 109ms
127:	learn: 0.2053892	total: 52ms	remaining: 108ms
128:	learn: 0.2051732	total: 52.5ms	remaining: 108ms
129:	learn: 0.2048793	total: 52.8ms	remaining: 107ms
130:	learn: 0.2046892	total: 53.2ms	remaining: 107ms
131:	learn: 0.2044600	total: 53.6ms	remaining: 106ms
132:	learn: 0.2041717	total: 54ms	remaining: 106ms
133:	learn: 0.2040263	total: 54.4ms	remaining: 106ms
134:	learn: 0.2038311	total: 54.8ms	remaining: 105ms
135:	learn: 0.2036540	total: 55.2ms	remaining: 105ms
136:	learn: 0.2035009	total: 55.5ms	remaining: 104ms
137:	learn: 0.2034200	total: 55.9ms	remaining: 104ms
138:	learn: 0.2032397	total: 56.3ms	remaining: 103ms
139:	learn: 0.2029912	total: 56.7ms	remaining: 103ms
140:	learn: 0.2027486	total: 57.1ms	remaining: 102ms
141:	learn: 0.2024748	total: 57.5ms	remaining: 102ms
142:	learn: 0.2022991	total: 57.9ms	remaining: 102ms
143:	learn: 0.2019957	total: 58.2ms	remaining: 101ms
144:	learn: 0.2018929	total: 58.6ms	remaining: 101ms
145:	learn: 0.2016959	total: 59ms	remaining: 100ms
146:	learn: 0.2014518	total: 59.4ms	remaining: 99.8ms
147:	learn: 0.2011591	total: 59.8ms	remaining: 99.4ms
148:	learn: 0.2009842	total: 60.2ms	remaining: 98.9ms
149:	learn: 0.2008088	total: 60.6ms	remaining: 98.6ms
150:	learn: 0.2004424	total: 61ms	remaining: 98.1ms
151:	learn: 0.2003235	total: 61.4ms	remaining: 97.7ms
152:	learn: 0.2002279	total: 61.7ms	remaining: 97.2ms
153:	learn: 0.2000878	total: 62.1ms	remaining: 96.8ms
154:	learn: 0.1999693	total: 62.5ms	remaining: 96.3ms
155:	learn: 0.1998572	total: 62.9ms	remaining: 95.9ms
156:	learn: 0.1996616	total: 63.2ms	remaining: 95.5ms
157:	learn: 0.1995082	total: 63.6ms	remaining: 95ms
158:	learn: 0.1993542	total: 64ms	remaining: 94.6ms
159:	learn: 0.1991957	total: 64.4ms	remaining: 94.2ms
160:	learn: 0.1990759	total: 64.8ms	remaining: 93.8ms
161:	learn: 0.1988494	total: 65.2ms	remaining: 93.3ms
162:	learn: 0.1987105	total: 65.5ms	remaining: 92.9ms
163:	learn: 0.1985001	total: 65.9ms	remaining: 92.4ms
164:	learn: 0.1982259	total: 66.3ms	remaining: 92ms
165:	learn: 0.1980174	total: 66.7ms	remaining: 91.6ms
166:	learn: 0.1978992	total: 67.1ms	remaining: 91.2ms
167:	learn: 0.1977352	total: 67.5ms	remaining: 90.7ms
168:	learn: 0.1976378	total: 67.9ms	remaining: 90.4ms
169:	learn: 0.1974895	total: 68.3ms	remaining: 89.9ms
170:	learn: 0.1974046	total: 68.6ms	remaining: 89.5ms
171:	learn: 0.1973329	total: 69ms	remaining: 89.1ms
172:	learn: 0.1971737	total: 69.4ms	remaining: 88.6ms
173:	learn: 0.1970842	total: 69.8ms	remaining: 88.2ms
174:	learn: 0.1969613	total: 70.1ms	remaining: 87.8ms
175:	learn: 0.1968008	total: 70.5ms	remaining: 87.4ms
176:	learn: 0.1966759	total: 70.9ms	remaining: 87ms
177:	learn: 0.1965128	total: 71.3ms	remaining: 86.5ms
178:	learn: 0.1962064	total: 71.7ms	remaining: 86.1ms
179:	learn: 0.1961191	total: 72.1ms	remaining: 85.7ms
180:	learn: 0.1958975	total: 72.5ms	remaining: 85.3ms
181:	learn: 0.1958089	total: 72.9ms	remaining: 84.9ms
182:	learn: 0.1956677	total: 73.2ms	remaining: 84.4ms
183:	learn: 0.1954230	total: 73.6ms	remaining: 84ms
184:	learn: 0.1952832	total: 74ms	remaining: 83.6ms
185:	learn: 0.1950197	total: 74.4ms	remaining: 83.2ms
186:	learn: 0.1949015	total: 74.8ms	remaining: 82.8ms
187:	learn: 0.1947722	total: 75.1ms	remaining: 82.3ms
188:	learn: 0.1946724	total: 75.5ms	remaining: 81.9ms
189:	learn: 0.1945385	total: 75.9ms	remaining: 81.5ms
190:	learn: 0.1944261	total: 76.2ms	remaining: 81ms
191:	learn: 0.1943261	total: 76.6ms	remaining: 80.6ms
192:	learn: 0.1940888	total: 77ms	remaining: 80.2ms
193:	learn: 0.1939430	total: 77.4ms	remaining: 79.8ms
194:	learn: 0.1938223	total: 77.8ms	remaining: 79.4ms
195:	learn: 0.1936355	total: 78.2ms	remaining: 79ms
196:	learn: 0.1935265	total: 78.6ms	remaining: 78.6ms
197:	learn: 0.1934181	total: 79ms	remaining: 78.2ms
198:	learn: 0.1932952	total: 79.3ms	remaining: 77.8ms
199:	learn: 0.1931468	total: 79.7ms	remaining: 77.3ms
200:	learn: 0.1930230	total: 80.1ms	remaining: 76.9ms
201:	learn: 0.1928677	total: 80.5ms	remaining: 76.5ms
202:	learn: 0.1926683	total: 80.9ms	remaining: 76.1ms
203:	learn: 0.1925533	total: 81.2ms	remaining: 75.7ms
204:	learn: 0.1924184	total: 81.6ms	remaining: 75.3ms
205:	learn: 0.1923601	total: 82ms	remaining: 74.9ms
206:	learn: 0.1922627	total: 82.4ms	remaining: 74.4ms
207:	learn: 0.1920885	total: 82.8ms	remaining: 74ms
208:	learn: 0.1919547	total: 83.2ms	remaining: 73.6ms
209:	learn: 0.1917164	total: 83.6ms	remaining: 73.2ms
210:	learn: 0.1915669	total: 84ms	remaining: 72.8ms
211:	learn: 0.1914206	total: 84.3ms	remaining: 72.4ms
212:	learn: 0.1913149	total: 84.7ms	remaining: 72ms
213:	learn: 0.1912028	total: 85.1ms	remaining: 71.6ms
214:	learn: 0.1909803	total: 85.5ms	remaining: 71.1ms
215:	learn: 0.1907438	total: 85.8ms	remaining: 70.7ms
216:	learn: 0.1905506	total: 86.2ms	remaining: 70.3ms
217:	learn: 0.1903714	total: 86.6ms	remaining: 69.9ms
218:	learn: 0.1902343	total: 87ms	remaining: 69.5ms
219:	learn: 0.1900023	total: 87.3ms	remaining: 69.1ms
220:	learn: 0.1898541	total: 87.7ms	remaining: 68.7ms
221:	learn: 0.1897154	total: 88.1ms	remaining: 68.3ms
222:	learn: 0.1894619	total: 88.5ms	remaining: 67.8ms
223:	learn: 0.1893701	total: 88.9ms	remaining: 67.4ms
224:	learn: 0.1891836	total: 89.2ms	remaining: 67ms
225:	learn: 0.1890147	total: 89.6ms	remaining: 66.6ms
226:	learn: 0.1888822	total: 90ms	remaining: 66.2ms
227:	learn: 0.1887008	total: 90.4ms	remaining: 65.8ms
228:	learn: 0.1886240	total: 90.9ms	remaining: 65.5ms
229:	learn: 0.1884985	total: 91.2ms	remaining: 65ms
230:	learn: 0.1883321	total: 91.6ms	remaining: 64.6ms
231:	learn: 0.1881443	total: 92ms	remaining: 64.2ms
232:	learn: 0.1880656	total: 92.4ms	remaining: 63.8ms
233:	learn: 0.1879426	total: 92.7ms	remaining: 63.4ms
234:	learn: 0.1877603	total: 93.1ms	remaining: 63ms
235:	learn: 0.1876566	total: 93.5ms	remaining: 62.6ms
236:	learn: 0.1875370	total: 93.9ms	remaining: 62.2ms
237:	learn: 0.1873813	total: 94.3ms	remaining: 61.8ms
238:	learn: 0.1872320	total: 94.6ms	remaining: 61.4ms
239:	learn: 0.1870991	total: 95ms	remaining: 61ms
240:	learn: 0.1869682	total: 95.4ms	remaining: 60.6ms
241:	learn: 0.1868875	total: 95.7ms	remaining: 60.1ms
242:	learn: 0.1866794	total: 96.1ms	remaining: 59.7ms
243:	learn: 0.1865013	total: 96.5ms	remaining: 59.3ms
244:	learn: 0.1862673	total: 96.9ms	remaining: 58.9ms
245:	learn: 0.1861196	total: 97.3ms	remaining: 58.5ms
246:	learn: 0.1860227	total: 97.7ms	remaining: 58.1ms
247:	learn: 0.1859244	total: 98ms	remaining: 57.7ms
248:	learn: 0.1857719	total: 98.4ms	remaining: 57.3ms
249:	learn: 0.1856564	total: 98.9ms	remaining: 57ms
250:	learn: 0.1854991	total: 99.4ms	remaining: 56.6ms
251:	learn: 0.1853920	total: 99.8ms	remaining: 56.2ms
252:	learn: 0.1852722	total: 100ms	remaining: 55.9ms
253:	learn: 0.1851804	total: 101ms	remaining: 55.5ms
254:	learn: 0.1849484	total: 101ms	remaining: 55.1ms
255:	learn: 0.1847887	total: 101ms	remaining: 54.7ms
256:	learn: 0.1846350	total: 102ms	remaining: 54.3ms
257:	learn: 0.1845373	total: 135ms	remaining: 71ms
258:	learn: 0.1843414	total: 135ms	remaining: 70.4ms
259:	learn: 0.1841788	total: 135ms	remaining: 69.8ms
260:	learn: 0.1840476	total: 136ms	remaining: 69.2ms
261:	learn: 0.1839334	total: 136ms	remaining: 68.6ms
262:	learn: 0.1838187	total: 137ms	remaining: 68.1ms
263:	learn: 0.1836494	total: 137ms	remaining: 67.5ms
264:	learn: 0.1835022	total: 137ms	remaining: 66.9ms
265:	learn: 0.1834525	total: 138ms	remaining: 66.3ms
266:	learn: 0.1832906	total: 138ms	remaining: 65.7ms
267:	learn: 0.1831675	total: 139ms	remaining: 65.2ms
268:	learn: 0.1829839	total: 139ms	remaining: 64.6ms
269:	learn: 0.1828152	total: 139ms	remaining: 64ms
270:	learn: 0.1826170	total: 140ms	remaining: 63.4ms
271:	learn: 0.1825365	total: 140ms	remaining: 62.8ms
272:	learn: 0.1823523	total: 140ms	remaining: 62.3ms
273:	learn: 0.1821404	total: 141ms	remaining: 61.7ms
274:	learn: 0.1820651	total: 141ms	remaining: 61.1ms
275:	learn: 0.1818851	total: 142ms	remaining: 60.6ms
276:	learn: 0.1817650	total: 142ms	remaining: 60ms
277:	learn: 0.1816819	total: 142ms	remaining: 59.4ms
278:	learn: 0.1815755	total: 143ms	remaining: 58.9ms
279:	learn: 0.1814172	total: 143ms	remaining: 58.3ms
280:	learn: 0.1813085	total: 144ms	remaining: 57.7ms
281:	learn: 0.1811843	total: 144ms	remaining: 57.2ms
282:	learn: 0.1810770	total: 144ms	remaining: 56.6ms
283:	learn: 0.1809690	total: 145ms	remaining: 56.1ms
284:	learn: 0.1808257	total: 145ms	remaining: 55.5ms
285:	learn: 0.1806090	total: 146ms	remaining: 55ms
286:	learn: 0.1804697	total: 146ms	remaining: 54.4ms
287:	learn: 0.1803534	total: 146ms	remaining: 53.9ms
288:	learn: 0.1801620	total: 147ms	remaining: 53.3ms
289:	learn: 0.1800782	total: 147ms	remaining: 52.8ms
290:	learn: 0.1800005	total: 148ms	remaining: 52.2ms
291:	learn: 0.1799115	total: 148ms	remaining: 51.7ms
292:	learn: 0.1797530	total: 148ms	remaining: 51.1ms
293:	learn: 0.1796343	total: 149ms	remaining: 50.6ms
294:	learn: 0.1794558	total: 149ms	remaining: 50ms
295:	learn: 0.1792490	total: 149ms	remaining: 49.5ms
296:	learn: 0.1791192	total: 150ms	remaining: 48.9ms
297:	learn: 0.1789423	total: 150ms	remaining: 48.4ms
298:	learn: 0.1787627	total: 151ms	remaining: 47.8ms
299:	learn: 0.1786378	total: 151ms	remaining: 47.3ms
300:	learn: 0.1784582	total: 151ms	remaining: 46.7ms
301:	learn: 0.1783343	total: 152ms	remaining: 46.2ms
302:	learn: 0.1781926	total: 152ms	remaining: 45.7ms
303:	learn: 0.1780797	total: 152ms	remaining: 45.1ms
304:	learn: 0.1779726	total: 153ms	remaining: 44.6ms
305:	learn: 0.1779173	total: 153ms	remaining: 44.1ms
306:	learn: 0.1777219	total: 154ms	remaining: 43.5ms
307:	learn: 0.1775867	total: 154ms	remaining: 43ms
308:	learn: 0.1774604	total: 154ms	remaining: 42.5ms
309:	learn: 0.1773241	total: 155ms	remaining: 41.9ms
310:	learn: 0.1771324	total: 155ms	remaining: 41.4ms
311:	learn: 0.1769480	total: 155ms	remaining: 40.9ms
312:	learn: 0.1767334	total: 156ms	remaining: 40.3ms
313:	learn: 0.1765511	total: 156ms	remaining: 39.8ms
314:	learn: 0.1764375	total: 157ms	remaining: 39.3ms
315:	learn: 0.1763027	total: 157ms	remaining: 38.7ms
316:	learn: 0.1761570	total: 157ms	remaining: 38.2ms
317:	learn: 0.1759593	total: 158ms	remaining: 37.7ms
318:	learn: 0.1758202	total: 158ms	remaining: 37.2ms
319:	learn: 0.1756313	total: 158ms	remaining: 36.7ms
320:	learn: 0.1754111	total: 159ms	remaining: 36.1ms
321:	learn: 0.1752565	total: 159ms	remaining: 35.6ms
322:	learn: 0.1751249	total: 160ms	remaining: 35.1ms
323:	learn: 0.1749368	total: 160ms	remaining: 34.6ms
324:	learn: 0.1748548	total: 160ms	remaining: 34ms
325:	learn: 0.1747734	total: 161ms	remaining: 33.5ms
326:	learn: 0.1746872	total: 161ms	remaining: 33ms
327:	learn: 0.1743922	total: 161ms	remaining: 32.5ms
328:	learn: 0.1742441	total: 162ms	remaining: 32ms
329:	learn: 0.1741171	total: 162ms	remaining: 31.5ms
330:	learn: 0.1739728	total: 163ms	remaining: 30.9ms
331:	learn: 0.1737803	total: 163ms	remaining: 30.4ms
332:	learn: 0.1735666	total: 163ms	remaining: 29.9ms
333:	learn: 0.1734521	total: 164ms	remaining: 29.4ms
334:	learn: 0.1732969	total: 164ms	remaining: 28.9ms
335:	learn: 0.1731997	total: 164ms	remaining: 28.4ms
336:	learn: 0.1730621	total: 165ms	remaining: 27.9ms
337:	learn: 0.1728950	total: 165ms	remaining: 27.4ms
338:	learn: 0.1727648	total: 166ms	remaining: 26.9ms
339:	learn: 0.1726033	total: 166ms	remaining: 26.4ms
340:	learn: 0.1723949	total: 166ms	remaining: 25.9ms
341:	learn: 0.1721791	total: 167ms	remaining: 25.3ms
342:	learn: 0.1720768	total: 167ms	remaining: 24.8ms
343:	learn: 0.1719171	total: 167ms	remaining: 24.3ms
344:	learn: 0.1717301	total: 168ms	remaining: 23.8ms
345:	learn: 0.1716356	total: 168ms	remaining: 23.3ms
346:	learn: 0.1714428	total: 169ms	remaining: 22.8ms
347:	learn: 0.1713117	total: 169ms	remaining: 22.3ms
348:	learn: 0.1712127	total: 169ms	remaining: 21.8ms
349:	learn: 0.1711003	total: 170ms	remaining: 21.3ms
350:	learn: 0.1710297	total: 170ms	remaining: 20.8ms
351:	learn: 0.1709582	total: 171ms	remaining: 20.3ms
352:	learn: 0.1708664	total: 171ms	remaining: 19.8ms
353:	learn: 0.1707180	total: 171ms	remaining: 19.4ms
354:	learn: 0.1705594	total: 172ms	remaining: 18.9ms
355:	learn: 0.1704557	total: 172ms	remaining: 18.4ms
356:	learn: 0.1703485	total: 173ms	remaining: 17.9ms
357:	learn: 0.1702137	total: 173ms	remaining: 17.4ms
358:	learn: 0.1700204	total: 173ms	remaining: 16.9ms
359:	learn: 0.1697865	total: 174ms	remaining: 16.4ms
360:	learn: 0.1697436	total: 174ms	remaining: 15.9ms
361:	learn: 0.1696706	total: 174ms	remaining: 15.4ms
362:	learn: 0.1694954	total: 175ms	remaining: 14.9ms
363:	learn: 0.1693606	total: 175ms	remaining: 14.4ms
364:	learn: 0.1691959	total: 176ms	remaining: 13.9ms
365:	learn: 0.1690728	total: 176ms	remaining: 13.5ms
366:	learn: 0.1689422	total: 176ms	remaining: 13ms
367:	learn: 0.1687219	total: 177ms	remaining: 12.5ms
368:	learn: 0.1686002	total: 178ms	remaining: 12.1ms
369:	learn: 0.1684768	total: 179ms	remaining: 11.6ms
370:	learn: 0.1683214	total: 179ms	remaining: 11.1ms
371:	learn: 0.1680680	total: 179ms	remaining: 10.6ms
372:	learn: 0.1679893	total: 180ms	remaining: 10.1ms
373:	learn: 0.1678774	total: 180ms	remaining: 9.63ms
374:	learn: 0.1678101	total: 180ms	remaining: 9.14ms
375:	learn: 0.1676651	total: 181ms	remaining: 8.66ms
376:	learn: 0.1674628	total: 181ms	remaining: 8.17ms
377:	learn: 0.1673691	total: 182ms	remaining: 7.69ms
378:	learn: 0.1672799	total: 182ms	remaining: 7.2ms

## Predict

In [23]:
preds_p = {}
for task in ['agnostic', 'aware']:
    preds_p['test-' + task] = best_models['val-' + task].predict(X['test-' + task])

    # Postprocessing
    np.clip(preds_p['test-' + task], 0.0, 1.0, out=preds_p['test-' + task])

    print(f'test-{task} - done!')

test-agnostic - done!
test-aware - done!

# Submit
## Form dataframe

In [24]:
submission = {}
for task in ['agnostic', 'aware']:
    submission[task] = pd.DataFrame({
        'id': X['test-' + task].index.to_list(),
        'label': preds_label['test-' + task],
        'p(Hallucination)': preds_p['test-' + task],
        })

submission['agnostic']

        id              label  p(Hallucination)
0        1  Not Hallucination          0.290485
1        2  Not Hallucination          0.531546
2        3  Not Hallucination          0.195192
3        6      Hallucination          1.000000
4        7      Hallucination          0.669374
...    ...                ...               ...
1495  2992  Not Hallucination          0.099351
1496  2993      Hallucination          0.705569
1497  2994  Not Hallucination          0.240467
1498  2996  Not Hallucination          0.200711
1499  2999  Not Hallucination          0.160928

[1500 rows x 3 columns]

In [25]:
submission['aware']

        id              label  p(Hallucination)
0        0  Not Hallucination          0.183616
1        4  Not Hallucination          0.309078
2        5      Hallucination          0.552941
3        9      Hallucination          0.695692
4       11  Not Hallucination          0.161514
...    ...                ...               ...
1495  2988  Not Hallucination          0.535501
1496  2991  Not Hallucination          0.237558
1497  2995  Not Hallucination          0.169971
1498  2997  Not Hallucination          0.181309
1499  2998      Hallucination          0.654638

[1500 rows x 3 columns]

## Save to json

In [26]:
for task in ['agnostic', 'aware']:
    json_file_path = SUBMISSION_PATH + 'test.model-' + task + '.json'

    # Check if file exists
    assert not os.path.exists(json_file_path), 'File already exists.'

    # Save to .json file
    submission[task].to_json(
        path_or_buf=json_file_path,
        orient='records',
    )

## Check file format

In [27]:
!python ./check_output.py {SUBMISSION_PATH}

all clear!