# Setup

In [1]:
import os
from pathlib import Path
import statistics

import numpy as np
import pandas as pd
from scipy.stats import spearmanr
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score, KFold, StratifiedKFold, RepeatedStratifiedKFold

import catboost as cb
import optuna

In [2]:
FIND_HYPERPARAMETERS = False
EVALUATE_ON_VAL = False
INPUT_DATA_PATH = './data/'
REFERENCE_PATH = './data/test/'
OUTPUT_DATA_PATH = './output/'
SUBMISSION_PATH = './output/catboost/test_tmp/'
RESULT_PATH = './output/catboost/test_tmp/test.score.txt'
MODELS = [
    'deberta_nli',
    'deberta_inverse_nli',
    'roberta_nli',
    'roberta_inverse_nli',
    't5_nli',
    't5_inverse_nli',
    'st_roberta_nli',
    'openchat_chain_poll',
    ]

RANDOM_SEED = 424242

Path(SUBMISSION_PATH).mkdir(parents=True, exist_ok=True)

# Load data

In [3]:
X = {}
y = {}
for sample in ['val', 'test']:
    for task in ['agnostic', 'aware']:
        # Load 'task' and 'length' features
        file = INPUT_DATA_PATH + sample + '/' + sample + '.model-' + task + '.json'
        df = pd.read_json(file, orient='records')
        if sample == 'test':
            df.set_index('id', drop=True, inplace=True)
        df['DM'] = df['task'].map({'DM': 1, 'MT': 0, 'PG': 0})
        df['MT'] = df['task'].map({'DM': 0, 'MT': 1, 'PG': 0})
        df['hyp_len'] = df['hyp'].str.len()
        df['tgt_len'] = df['tgt'].str.len()
        df['src_len'] = df['src'].str.len()
        X[sample + '-' + task] = []
        X[sample + '-' + task].append(df[['DM', 'MT', 'hyp_len', 'tgt_len', 'src_len']])
        print(file)
        
        # Load y
        df.rename(columns={"p(Hallucination)": "p"}, inplace=True)
        y[sample + '-' + task] = df[['label', 'p']]

        for model in MODELS:
            # Load features form transformer-based models
            file = OUTPUT_DATA_PATH + model + '/' + sample + '/' + sample + '.model-' + task + '.json'
            df = pd.read_json(file, orient='records')
            if sample == 'test':
                df.set_index('id', drop=True, inplace=True)
            df.rename(columns={"label": "label_" + model, "p(Hallucination)": "p_" + model}, inplace=True)
            X[sample + '-' + task].append(df)
            print(file)

./data/val/val.model-agnostic.json
./output/deberta_nli/val/val.model-agnostic.json
./output/deberta_inverse_nli/val/val.model-agnostic.json
./output/roberta_nli/val/val.model-agnostic.json
./output/roberta_inverse_nli/val/val.model-agnostic.json
./output/t5_nli/val/val.model-agnostic.json
./output/t5_inverse_nli/val/val.model-agnostic.json
./output/st_roberta_nli/val/val.model-agnostic.json
./output/openchat_chain_poll/val/val.model-agnostic.json
./data/val/val.model-aware.json
./output/deberta_nli/val/val.model-aware.json
./output/deberta_inverse_nli/val/val.model-aware.json
./output/roberta_nli/val/val.model-aware.json
./output/roberta_inverse_nli/val/val.model-aware.json
./output/t5_nli/val/val.model-aware.json
./output/t5_inverse_nli/val/val.model-aware.json
./output/st_roberta_nli/val/val.model-aware.json
./output/openchat_chain_poll/val/val.model-aware.json
./data/test/test.model-agnostic.json
./output/deberta_nli/test/test.model-agnostic.json
./output/deberta_inverse_nli/test/test.model-agnostic.json
./output/roberta_nli/test/test.model-agnostic.json
./output/roberta_inverse_nli/test/test.model-agnostic.json
./output/t5_nli/test/test.model-agnostic.json
./output/t5_inverse_nli/test/test.model-agnostic.json
./output/st_roberta_nli/test/test.model-agnostic.json
./output/openchat_chain_poll/test/test.model-agnostic.json
./data/test/test.model-aware.json
./output/deberta_nli/test/test.model-aware.json
./output/deberta_inverse_nli/test/test.model-aware.json
./output/roberta_nli/test/test.model-aware.json
./output/roberta_inverse_nli/test/test.model-aware.json
./output/t5_nli/test/test.model-aware.json
./output/t5_inverse_nli/test/test.model-aware.json
./output/st_roberta_nli/test/test.model-aware.json
./output/openchat_chain_poll/test/test.model-aware.json

In [4]:
# Concatenate dataframes by columns
X_ = {}
X_['val-agnostic'] = pd.concat(X['val-agnostic'], axis=1)
X_['val-aware'] = pd.concat(X['val-aware'], axis=1)
X_['test-agnostic'] = pd.concat(X['test-agnostic'], axis=1)
X_['test-aware'] = pd.concat(X['test-aware'], axis=1)
X = X_

# For X: drop columns with 'label' feature
for df_name in X:
    for column in X[df_name].columns:
        if column.startswith('label'):
            X[df_name].drop(columns=column, inplace=True)

# Print dataframe names
print('For X data:')
for df_name in X:
    print('\t', df_name)
print()
print('For y data:')
for df_name in y:
    print('\t', df_name)

For X data:
	 val-agnostic
	 val-aware
	 test-agnostic
	 test-aware

For y data:
	 val-agnostic
	 val-aware
	 test-agnostic
	 test-aware

In [5]:
X['val-agnostic']

,DM,MT,hyp_len,tgt_len,src_len,p_deberta_nli,p_deberta_inverse_nli,p_roberta_nli,p_roberta_inverse_nli,p_t5_nli,p_t5_inverse_nli,p_st_roberta_nli,p_openchat_chain_poll
0,1,0,41,36,316,0.002097,0.027509,0.001844,0.003966,0,0,0.053903,0
1,1,0,32,1,451,0.643224,0.616778,0.289209,0.150303,1,0,0.955537,1
2,1,0,34,36,181,0.707190,0.608000,0.993463,0.932218,1,1,0.107394,0
3,1,0,17,100,149,0.008859,0.861013,0.094564,0.229191,0,1,0.428500,0
4,1,0,39,63,441,0.004337,0.934161,0.013538,0.723117,0,1,0.059323,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,0,1,32,39,30,0.000138,0.000098,0.001673,0.001751,0,0,0.014917,0
495,0,1,42,46,48,0.000263,0.000158,0.004702,0.015190,0,0,0.024462,0
496,0,1,43,42,43,0.000291,0.000118,0.001838,0.002023,0,0,0.016321,0
497,0,1,28,31,22,0.000053,0.000040,0.000960,0.000589,0,0,0.042848,0
498,0,1,43,43,39,0.000145,0.000201,0.005383,0.002978,0,0,0.024805,0

In [6]:
y['val-agnostic']

                 label    p
0    Not Hallucination  0.2
1        Hallucination  0.8
2    Not Hallucination  0.0
3    Not Hallucination  0.2
4    Not Hallucination  0.0
..                 ...  ...
494  Not Hallucination  0.0
495  Not Hallucination  0.2
496  Not Hallucination  0.0
497  Not Hallucination  0.0
498  Not Hallucination  0.0

[499 rows x 2 columns]

# CatBoost Classifier
## Find parameters

In [7]:
# Определение функции для оптимизации
def objective(trial):
    params = {
        'iterations': trial.suggest_int('iterations', 100, 400),
        'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),
        'depth': trial.suggest_int('depth', 6, 12),
        'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-2, 10),
        'border_count': trial.suggest_int('border_count', 5, 200),
        'verbose': False,
        'random_seed': RANDOM_SEED
    }

    model = cb.CatBoostClassifier(**params)

    # Кросс-валидация
    cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=RANDOM_SEED)
    accuracy = cross_val_score(model, X[df_name], y[df_name]['label'], cv=cv, scoring='accuracy').mean()

    return accuracy

best_params_dict = {}
if FIND_HYPERPARAMETERS:
    for df_name in ['val-agnostic', 'val-aware']:
        # Создание объекта study и запуск оптимизации
        study = optuna.create_study(direction='maximize')
        study.optimize(objective, n_trials=100)

        # Получение лучших параметров
        best_params_dict[df_name] = study.best_params
else:
    best_params_dict['val-agnostic'] = {'iterations': 216, 'learning_rate': 0.0102019005543733, 'depth': 12, 'l2_leaf_reg': 0.09976943036124933, 'border_count': 39}
    best_params_dict['val-aware'] = {'iterations': 129, 'learning_rate': 0.005371920324746337, 'depth': 9, 'l2_leaf_reg': 0.6911690977933583, 'border_count': 186}

In [8]:
for df_name in ['val-agnostic', 'val-aware']:
    print("Best Params:", df_name.ljust(15), best_params_dict[df_name])

Best Params: val-agnostic    {'iterations': 216, 'learning_rate': 0.0102019005543733, 'depth': 12, 'l2_leaf_reg': 0.09976943036124933, 'border_count': 39}
Best Params: val-aware       {'iterations': 129, 'learning_rate': 0.005371920324746337, 'depth': 9, 'l2_leaf_reg': 0.6911690977933583, 'border_count': 186}

## Evaluate on validation sample

In [9]:
if EVALUATE_ON_VAL:
    cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=RANDOM_SEED)
    mean_accuracy_dict = {}
    for df_name in ['val-agnostic', 'val-aware']:
        model = cb.CatBoostClassifier(**best_params_dict[df_name])
        accuracy = []
        for i, (train_index, test_index) in enumerate(cv.split(X[df_name], y[df_name]['label'])):
            # Train
            X_train = X[df_name].loc[train_index]
            y_train = y[df_name]['label'].loc[train_index]
            model.fit(X_train, y_train)

            # Predict
            X_test = X[df_name].loc[test_index]
            y_test = y[df_name]['label'].loc[test_index]
            y_pred = model.predict(X_test)

            # Calc metric
            accuracy.append(accuracy_score(y_test, y_pred))
            
        # Calc average metric
        mean_accuracy = statistics.fmean(accuracy)
        mean_accuracy_dict[df_name] = mean_accuracy

In [10]:
if EVALUATE_ON_VAL:
    for df_name in ['val-agnostic', 'val-aware']:
        print('Accuracy:', df_name.ljust(15), mean_accuracy_dict[df_name])

## Train on 100 % of data

In [11]:
models = {}
for df_name in ['val-agnostic', 'val-aware']:
    # Обучение модели с лучшими параметрами
    model = cb.CatBoostClassifier(**best_params_dict[df_name])
    model.fit(X[df_name], y[df_name]['label'])
    models[df_name] = model

0:	learn: 0.6751101	total: 57.8ms	remaining: 12.4s
1:	learn: 0.6587802	total: 67.1ms	remaining: 7.18s
2:	learn: 0.6468968	total: 75.9ms	remaining: 5.39s

3:	learn: 0.6307475	total: 85.3ms	remaining: 4.52s
4:	learn: 0.6170895	total: 93.9ms	remaining: 3.96s
5:	learn: 0.6046888	total: 102ms	remaining: 3.57s
6:	learn: 0.5913350	total: 110ms	remaining: 3.28s
7:	learn: 0.5780215	total: 118ms	remaining: 3.06s
8:	learn: 0.5657623	total: 125ms	remaining: 2.87s
9:	learn: 0.5538815	total: 133ms	remaining: 2.73s
10:	learn: 0.5449129	total: 135ms	remaining: 2.51s
11:	learn: 0.5354257	total: 143ms	remaining: 2.42s
12:	learn: 0.5244566	total: 151ms	remaining: 2.35s
13:	learn: 0.5133151	total: 158ms	remaining: 2.27s
14:	learn: 0.5041635	total: 166ms	remaining: 2.22s
15:	learn: 0.4935288	total: 173ms	remaining: 2.16s
16:	learn: 0.4843304	total: 180ms	remaining: 2.1s
17:	learn: 0.4742745	total: 187ms	remaining: 2.05s
18:	learn: 0.4632092	total: 194ms	remaining: 2.01s
19:	learn: 0.4608192	total: 195ms	remaining: 1.91s
20:	learn: 0.4564004	total: 196ms	remaining: 1.82s
21:	learn: 0.4465431	total: 203ms	remaining: 1.79s
22:	learn: 0.4379118	total: 210ms	remaining: 1.76s
23:	learn: 0.4304782	total: 217ms	remaining: 1.73s
24:	learn: 0.4232819	total: 223ms	remaining: 1.71s
25:	learn: 0.4156932	total: 230ms	remaining: 1.68s
26:	learn: 0.4068981	total: 236ms	remaining: 1.65s
27:	learn: 0.3990236	total: 243ms	remaining: 1.63s
28:	learn: 0.3906053	total: 249ms	remaining: 1.61s
29:	learn: 0.3830022	total: 256ms	remaining: 1.59s
30:	learn: 0.3789601	total: 258ms	remaining: 1.54s
31:	learn: 0.3719426	total: 264ms	remaining: 1.52s
32:	learn: 0.3657343	total: 271ms	remaining: 1.5s
33:	learn: 0.3634045	total: 272ms	remaining: 1.45s
34:	learn: 0.3611327	total: 273ms	remaining: 1.41s
35:	learn: 0.3546332	total: 280ms	remaining: 1.4s
36:	learn: 0.3488588	total: 287ms	remaining: 1.39s
37:	learn: 0.3425723	total: 294ms	remaining: 1.38s
38:	learn: 0.3359047	total: 300ms	remaining: 1.36s
39:	learn: 0.3300586	total: 307ms	remaining: 1.35s
40:	learn: 0.3233969	total: 314ms	remaining: 1.34s
41:	learn: 0.3221760	total: 315ms	remaining: 1.3s
42:	learn: 0.3157658	total: 321ms	remaining: 1.29s
43:	learn: 0.3097335	total: 327ms	remaining: 1.28s
44:	learn: 0.3033398	total: 334ms	remaining: 1.27s
45:	learn: 0.2968684	total: 341ms	remaining: 1.26s
46:	learn: 0.2917888	total: 347ms	remaining: 1.25s
47:	learn: 0.2866535	total: 355ms	remaining: 1.24s
48:	learn: 0.2846851	total: 356ms	remaining: 1.21s
49:	learn: 0.2806351	total: 363ms	remaining: 1.21s
50:	learn: 0.2748440	total: 370ms	remaining: 1.2s
51:	learn: 0.2702596	total: 376ms	remaining: 1.19s
52:	learn: 0.2644329	total: 384ms	remaining: 1.18s
53:	learn: 0.2596431	total: 391ms	remaining: 1.17s
54:	learn: 0.2546682	total: 398ms	remaining: 1.16s
55:	learn: 0.2507795	total: 405ms	remaining: 1.16s
56:	learn: 0.2469308	total: 412ms	remaining: 1.15s
57:	learn: 0.2417432	total: 419ms	remaining: 1.14s
58:	learn: 0.2387658	total: 425ms	remaining: 1.13s
59:	learn: 0.2349872	total: 432ms	remaining: 1.12s
60:	learn: 0.2309317	total: 439ms	remaining: 1.11s
61:	learn: 0.2281697	total: 445ms	remaining: 1.11s
62:	learn: 0.2239392	total: 455ms	remaining: 1.1s
63:	learn: 0.2204618	total: 461ms	remaining: 1.09s
64:	learn: 0.2176447	total: 468ms	remaining: 1.09s
65:	learn: 0.2142279	total: 474ms	remaining: 1.08s
66:	learn: 0.2109304	total: 480ms	remaining: 1.07s
67:	learn: 0.2088059	total: 487ms	remaining: 1.06s
68:	learn: 0.2062906	total: 494ms	remaining: 1.05s
69:	learn: 0.2033432	total: 501ms	remaining: 1.04s
70:	learn: 0.2010329	total: 507ms	remaining: 1.04s
71:	learn: 0.1984433	total: 515ms	remaining: 1.03s
72:	learn: 0.1951084	total: 521ms	remaining: 1.02s
73:	learn: 0.1923848	total: 527ms	remaining: 1.01s
74:	learn: 0.1893592	total: 535ms	remaining: 1s
75:	learn: 0.1872423	total: 541ms	remaining: 996ms
76:	learn: 0.1846798	total: 548ms	remaining: 988ms
77:	learn: 0.1824977	total: 554ms	remaining: 981ms
78:	learn: 0.1792789	total: 562ms	remaining: 974ms
79:	learn: 0.1775765	total: 568ms	remaining: 966ms
80:	learn: 0.1753325	total: 575ms	remaining: 958ms
81:	learn: 0.1730996	total: 581ms	remaining: 950ms
82:	learn: 0.1708765	total: 588ms	remaining: 943ms
83:	learn: 0.1689519	total: 595ms	remaining: 935ms
84:	learn: 0.1687400	total: 596ms	remaining: 918ms
85:	learn: 0.1664823	total: 604ms	remaining: 913ms
86:	learn: 0.1644620	total: 611ms	remaining: 906ms
87:	learn: 0.1621399	total: 619ms	remaining: 900ms
88:	learn: 0.1602927	total: 626ms	remaining: 893ms
89:	learn: 0.1582884	total: 632ms	remaining: 885ms
90:	learn: 0.1558064	total: 639ms	remaining: 877ms
91:	learn: 0.1553021	total: 640ms	remaining: 863ms
92:	learn: 0.1536762	total: 646ms	remaining: 855ms
93:	learn: 0.1518848	total: 653ms	remaining: 847ms
94:	learn: 0.1497510	total: 660ms	remaining: 840ms
95:	learn: 0.1484697	total: 666ms	remaining: 833ms
96:	learn: 0.1464345	total: 673ms	remaining: 826ms
97:	learn: 0.1446984	total: 680ms	remaining: 819ms
98:	learn: 0.1427589	total: 686ms	remaining: 811ms
99:	learn: 0.1408576	total: 693ms	remaining: 804ms
100:	learn: 0.1384208	total: 700ms	remaining: 797ms
101:	learn: 0.1367271	total: 706ms	remaining: 790ms
102:	learn: 0.1353588	total: 713ms	remaining: 782ms
103:	learn: 0.1340894	total: 719ms	remaining: 774ms
104:	learn: 0.1327468	total: 726ms	remaining: 767ms
105:	learn: 0.1312669	total: 732ms	remaining: 760ms
106:	learn: 0.1293132	total: 739ms	remaining: 752ms
107:	learn: 0.1277257	total: 746ms	remaining: 746ms
108:	learn: 0.1266170	total: 753ms	remaining: 739ms
109:	learn: 0.1250630	total: 759ms	remaining: 731ms
110:	learn: 0.1235421	total: 766ms	remaining: 724ms
111:	learn: 0.1223576	total: 772ms	remaining: 717ms
112:	learn: 0.1211439	total: 779ms	remaining: 710ms
113:	learn: 0.1195694	total: 786ms	remaining: 703ms
114:	learn: 0.1183879	total: 793ms	remaining: 696ms
115:	learn: 0.1169862	total: 799ms	remaining: 689ms
116:	learn: 0.1156775	total: 805ms	remaining: 682ms
117:	learn: 0.1144741	total: 812ms	remaining: 675ms
118:	learn: 0.1126142	total: 819ms	remaining: 668ms
119:	learn: 0.1113504	total: 825ms	remaining: 660ms
120:	learn: 0.1102152	total: 832ms	remaining: 653ms
121:	learn: 0.1092779	total: 838ms	remaining: 646ms
122:	learn: 0.1079902	total: 845ms	remaining: 639ms
123:	learn: 0.1067188	total: 852ms	remaining: 632ms
124:	learn: 0.1056778	total: 859ms	remaining: 625ms
125:	learn: 0.1046144	total: 865ms	remaining: 618ms
126:	learn: 0.1034901	total: 872ms	remaining: 611ms
127:	learn: 0.1025231	total: 879ms	remaining: 604ms
128:	learn: 0.1016290	total: 885ms	remaining: 597ms
129:	learn: 0.1008903	total: 892ms	remaining: 590ms
130:	learn: 0.1000082	total: 898ms	remaining: 583ms
131:	learn: 0.0988956	total: 905ms	remaining: 576ms
132:	learn: 0.0979511	total: 911ms	remaining: 569ms
133:	learn: 0.0970535	total: 918ms	remaining: 562ms
134:	learn: 0.0962184	total: 925ms	remaining: 555ms
135:	learn: 0.0951703	total: 932ms	remaining: 548ms
136:	learn: 0.0940647	total: 938ms	remaining: 541ms
137:	learn: 0.0933401	total: 945ms	remaining: 534ms
138:	learn: 0.0921664	total: 951ms	remaining: 527ms
139:	learn: 0.0913033	total: 958ms	remaining: 520ms
140:	learn: 0.0901995	total: 965ms	remaining: 513ms
141:	learn: 0.0892731	total: 971ms	remaining: 506ms
142:	learn: 0.0892499	total: 972ms	remaining: 496ms
143:	learn: 0.0883012	total: 978ms	remaining: 489ms
144:	learn: 0.0873889	total: 984ms	remaining: 482ms
145:	learn: 0.0863367	total: 991ms	remaining: 475ms
146:	learn: 0.0854961	total: 997ms	remaining: 468ms
147:	learn: 0.0846815	total: 1s	remaining: 461ms
148:	learn: 0.0841360	total: 1.01s	remaining: 454ms
149:	learn: 0.0831717	total: 1.02s	remaining: 448ms
150:	learn: 0.0821085	total: 1.02s	remaining: 441ms
151:	learn: 0.0812875	total: 1.03s	remaining: 434ms
152:	learn: 0.0804258	total: 1.04s	remaining: 427ms
153:	learn: 0.0793657	total: 1.04s	remaining: 421ms
154:	learn: 0.0787530	total: 1.05s	remaining: 414ms
155:	learn: 0.0778898	total: 1.06s	remaining: 407ms
156:	learn: 0.0772151	total: 1.06s	remaining: 400ms
157:	learn: 0.0762392	total: 1.07s	remaining: 393ms
158:	learn: 0.0754432	total: 1.08s	remaining: 386ms
159:	learn: 0.0747585	total: 1.08s	remaining: 379ms
160:	learn: 0.0740872	total: 1.09s	remaining: 372ms
161:	learn: 0.0734808	total: 1.09s	remaining: 365ms
162:	learn: 0.0727029	total: 1.1s	remaining: 358ms
163:	learn: 0.0719038	total: 1.11s	remaining: 351ms
164:	learn: 0.0712485	total: 1.11s	remaining: 344ms
165:	learn: 0.0706912	total: 1.12s	remaining: 338ms
166:	learn: 0.0700550	total: 1.13s	remaining: 331ms
167:	learn: 0.0695956	total: 1.13s	remaining: 324ms
168:	learn: 0.0690304	total: 1.14s	remaining: 317ms
169:	learn: 0.0685206	total: 1.15s	remaining: 311ms
170:	learn: 0.0680409	total: 1.16s	remaining: 304ms
171:	learn: 0.0673400	total: 1.16s	remaining: 297ms
172:	learn: 0.0664838	total: 1.17s	remaining: 290ms
173:	learn: 0.0658697	total: 1.17s	remaining: 284ms
174:	learn: 0.0651717	total: 1.18s	remaining: 277ms
175:	learn: 0.0646582	total: 1.19s	remaining: 270ms
176:	learn: 0.0640481	total: 1.19s	remaining: 263ms
177:	learn: 0.0634030	total: 1.2s	remaining: 256ms
178:	learn: 0.0628985	total: 1.21s	remaining: 250ms
179:	learn: 0.0623055	total: 1.21s	remaining: 243ms
180:	learn: 0.0618078	total: 1.22s	remaining: 236ms
181:	learn: 0.0611252	total: 1.23s	remaining: 229ms
182:	learn: 0.0606655	total: 1.23s	remaining: 222ms
183:	learn: 0.0601610	total: 1.24s	remaining: 216ms
184:	learn: 0.0598379	total: 1.25s	remaining: 209ms
185:	learn: 0.0592475	total: 1.25s	remaining: 202ms
186:	learn: 0.0586816	total: 1.26s	remaining: 195ms
187:	learn: 0.0582972	total: 1.27s	remaining: 189ms
188:	learn: 0.0578712	total: 1.27s	remaining: 182ms
189:	learn: 0.0575904	total: 1.28s	remaining: 175ms
190:	learn: 0.0570395	total: 1.29s	remaining: 169ms
191:	learn: 0.0564388	total: 1.29s	remaining: 162ms
192:	learn: 0.0558529	total: 1.3s	remaining: 155ms
193:	learn: 0.0552773	total: 1.31s	remaining: 148ms
194:	learn: 0.0548997	total: 1.31s	remaining: 141ms
195:	learn: 0.0545050	total: 1.32s	remaining: 135ms
196:	learn: 0.0540354	total: 1.33s	remaining: 128ms
197:	learn: 0.0536275	total: 1.33s	remaining: 121ms
198:	learn: 0.0532652	total: 1.34s	remaining: 114ms
199:	learn: 0.0528254	total: 1.35s	remaining: 108ms
200:	learn: 0.0522534	total: 1.35s	remaining: 101ms
201:	learn: 0.0518905	total: 1.36s	remaining: 94.3ms
202:	learn: 0.0514827	total: 1.37s	remaining: 87.6ms
203:	learn: 0.0509236	total: 1.37s	remaining: 80.8ms
204:	learn: 0.0504457	total: 1.38s	remaining: 74.1ms
205:	learn: 0.0501599	total: 1.39s	remaining: 67.3ms
206:	learn: 0.0497306	total: 1.39s	remaining: 60.6ms
207:	learn: 0.0493678	total: 1.4s	remaining: 53.8ms
208:	learn: 0.0489522	total: 1.41s	remaining: 47.1ms
209:	learn: 0.0485533	total: 1.41s	remaining: 40.4ms
210:	learn: 0.0482378	total: 1.42s	remaining: 33.6ms
211:	learn: 0.0477925	total: 1.43s	remaining: 26.9ms
212:	learn: 0.0474341	total: 1.43s	remaining: 20.2ms
213:	learn: 0.0471524	total: 1.44s	remaining: 13.4ms
214:	learn: 0.0468524	total: 1.44s	remaining: 6.72ms
215:	learn: 0.0465831	total: 1.45s	remaining: 0us
0:	learn: 0.6909624	total: 4.16ms	remaining: 533ms
1:	learn: 0.6887341	total: 7.55ms	remaining: 479ms
2:	learn: 0.6864828	total: 10.5ms	remaining: 442ms
3:	learn: 0.6843124	total: 13.4ms	remaining: 418ms
4:	learn: 0.6822158	total: 17.5ms	remaining: 435ms
5:	learn: 0.6800316	total: 20.5ms	remaining: 420ms
6:	learn: 0.6778077	total: 23.6ms	remaining: 411ms
7:	learn: 0.6756809	total: 26.5ms	remaining: 400ms
8:	learn: 0.6739399	total: 29.7ms	remaining: 396ms
9:	learn: 0.6717704	total: 32.7ms	remaining: 390ms
10:	learn: 0.6697056	total: 35.6ms	remaining: 382ms
11:	learn: 0.6677178	total: 38.4ms	remaining: 375ms
12:	learn: 0.6655190	total: 41.3ms	remaining: 369ms
13:	learn: 0.6636034	total: 44.2ms	remaining: 363ms
14:	learn: 0.6617316	total: 46.6ms	remaining: 354ms
15:	learn: 0.6596688	total: 49.8ms	remaining: 352ms
16:	learn: 0.6576409	total: 52.7ms	remaining: 347ms
17:	learn: 0.6556694	total: 56ms	remaining: 346ms
18:	learn: 0.6538168	total: 59ms	remaining: 342ms
19:	learn: 0.6520250	total: 62ms	remaining: 338ms
20:	learn: 0.6500259	total: 65.2ms	remaining: 335ms
21:	learn: 0.6480079	total: 68.2ms	remaining: 332ms
22:	learn: 0.6460137	total: 71.2ms	remaining: 328ms
23:	learn: 0.6441377	total: 76.7ms	remaining: 336ms
24:	learn: 0.6423056	total: 79.8ms	remaining: 332ms
25:	learn: 0.6402781	total: 82.9ms	remaining: 328ms
26:	learn: 0.6382448	total: 85.8ms	remaining: 324ms
27:	learn: 0.6362549	total: 88.8ms	remaining: 320ms
28:	learn: 0.6344284	total: 91.8ms	remaining: 317ms
29:	learn: 0.6324870	total: 94.7ms	remaining: 313ms
30:	learn: 0.6306285	total: 97.9ms	remaining: 309ms
31:	learn: 0.6287750	total: 101ms	remaining: 305ms
32:	learn: 0.6269321	total: 104ms	remaining: 302ms
33:	learn: 0.6250790	total: 107ms	remaining: 299ms
34:	learn: 0.6233915	total: 110ms	remaining: 295ms
35:	learn: 0.6215987	total: 112ms	remaining: 290ms
36:	learn: 0.6196793	total: 115ms	remaining: 287ms
37:	learn: 0.6180587	total: 119ms	remaining: 284ms
38:	learn: 0.6162372	total: 125ms	remaining: 288ms
39:	learn: 0.6144897	total: 128ms	remaining: 284ms
40:	learn: 0.6128721	total: 131ms	remaining: 280ms
41:	learn: 0.6111963	total: 134ms	remaining: 277ms
42:	learn: 0.6095015	total: 137ms	remaining: 274ms
43:	learn: 0.6076790	total: 140ms	remaining: 270ms
44:	learn: 0.6061126	total: 143ms	remaining: 267ms
45:	learn: 0.6044501	total: 146ms	remaining: 263ms
46:	learn: 0.6028550	total: 149ms	remaining: 260ms
47:	learn: 0.6012071	total: 152ms	remaining: 256ms
48:	learn: 0.5995536	total: 155ms	remaining: 253ms
49:	learn: 0.5980343	total: 158ms	remaining: 249ms
50:	learn: 0.5964622	total: 161ms	remaining: 246ms
51:	learn: 0.5948633	total: 164ms	remaining: 242ms
52:	learn: 0.5931611	total: 166ms	remaining: 238ms
53:	learn: 0.5915502	total: 169ms	remaining: 235ms
54:	learn: 0.5899406	total: 172ms	remaining: 232ms
55:	learn: 0.5885125	total: 175ms	remaining: 228ms
56:	learn: 0.5870001	total: 178ms	remaining: 225ms
57:	learn: 0.5853066	total: 181ms	remaining: 222ms
58:	learn: 0.5839901	total: 184ms	remaining: 218ms
59:	learn: 0.5823231	total: 187ms	remaining: 215ms
60:	learn: 0.5807223	total: 190ms	remaining: 212ms
61:	learn: 0.5792006	total: 193ms	remaining: 209ms
62:	learn: 0.5777772	total: 196ms	remaining: 205ms
63:	learn: 0.5762915	total: 200ms	remaining: 203ms
64:	learn: 0.5749143	total: 203ms	remaining: 200ms
65:	learn: 0.5735309	total: 206ms	remaining: 196ms
66:	learn: 0.5721719	total: 209ms	remaining: 193ms
67:	learn: 0.5708659	total: 212ms	remaining: 190ms
68:	learn: 0.5696223	total: 215ms	remaining: 187ms
69:	learn: 0.5680854	total: 218ms	remaining: 184ms
70:	learn: 0.5667058	total: 221ms	remaining: 180ms
71:	learn: 0.5654176	total: 224ms	remaining: 177ms
72:	learn: 0.5640524	total: 227ms	remaining: 174ms
73:	learn: 0.5625782	total: 230ms	remaining: 171ms
74:	learn: 0.5612471	total: 233ms	remaining: 168ms
75:	learn: 0.5599929	total: 236ms	remaining: 164ms
76:	learn: 0.5585763	total: 239ms	remaining: 161ms
77:	learn: 0.5572108	total: 242ms	remaining: 158ms
78:	learn: 0.5557914	total: 245ms	remaining: 155ms
79:	learn: 0.5544308	total: 248ms	remaining: 152ms
80:	learn: 0.5530319	total: 251ms	remaining: 149ms
81:	learn: 0.5516224	total: 254ms	remaining: 145ms
82:	learn: 0.5502654	total: 259ms	remaining: 144ms
83:	learn: 0.5488817	total: 262ms	remaining: 140ms
84:	learn: 0.5475726	total: 265ms	remaining: 137ms
85:	learn: 0.5464641	total: 268ms	remaining: 134ms
86:	learn: 0.5451960	total: 271ms	remaining: 131ms
87:	learn: 0.5438631	total: 274ms	remaining: 128ms
88:	learn: 0.5425678	total: 277ms	remaining: 124ms
89:	learn: 0.5413653	total: 280ms	remaining: 121ms
90:	learn: 0.5401404	total: 283ms	remaining: 118ms
91:	learn: 0.5388941	total: 286ms	remaining: 115ms
92:	learn: 0.5377781	total: 289ms	remaining: 112ms
93:	learn: 0.5364701	total: 292ms	remaining: 109ms
94:	learn: 0.5351584	total: 296ms	remaining: 106ms
95:	learn: 0.5339390	total: 299ms	remaining: 103ms
96:	learn: 0.5326801	total: 302ms	remaining: 99.6ms
97:	learn: 0.5314354	total: 305ms	remaining: 96.5ms
98:	learn: 0.5302237	total: 308ms	remaining: 93.3ms
99:	learn: 0.5290669	total: 311ms	remaining: 90.2ms
100:	learn: 0.5278886	total: 315ms	remaining: 87.3ms
101:	learn: 0.5267167	total: 318ms	remaining: 84.1ms
102:	learn: 0.5257049	total: 321ms	remaining: 81ms
103:	learn: 0.5244360	total: 324ms	remaining: 77.8ms
104:	learn: 0.5232673	total: 327ms	remaining: 74.7ms
105:	learn: 0.5221908	total: 330ms	remaining: 71.5ms
106:	learn: 0.5211953	total: 333ms	remaining: 68.4ms
107:	learn: 0.5200384	total: 336ms	remaining: 65.3ms
108:	learn: 0.5188213	total: 339ms	remaining: 62.1ms
109:	learn: 0.5177896	total: 342ms	remaining: 59ms
110:	learn: 0.5166068	total: 345ms	remaining: 55.9ms
111:	learn: 0.5156348	total: 348ms	remaining: 52.8ms
112:	learn: 0.5145190	total: 351ms	remaining: 49.7ms
113:	learn: 0.5133511	total: 354ms	remaining: 46.5ms
114:	learn: 0.5123514	total: 357ms	remaining: 43.4ms
115:	learn: 0.5112185	total: 360ms	remaining: 40.3ms
116:	learn: 0.5100925	total: 363ms	remaining: 37.2ms
117:	learn: 0.5090026	total: 366ms	remaining: 34.1ms
118:	learn: 0.5079093	total: 369ms	remaining: 31ms
119:	learn: 0.5069047	total: 372ms	remaining: 27.9ms
120:	learn: 0.5057837	total: 375ms	remaining: 24.8ms
121:	learn: 0.5046775	total: 378ms	remaining: 21.7ms
122:	learn: 0.5036367	total: 381ms	remaining: 18.6ms
123:	learn: 0.5025680	total: 384ms	remaining: 15.5ms
124:	learn: 0.5015230	total: 388ms	remaining: 12.4ms
125:	learn: 0.5005708	total: 391ms	remaining: 9.3ms
126:	learn: 0.4994758	total: 394ms	remaining: 6.21ms
127:	learn: 0.4984715	total: 398ms	remaining: 3.11ms
128:	learn: 0.4975533	total: 401ms	remaining: 0us

## Predict

In [12]:
preds_label = {}
for task in ['agnostic', 'aware']:
    preds_label['test-' + task] = models['val-' + task].predict(X['test-' + task])
    print(f'test-{task} - done!')

test-agnostic - done!
test-aware - done!

# CatBoost Regressor
## Find parameters

In [13]:
# Определение функции для оптимизации
def objective(trial):
    params = {
        'iterations': trial.suggest_int('iterations', 50, 400),
        'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.5),
        'depth': trial.suggest_int('depth', 4, 14),
        'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
        'border_count': trial.suggest_int('border_count', 5, 200),
        'verbose': False,
        'random_seed': RANDOM_SEED
    }

    model = cb.CatBoostRegressor(**params)

    # Кросс-валидация
    cv = KFold(n_splits=10, shuffle=True, random_state=RANDOM_SEED)
    mse = - cross_val_score(model, X[df_name], y[df_name]['p'], cv=cv, scoring='neg_mean_squared_error').mean()

    return mse

best_params_dict = {}
if FIND_HYPERPARAMETERS:
    for df_name in ['val-agnostic', 'val-aware']:
        # Создание объекта study и запуск оптимизации
        study = optuna.create_study(direction='minimize')
        study.optimize(objective, n_trials=50)

        # Получение лучших параметров
        best_params_dict[df_name] = study.best_params
else:
    best_params_dict['val-agnostic'] = {'iterations': 394, 'learning_rate': 0.021608465544161754, 'depth': 4, 'l2_leaf_reg': 0.007156537267301533, 'border_count': 98}
    best_params_dict['val-aware'] = {'iterations': 135, 'learning_rate': 0.025526913154005487, 'depth': 4, 'l2_leaf_reg': 0.12536020060626074, 'border_count': 118}

In [14]:
for df_name in ['val-agnostic', 'val-aware']:
    print("Best Params:", df_name.ljust(15), best_params_dict[df_name])

Best Params: val-agnostic    {'iterations': 394, 'learning_rate': 0.021608465544161754, 'depth': 4, 'l2_leaf_reg': 0.007156537267301533, 'border_count': 98}
Best Params: val-aware       {'iterations': 135, 'learning_rate': 0.025526913154005487, 'depth': 4, 'l2_leaf_reg': 0.12536020060626074, 'border_count': 118}

## Evaluate on validation sample

In [15]:
if EVALUATE_ON_VAL:
    cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=RANDOM_SEED)
    mean_corr_dict = {}
    for df_name in ['val-agnostic', 'val-aware']:
        model = cb.CatBoostRegressor(**best_params_dict[df_name])
        correlation = []
        for i, (train_index, test_index) in enumerate(cv.split(X[df_name], y[df_name]['label'])):
            # Train
            X_train = X[df_name].loc[train_index]
            y_train = y[df_name]['p'].loc[train_index]
            model.fit(X_train, y_train)

            # Predict
            X_test = X[df_name].loc[test_index]
            y_test = y[df_name]['p'].loc[test_index]
            y_pred = model.predict(X_test)

            # Postprocessing
            np.clip(y_pred, 0.0, 1.0, out=y_pred)

            # Calc metric
            correlation.append(spearmanr(y_pred, y_test)[0])
            
        # Calc average metric
        mean_corr = statistics.fmean(correlation)
        mean_corr_dict[df_name] = mean_corr

In [16]:
if EVALUATE_ON_VAL:
    for df_name in ['val-agnostic', 'val-aware']:
        print('Correlation:', df_name.ljust(15), mean_corr_dict[df_name])

## Train on 100 % of data

In [17]:
models = {}
for df_name in ['val-agnostic', 'val-aware']:
    # Обучение модели с лучшими параметрами
    model = cb.CatBoostRegressor(**best_params_dict[df_name])
    model.fit(X[df_name], y[df_name]['p'])
    models[df_name] = model

0:	learn: 0.3473506	total: 1.43ms	remaining: 563ms
1:	learn: 0.3436064	total: 2.12ms	remaining: 415ms
2:	learn: 0.3397502	total: 2.54ms	remaining: 332ms
3:	learn: 0.3359814	total: 2.99ms	remaining: 291ms
4:	learn: 0.3321958	total: 3.39ms	remaining: 264ms
5:	learn: 0.3291622	total: 3.79ms	remaining: 245ms
6:	learn: 0.3255975	total: 4.19ms	remaining: 232ms
7:	learn: 0.3223050	total: 4.59ms	remaining: 221ms
8:	learn: 0.3190166	total: 5ms	remaining: 214ms
9:	learn: 0.3162097	total: 5.42ms	remaining: 208ms
10:	learn: 0.3131227	total: 5.81ms	remaining: 202ms
11:	learn: 0.3104455	total: 6.2ms	remaining: 197ms
12:	learn: 0.3073290	total: 6.6ms	remaining: 193ms
13:	learn: 0.3047466	total: 7ms	remaining: 190ms
14:	learn: 0.3021319	total: 7.39ms	remaining: 187ms
15:	learn: 0.2993682	total: 7.77ms	remaining: 184ms
16:	learn: 0.2967632	total: 8.18ms	remaining: 181ms
17:	learn: 0.2941623	total: 8.58ms	remaining: 179ms
18:	learn: 0.2918140	total: 8.98ms	remaining: 177ms
19:	learn: 0.2894188	total: 9.37ms	remaining: 175ms
20:	learn: 0.2872544	total: 9.75ms	remaining: 173ms
21:	learn: 0.2849769	total: 10.1ms	remaining: 171ms
22:	learn: 0.2828384	total: 10.5ms	remaining: 170ms
23:	learn: 0.2809890	total: 10.9ms	remaining: 168ms
24:	learn: 0.2788016	total: 11.3ms	remaining: 167ms
25:	learn: 0.2770725	total: 11.7ms	remaining: 166ms
26:	learn: 0.2751828	total: 12.1ms	remaining: 165ms
27:	learn: 0.2731813	total: 12.5ms	remaining: 164ms
28:	learn: 0.2713058	total: 12.9ms	remaining: 163ms
29:	learn: 0.2695379	total: 13.3ms	remaining: 161ms
30:	learn: 0.2678052	total: 13.7ms	remaining: 161ms
31:	learn: 0.2661728	total: 14.1ms	remaining: 160ms
32:	learn: 0.2644847	total: 14.6ms	remaining: 159ms
33:	learn: 0.2629538	total: 15ms	remaining: 158ms
34:	learn: 0.2612611	total: 15.3ms	remaining: 157ms
35:	learn: 0.2601771	total: 15.7ms	remaining: 156ms
36:	learn: 0.2590586	total: 16.1ms	remaining: 156ms
37:	learn: 0.2577183	total: 16.5ms	remaining: 155ms
38:	learn: 0.2564682	total: 16.9ms	remaining: 154ms
39:	learn: 0.2551096	total: 17.3ms	remaining: 153ms
40:	learn: 0.2537662	total: 17.7ms	remaining: 152ms
41:	learn: 0.2523233	total: 18.1ms	remaining: 151ms
42:	learn: 0.2511290	total: 18.5ms	remaining: 151ms
43:	learn: 0.2498316	total: 18.9ms	remaining: 150ms
44:	learn: 0.2484823	total: 19.2ms	remaining: 149ms
45:	learn: 0.2473248	total: 19.6ms	remaining: 149ms
46:	learn: 0.2462167	total: 20ms	remaining: 148ms
47:	learn: 0.2449073	total: 20.4ms	remaining: 147ms
48:	learn: 0.2438895	total: 20.8ms	remaining: 146ms
49:	learn: 0.2430292	total: 21.2ms	remaining: 146ms
50:	learn: 0.2421271	total: 21.5ms	remaining: 145ms
51:	learn: 0.2410569	total: 21.9ms	remaining: 144ms
52:	learn: 0.2401767	total: 22.3ms	remaining: 144ms
53:	learn: 0.2393634	total: 22.7ms	remaining: 143ms
54:	learn: 0.2383281	total: 23.1ms	remaining: 143ms
55:	learn: 0.2374738	total: 23.5ms	remaining: 142ms
56:	learn: 0.2365952	total: 23.9ms	remaining: 141ms
57:	learn: 0.2358891	total: 24.3ms	remaining: 141ms
58:	learn: 0.2348515	total: 24.7ms	remaining: 140ms
59:	learn: 0.2341258	total: 25.1ms	remaining: 140ms
60:	learn: 0.2334459	total: 25.5ms	remaining: 139ms
61:	learn: 0.2326780	total: 25.9ms	remaining: 139ms
62:	learn: 0.2320062	total: 26.3ms	remaining: 138ms
63:	learn: 0.2312565	total: 26.7ms	remaining: 138ms
64:	learn: 0.2304962	total: 27.3ms	remaining: 138ms
65:	learn: 0.2297401	total: 27.7ms	remaining: 138ms
66:	learn: 0.2290608	total: 28.1ms	remaining: 137ms
67:	learn: 0.2285849	total: 28.6ms	remaining: 137ms
68:	learn: 0.2278618	total: 29ms	remaining: 137ms
69:	learn: 0.2272086	total: 29.4ms	remaining: 136ms
70:	learn: 0.2265377	total: 29.8ms	remaining: 136ms
71:	learn: 0.2260659	total: 30.2ms	remaining: 135ms
72:	learn: 0.2256842	total: 30.7ms	remaining: 135ms
73:	learn: 0.2248902	total: 31.1ms	remaining: 134ms
74:	learn: 0.2242861	total: 31.5ms	remaining: 134ms
75:	learn: 0.2237567	total: 31.9ms	remaining: 133ms
76:	learn: 0.2232692	total: 32.3ms	remaining: 133ms
77:	learn: 0.2226665	total: 32.7ms	remaining: 132ms
78:	learn: 0.2222506	total: 33.1ms	remaining: 132ms
79:	learn: 0.2218183	total: 33.4ms	remaining: 131ms
80:	learn: 0.2212104	total: 33.9ms	remaining: 131ms
81:	learn: 0.2207818	total: 34.3ms	remaining: 130ms
82:	learn: 0.2204342	total: 34.6ms	remaining: 130ms
83:	learn: 0.2199459	total: 35ms	remaining: 129ms
84:	learn: 0.2194575	total: 35.4ms	remaining: 129ms
85:	learn: 0.2190020	total: 35.8ms	remaining: 128ms
86:	learn: 0.2187156	total: 36.1ms	remaining: 128ms
87:	learn: 0.2182421	total: 36.5ms	remaining: 127ms
88:	learn: 0.2179812	total: 37ms	remaining: 127ms
89:	learn: 0.2176287	total: 37.4ms	remaining: 126ms
90:	learn: 0.2171614	total: 37.9ms	remaining: 126ms
91:	learn: 0.2167851	total: 38.3ms	remaining: 126ms
92:	learn: 0.2163715	total: 38.7ms	remaining: 125ms
93:	learn: 0.2158384	total: 39.1ms	remaining: 125ms
94:	learn: 0.2155964	total: 39.5ms	remaining: 124ms
95:	learn: 0.2151722	total: 39.9ms	remaining: 124ms
96:	learn: 0.2147906	total: 40.3ms	remaining: 123ms
97:	learn: 0.2143080	total: 40.7ms	remaining: 123ms
98:	learn: 0.2140383	total: 41ms	remaining: 122ms
99:	learn: 0.2136646	total: 41.5ms	remaining: 122ms
100:	learn: 0.2134184	total: 41.8ms	remaining: 121ms
101:	learn: 0.2131039	total: 42.2ms	remaining: 121ms
102:	learn: 0.2128701	total: 42.6ms	remaining: 120ms
103:	learn: 0.2126143	total: 43ms	remaining: 120ms
104:	learn: 0.2122875	total: 43.4ms	remaining: 120ms
105:	learn: 0.2120213	total: 43.8ms	remaining: 119ms
106:	learn: 0.2117571	total: 44.2ms	remaining: 119ms
107:	learn: 0.2115038	total: 44.6ms	remaining: 118ms
108:	learn: 0.2112768	total: 45ms	remaining: 118ms
109:	learn: 0.2109754	total: 45.4ms	remaining: 117ms
110:	learn: 0.2107296	total: 45.8ms	remaining: 117ms
111:	learn: 0.2104609	total: 46.2ms	remaining: 116ms
112:	learn: 0.2102649	total: 46.6ms	remaining: 116ms
113:	learn: 0.2100120	total: 46.9ms	remaining: 115ms
114:	learn: 0.2097565	total: 47.3ms	remaining: 115ms
115:	learn: 0.2093337	total: 47.7ms	remaining: 114ms
116:	learn: 0.2091052	total: 48.1ms	remaining: 114ms
117:	learn: 0.2089700	total: 48.5ms	remaining: 113ms
118:	learn: 0.2088118	total: 48.9ms	remaining: 113ms
119:	learn: 0.2085726	total: 49.3ms	remaining: 113ms
120:	learn: 0.2083463	total: 49.7ms	remaining: 112ms
121:	learn: 0.2081248	total: 50.1ms	remaining: 112ms
122:	learn: 0.2077793	total: 50.5ms	remaining: 111ms
123:	learn: 0.2075911	total: 50.9ms	remaining: 111ms
124:	learn: 0.2074262	total: 51.3ms	remaining: 110ms
125:	learn: 0.2071893	total: 51.6ms	remaining: 110ms
126:	learn: 0.2068792	total: 52ms	remaining: 109ms
127:	learn: 0.2066906	total: 52.4ms	remaining: 109ms
128:	learn: 0.2064235	total: 52.8ms	remaining: 109ms
129:	learn: 0.2061251	total: 53.2ms	remaining: 108ms
130:	learn: 0.2059571	total: 53.6ms	remaining: 108ms
131:	learn: 0.2057187	total: 54ms	remaining: 107ms
132:	learn: 0.2054424	total: 54.4ms	remaining: 107ms
133:	learn: 0.2052962	total: 54.8ms	remaining: 106ms
134:	learn: 0.2051222	total: 55.1ms	remaining: 106ms
135:	learn: 0.2049410	total: 55.5ms	remaining: 105ms
136:	learn: 0.2046220	total: 55.9ms	remaining: 105ms
137:	learn: 0.2044518	total: 56.3ms	remaining: 104ms
138:	learn: 0.2043142	total: 56.7ms	remaining: 104ms
139:	learn: 0.2041150	total: 57.1ms	remaining: 104ms
140:	learn: 0.2040231	total: 57.5ms	remaining: 103ms
141:	learn: 0.2038675	total: 57.9ms	remaining: 103ms
142:	learn: 0.2037038	total: 58.3ms	remaining: 102ms
143:	learn: 0.2035105	total: 58.7ms	remaining: 102ms
144:	learn: 0.2033517	total: 59.1ms	remaining: 101ms
145:	learn: 0.2032279	total: 59.5ms	remaining: 101ms
146:	learn: 0.2030226	total: 60.2ms	remaining: 101ms
147:	learn: 0.2028699	total: 60.6ms	remaining: 101ms
148:	learn: 0.2026923	total: 61ms	remaining: 100ms
149:	learn: 0.2023369	total: 61.4ms	remaining: 99.9ms
150:	learn: 0.2021269	total: 61.8ms	remaining: 99.4ms
151:	learn: 0.2018465	total: 62.2ms	remaining: 99ms
152:	learn: 0.2017376	total: 62.6ms	remaining: 98.6ms
153:	learn: 0.2016158	total: 63ms	remaining: 98.1ms
154:	learn: 0.2015035	total: 63.4ms	remaining: 97.8ms
155:	learn: 0.2014049	total: 63.8ms	remaining: 97.4ms
156:	learn: 0.2011766	total: 64.3ms	remaining: 97ms
157:	learn: 0.2010288	total: 64.7ms	remaining: 96.6ms
158:	learn: 0.2008313	total: 65.1ms	remaining: 96.2ms
159:	learn: 0.2007113	total: 65.5ms	remaining: 95.8ms
160:	learn: 0.2005370	total: 65.9ms	remaining: 95.4ms
161:	learn: 0.2003400	total: 66.3ms	remaining: 95ms
162:	learn: 0.2001802	total: 66.7ms	remaining: 94.6ms
163:	learn: 0.2000809	total: 67.2ms	remaining: 94.3ms
164:	learn: 0.1998066	total: 67.6ms	remaining: 93.8ms
165:	learn: 0.1996132	total: 68.1ms	remaining: 93.5ms
166:	learn: 0.1995018	total: 68.5ms	remaining: 93.1ms
167:	learn: 0.1992495	total: 68.9ms	remaining: 92.7ms
168:	learn: 0.1990882	total: 69.3ms	remaining: 92.3ms
169:	learn: 0.1989162	total: 69.7ms	remaining: 91.9ms
170:	learn: 0.1987901	total: 70.1ms	remaining: 91.5ms
171:	learn: 0.1985502	total: 70.5ms	remaining: 91.1ms
172:	learn: 0.1984428	total: 71ms	remaining: 90.6ms
173:	learn: 0.1983549	total: 71.4ms	remaining: 90.2ms
174:	learn: 0.1982324	total: 71.8ms	remaining: 89.8ms
175:	learn: 0.1980279	total: 72.2ms	remaining: 89.4ms
176:	learn: 0.1979088	total: 72.6ms	remaining: 89ms
177:	learn: 0.1977061	total: 73ms	remaining: 88.6ms
178:	learn: 0.1975159	total: 73.5ms	remaining: 88.2ms
179:	learn: 0.1973982	total: 73.9ms	remaining: 87.8ms
180:	learn: 0.1971961	total: 74.3ms	remaining: 87.4ms
181:	learn: 0.1970562	total: 74.7ms	remaining: 87ms
182:	learn: 0.1968142	total: 75.1ms	remaining: 86.6ms
183:	learn: 0.1966695	total: 75.5ms	remaining: 86.2ms
184:	learn: 0.1964780	total: 76ms	remaining: 85.8ms
185:	learn: 0.1963755	total: 76.4ms	remaining: 85.4ms
186:	learn: 0.1962015	total: 76.8ms	remaining: 85ms
187:	learn: 0.1960868	total: 77.2ms	remaining: 84.6ms
188:	learn: 0.1959766	total: 77.6ms	remaining: 84.2ms
189:	learn: 0.1958431	total: 78ms	remaining: 83.7ms
190:	learn: 0.1957842	total: 78.4ms	remaining: 83.3ms
191:	learn: 0.1955706	total: 78.8ms	remaining: 82.9ms
192:	learn: 0.1954145	total: 79.2ms	remaining: 82.5ms
193:	learn: 0.1952694	total: 79.7ms	remaining: 82.2ms
194:	learn: 0.1952052	total: 80.3ms	remaining: 81.9ms
195:	learn: 0.1949555	total: 80.8ms	remaining: 81.6ms
196:	learn: 0.1949096	total: 81.2ms	remaining: 81.2ms
197:	learn: 0.1947717	total: 81.6ms	remaining: 80.8ms
198:	learn: 0.1945995	total: 82.8ms	remaining: 81.1ms
199:	learn: 0.1944932	total: 83.3ms	remaining: 80.8ms
200:	learn: 0.1943810	total: 83.7ms	remaining: 80.3ms
201:	learn: 0.1942127	total: 84.1ms	remaining: 79.9ms
202:	learn: 0.1940565	total: 84.5ms	remaining: 79.5ms
203:	learn: 0.1939418	total: 84.8ms	remaining: 79ms
204:	learn: 0.1938244	total: 85.3ms	remaining: 78.6ms
205:	learn: 0.1937422	total: 85.7ms	remaining: 78.2ms
206:	learn: 0.1935846	total: 86.1ms	remaining: 77.7ms
207:	learn: 0.1933169	total: 86.5ms	remaining: 77.3ms
208:	learn: 0.1931781	total: 86.9ms	remaining: 76.9ms
209:	learn: 0.1931088	total: 87.3ms	remaining: 76.5ms
210:	learn: 0.1929740	total: 87.7ms	remaining: 76ms
211:	learn: 0.1927757	total: 88.1ms	remaining: 75.6ms
212:	learn: 0.1927150	total: 88.5ms	remaining: 75.2ms
213:	learn: 0.1925347	total: 88.9ms	remaining: 74.8ms
214:	learn: 0.1924199	total: 89.2ms	remaining: 74.3ms
215:	learn: 0.1922969	total: 89.7ms	remaining: 73.9ms
216:	learn: 0.1921894	total: 90.1ms	remaining: 73.5ms
217:	learn: 0.1921037	total: 90.5ms	remaining: 73.1ms
218:	learn: 0.1919035	total: 90.9ms	remaining: 72.7ms
219:	learn: 0.1917322	total: 91.3ms	remaining: 72.2ms
220:	learn: 0.1914945	total: 91.7ms	remaining: 71.8ms
221:	learn: 0.1913535	total: 92.1ms	remaining: 71.4ms
222:	learn: 0.1911919	total: 92.5ms	remaining: 70.9ms
223:	learn: 0.1911046	total: 92.9ms	remaining: 70.5ms
224:	learn: 0.1909072	total: 93.3ms	remaining: 70.1ms
225:	learn: 0.1908028	total: 93.8ms	remaining: 69.7ms
226:	learn: 0.1907195	total: 94.2ms	remaining: 69.3ms
227:	learn: 0.1906191	total: 94.6ms	remaining: 68.9ms
228:	learn: 0.1904389	total: 95ms	remaining: 68.4ms
229:	learn: 0.1901844	total: 95.4ms	remaining: 68ms
230:	learn: 0.1900374	total: 95.7ms	remaining: 67.6ms
231:	learn: 0.1899204	total: 96.1ms	remaining: 67.1ms
232:	learn: 0.1898347	total: 96.5ms	remaining: 66.7ms
233:	learn: 0.1896740	total: 97.2ms	remaining: 66.4ms
234:	learn: 0.1895283	total: 97.7ms	remaining: 66.1ms
235:	learn: 0.1894466	total: 98.1ms	remaining: 65.7ms
236:	learn: 0.1892877	total: 98.5ms	remaining: 65.2ms
237:	learn: 0.1891495	total: 99.1ms	remaining: 65ms
238:	learn: 0.1889887	total: 99.5ms	remaining: 64.5ms
239:	learn: 0.1888808	total: 99.9ms	remaining: 64.1ms
240:	learn: 0.1886942	total: 101ms	remaining: 64.2ms
241:	learn: 0.1885369	total: 102ms	remaining: 63.8ms
242:	learn: 0.1883891	total: 102ms	remaining: 63.3ms
243:	learn: 0.1882697	total: 102ms	remaining: 62.9ms
244:	learn: 0.1880577	total: 104ms	remaining: 63.1ms
245:	learn: 0.1878333	total: 104ms	remaining: 62.6ms
246:	learn: 0.1877518	total: 104ms	remaining: 62.2ms
247:	learn: 0.1876330	total: 105ms	remaining: 61.7ms
248:	learn: 0.1874153	total: 105ms	remaining: 61.3ms
249:	learn: 0.1872313	total: 106ms	remaining: 60.9ms
250:	learn: 0.1870921	total: 106ms	remaining: 60.4ms
251:	learn: 0.1869174	total: 106ms	remaining: 60ms
252:	learn: 0.1867195	total: 109ms	remaining: 60.6ms
253:	learn: 0.1864978	total: 109ms	remaining: 60.2ms
254:	learn: 0.1864403	total: 110ms	remaining: 59.8ms
255:	learn: 0.1862672	total: 111ms	remaining: 59.8ms
256:	learn: 0.1862143	total: 111ms	remaining: 59.4ms
257:	learn: 0.1860960	total: 112ms	remaining: 59ms
258:	learn: 0.1859527	total: 113ms	remaining: 58.7ms
259:	learn: 0.1858782	total: 113ms	remaining: 58.3ms
260:	learn: 0.1858096	total: 114ms	remaining: 57.8ms
261:	learn: 0.1856446	total: 114ms	remaining: 57.4ms
262:	learn: 0.1854889	total: 114ms	remaining: 56.9ms
263:	learn: 0.1852910	total: 115ms	remaining: 56.5ms
264:	learn: 0.1851540	total: 116ms	remaining: 56.6ms
265:	learn: 0.1849994	total: 117ms	remaining: 56.2ms
266:	learn: 0.1848381	total: 117ms	remaining: 55.9ms
267:	learn: 0.1847102	total: 118ms	remaining: 55.4ms
268:	learn: 0.1846504	total: 118ms	remaining: 55ms
269:	learn: 0.1845395	total: 119ms	remaining: 54.5ms
270:	learn: 0.1843904	total: 120ms	remaining: 54.3ms
271:	learn: 0.1841336	total: 120ms	remaining: 53.9ms
272:	learn: 0.1839326	total: 121ms	remaining: 53.5ms
273:	learn: 0.1837054	total: 121ms	remaining: 53.1ms
274:	learn: 0.1835445	total: 122ms	remaining: 52.6ms
275:	learn: 0.1834753	total: 122ms	remaining: 52.2ms
276:	learn: 0.1832395	total: 122ms	remaining: 51.7ms
277:	learn: 0.1830846	total: 123ms	remaining: 51.2ms
278:	learn: 0.1829729	total: 123ms	remaining: 50.8ms
279:	learn: 0.1828130	total: 124ms	remaining: 50.3ms
280:	learn: 0.1826865	total: 124ms	remaining: 49.9ms
281:	learn: 0.1824296	total: 124ms	remaining: 49.4ms
282:	learn: 0.1822350	total: 125ms	remaining: 48.9ms
283:	learn: 0.1820762	total: 125ms	remaining: 48.5ms
284:	learn: 0.1819266	total: 126ms	remaining: 48ms
285:	learn: 0.1817717	total: 126ms	remaining: 47.6ms
286:	learn: 0.1816055	total: 127ms	remaining: 47.5ms
287:	learn: 0.1814267	total: 128ms	remaining: 47ms
288:	learn: 0.1813279	total: 128ms	remaining: 46.6ms
289:	learn: 0.1811695	total: 129ms	remaining: 46.1ms
290:	learn: 0.1809692	total: 129ms	remaining: 45.7ms
291:	learn: 0.1808539	total: 129ms	remaining: 45.2ms
292:	learn: 0.1806563	total: 130ms	remaining: 44.8ms
293:	learn: 0.1805114	total: 130ms	remaining: 44.3ms
294:	learn: 0.1803170	total: 131ms	remaining: 43.9ms
295:	learn: 0.1800745	total: 131ms	remaining: 43.4ms
296:	learn: 0.1800244	total: 132ms	remaining: 43ms
297:	learn: 0.1798453	total: 132ms	remaining: 42.5ms
298:	learn: 0.1796472	total: 132ms	remaining: 42.1ms
299:	learn: 0.1795040	total: 133ms	remaining: 41.8ms
300:	learn: 0.1793768	total: 134ms	remaining: 41.3ms
301:	learn: 0.1792419	total: 134ms	remaining: 40.9ms
302:	learn: 0.1791217	total: 135ms	remaining: 40.4ms
303:	learn: 0.1788966	total: 135ms	remaining: 40ms
304:	learn: 0.1787958	total: 135ms	remaining: 39.5ms
305:	learn: 0.1787004	total: 136ms	remaining: 39ms
306:	learn: 0.1785462	total: 136ms	remaining: 38.6ms
307:	learn: 0.1783357	total: 137ms	remaining: 38.1ms
308:	learn: 0.1782006	total: 137ms	remaining: 37.7ms
309:	learn: 0.1780717	total: 137ms	remaining: 37.2ms
310:	learn: 0.1779111	total: 138ms	remaining: 36.8ms
311:	learn: 0.1777453	total: 138ms	remaining: 36.3ms
312:	learn: 0.1776520	total: 138ms	remaining: 35.8ms
313:	learn: 0.1774723	total: 139ms	remaining: 35.4ms
314:	learn: 0.1773549	total: 139ms	remaining: 34.9ms
315:	learn: 0.1772370	total: 140ms	remaining: 34.5ms
316:	learn: 0.1771469	total: 140ms	remaining: 34ms
317:	learn: 0.1769426	total: 141ms	remaining: 33.7ms
318:	learn: 0.1767542	total: 141ms	remaining: 33.2ms
319:	learn: 0.1765928	total: 142ms	remaining: 32.8ms
320:	learn: 0.1764248	total: 142ms	remaining: 32.3ms
321:	learn: 0.1762830	total: 142ms	remaining: 31.8ms
322:	learn: 0.1761403	total: 143ms	remaining: 31.4ms
323:	learn: 0.1759746	total: 143ms	remaining: 30.9ms
324:	learn: 0.1758293	total: 144ms	remaining: 30.5ms
325:	learn: 0.1756964	total: 144ms	remaining: 30ms
326:	learn: 0.1755864	total: 144ms	remaining: 29.6ms
327:	learn: 0.1754308	total: 145ms	remaining: 29.2ms
328:	learn: 0.1752762	total: 145ms	remaining: 28.7ms
329:	learn: 0.1751648	total: 146ms	remaining: 28.3ms
330:	learn: 0.1749992	total: 146ms	remaining: 27.8ms
331:	learn: 0.1749055	total: 146ms	remaining: 27.3ms
332:	learn: 0.1747621	total: 147ms	remaining: 26.9ms
333:	learn: 0.1746331	total: 147ms	remaining: 26.4ms
334:	learn: 0.1745186	total: 148ms	remaining: 26ms
335:	learn: 0.1743290	total: 148ms	remaining: 25.6ms
336:	learn: 0.1740591	total: 149ms	remaining: 25.1ms
337:	learn: 0.1739262	total: 149ms	remaining: 24.7ms
338:	learn: 0.1737777	total: 149ms	remaining: 24.2ms
339:	learn: 0.1736612	total: 150ms	remaining: 23.8ms
340:	learn: 0.1735470	total: 150ms	remaining: 23.4ms
341:	learn: 0.1733836	total: 151ms	remaining: 22.9ms
342:	learn: 0.1732480	total: 151ms	remaining: 22.5ms
343:	learn: 0.1730768	total: 152ms	remaining: 22ms
344:	learn: 0.1728880	total: 152ms	remaining: 21.6ms
345:	learn: 0.1727721	total: 153ms	remaining: 21.2ms
346:	learn: 0.1725910	total: 153ms	remaining: 20.7ms
347:	learn: 0.1724776	total: 154ms	remaining: 20.3ms
348:	learn: 0.1722707	total: 154ms	remaining: 19.9ms
349:	learn: 0.1721629	total: 155ms	remaining: 19.5ms
350:	learn: 0.1720246	total: 155ms	remaining: 19ms
351:	learn: 0.1719407	total: 156ms	remaining: 18.6ms
352:	learn: 0.1718498	total: 156ms	remaining: 18.1ms
353:	learn: 0.1717092	total: 157ms	remaining: 17.7ms
354:	learn: 0.1715406	total: 157ms	remaining: 17.2ms
355:	learn: 0.1714101	total: 157ms	remaining: 16.8ms
356:	learn: 0.1712052	total: 158ms	remaining: 16.4ms
357:	learn: 0.1710936	total: 158ms	remaining: 15.9ms
358:	learn: 0.1709984	total: 159ms	remaining: 15.5ms
359:	learn: 0.1708994	total: 159ms	remaining: 15ms
360:	learn: 0.1707951	total: 160ms	remaining: 14.6ms
361:	learn: 0.1706561	total: 161ms	remaining: 14.3ms
362:	learn: 0.1704911	total: 162ms	remaining: 13.8ms
363:	learn: 0.1702098	total: 162ms	remaining: 13.4ms
364:	learn: 0.1700587	total: 163ms	remaining: 12.9ms
365:	learn: 0.1699311	total: 163ms	remaining: 12.5ms
366:	learn: 0.1697810	total: 163ms	remaining: 12ms
367:	learn: 0.1696537	total: 164ms	remaining: 11.6ms
368:	learn: 0.1695238	total: 164ms	remaining: 11.1ms
369:	learn: 0.1694092	total: 165ms	remaining: 10.7ms
370:	learn: 0.1692852	total: 165ms	remaining: 10.2ms
371:	learn: 0.1691303	total: 165ms	remaining: 9.79ms
372:	learn: 0.1689833	total: 166ms	remaining: 9.34ms
373:	learn: 0.1689040	total: 166ms	remaining: 8.89ms
374:	learn: 0.1686333	total: 167ms	remaining: 8.45ms
375:	learn: 0.1685353	total: 169ms	remaining: 8.11ms
376:	learn: 0.1683568	total: 170ms	remaining: 7.66ms
377:	learn: 0.1682332	total: 171ms	remaining: 7.23ms
378:	learn: 0.1680429	total: 171ms	remaining: 6.77ms

382:	learn: 0.1676609	total: 174ms	remaining: 5ms
383:	learn: 0.1675613	total: 174ms	remaining: 4.54ms
384:	learn: 0.1674575	total: 175ms	remaining: 4.09ms
385:	learn: 0.1673602	total: 175ms	remaining: 3.63ms
386:	learn: 0.1671219	total: 176ms	remaining: 3.18ms
387:	learn: 0.1668736	total: 176ms	remaining: 2.72ms
388:	learn: 0.1667525	total: 176ms	remaining: 2.27ms
389:	learn: 0.1666359	total: 177ms	remaining: 1.81ms
390:	learn: 0.1665312	total: 178ms	remaining: 1.37ms
391:	learn: 0.1664504	total: 178ms	remaining: 910us
392:	learn: 0.1663113	total: 179ms	remaining: 455us
393:	learn: 0.1660740	total: 179ms	remaining: 0us
0:	learn: 0.3325298	total: 1.41ms	remaining: 189ms
1:	learn: 0.3287507	total: 1.99ms	remaining: 132ms
2:	learn: 0.3250584	total: 2.53ms	remaining: 111ms
3:	learn: 0.3212615	total: 2.98ms	remaining: 97.6ms
4:	learn: 0.3172326	total: 3.39ms	remaining: 88.2ms
5:	learn: 0.3139371	total: 3.8ms	remaining: 81.7ms
6:	learn: 0.3104941	total: 4.21ms	remaining: 77ms
7:	learn: 0.3075340	total: 4.63ms	remaining: 73.4ms
8:	learn: 0.3042169	total: 5.02ms	remaining: 70.3ms
9:	learn: 0.3010596	total: 5.43ms	remaining: 67.9ms
10:	learn: 0.2979902	total: 5.88ms	remaining: 66.3ms
11:	learn: 0.2950507	total: 6.29ms	remaining: 64.5ms
12:	learn: 0.2923958	total: 6.73ms	remaining: 63.1ms
13:	learn: 0.2896651	total: 7.16ms	remaining: 61.9ms
14:	learn: 0.2872037	total: 7.59ms	remaining: 60.7ms
15:	learn: 0.2847694	total: 8.01ms	remaining: 59.6ms
16:	learn: 0.2822672	total: 8.43ms	remaining: 58.5ms
17:	learn: 0.2800729	total: 8.84ms	remaining: 57.4ms
18:	learn: 0.2778780	total: 9.25ms	remaining: 56.5ms
19:	learn: 0.2756030	total: 9.67ms	remaining: 55.6ms
20:	learn: 0.2732164	total: 10.1ms	remaining: 54.9ms
21:	learn: 0.2708973	total: 10.5ms	remaining: 54.1ms
22:	learn: 0.2688940	total: 11ms	remaining: 53.4ms
23:	learn: 0.2667137	total: 11.4ms	remaining: 52.6ms
24:	learn: 0.2650016	total: 11.8ms	remaining: 52ms
25:	learn: 0.2633815	total: 12.3ms	remaining: 51.7ms
26:	learn: 0.2615432	total: 12.7ms	remaining: 51ms
27:	learn: 0.2599411	total: 13.1ms	remaining: 50.2ms
28:	learn: 0.2583277	total: 13.7ms	remaining: 50ms
29:	learn: 0.2567865	total: 14.1ms	remaining: 49.3ms
30:	learn: 0.2553017	total: 14.5ms	remaining: 48.7ms
31:	learn: 0.2538618	total: 14.9ms	remaining: 48.1ms
32:	learn: 0.2523284	total: 15.4ms	remaining: 47.5ms
33:	learn: 0.2510727	total: 15.8ms	remaining: 46.9ms
34:	learn: 0.2495141	total: 16.2ms	remaining: 46.3ms
35:	learn: 0.2480519	total: 16.6ms	remaining: 45.7ms
36:	learn: 0.2469608	total: 17.1ms	remaining: 45.2ms
37:	learn: 0.2456490	total: 17.5ms	remaining: 44.6ms
38:	learn: 0.2442495	total: 17.9ms	remaining: 44.1ms
39:	learn: 0.2430513	total: 18.4ms	remaining: 43.6ms
40:	learn: 0.2417214	total: 18.8ms	remaining: 43.1ms
41:	learn: 0.2404591	total: 19.3ms	remaining: 42.6ms
42:	learn: 0.2394558	total: 19.7ms	remaining: 42.1ms
43:	learn: 0.2383487	total: 20.1ms	remaining: 41.6ms
44:	learn: 0.2374195	total: 20.5ms	remaining: 41.1ms
45:	learn: 0.2363673	total: 21ms	remaining: 40.6ms
46:	learn: 0.2354341	total: 21.4ms	remaining: 40ms
47:	learn: 0.2345414	total: 21.8ms	remaining: 39.6ms
48:	learn: 0.2334777	total: 22.3ms	remaining: 39.1ms
49:	learn: 0.2326042	total: 22.7ms	remaining: 38.6ms
50:	learn: 0.2317268	total: 23.1ms	remaining: 38.1ms
51:	learn: 0.2310246	total: 23.6ms	remaining: 37.6ms
52:	learn: 0.2302970	total: 25.2ms	remaining: 39ms
53:	learn: 0.2294859	total: 25.7ms	remaining: 38.5ms
54:	learn: 0.2287965	total: 26.1ms	remaining: 38ms
55:	learn: 0.2280722	total: 26.5ms	remaining: 37.4ms
56:	learn: 0.2273906	total: 27ms	remaining: 36.9ms
57:	learn: 0.2269322	total: 27.4ms	remaining: 36.4ms
58:	learn: 0.2260967	total: 29.8ms	remaining: 38.4ms
59:	learn: 0.2254676	total: 30.3ms	remaining: 37.9ms
60:	learn: 0.2249113	total: 30.8ms	remaining: 37.3ms
61:	learn: 0.2243485	total: 31.2ms	remaining: 36.8ms
62:	learn: 0.2238415	total: 31.7ms	remaining: 36.2ms
63:	learn: 0.2233385	total: 32.1ms	remaining: 35.7ms
64:	learn: 0.2229621	total: 32.6ms	remaining: 35.1ms
65:	learn: 0.2225046	total: 33.1ms	remaining: 34.6ms
66:	learn: 0.2219986	total: 33.5ms	remaining: 34ms
67:	learn: 0.2214589	total: 34ms	remaining: 33.5ms
68:	learn: 0.2209574	total: 34.5ms	remaining: 33ms
69:	learn: 0.2203892	total: 34.9ms	remaining: 32.4ms
70:	learn: 0.2199294	total: 35.4ms	remaining: 31.9ms
71:	learn: 0.2194395	total: 35.8ms	remaining: 31.3ms
72:	learn: 0.2190707	total: 36.3ms	remaining: 30.8ms
73:	learn: 0.2186920	total: 36.7ms	remaining: 30.3ms
74:	learn: 0.2182801	total: 37.2ms	remaining: 29.7ms
75:	learn: 0.2177869	total: 37.6ms	remaining: 29.2ms
76:	learn: 0.2172274	total: 38.7ms	remaining: 29.1ms
77:	learn: 0.2168040	total: 39.1ms	remaining: 28.6ms
78:	learn: 0.2165369	total: 39.7ms	remaining: 28.1ms
79:	learn: 0.2162252	total: 40.1ms	remaining: 27.6ms
80:	learn: 0.2157170	total: 40.5ms	remaining: 27ms
81:	learn: 0.2152987	total: 40.9ms	remaining: 26.4ms
82:	learn: 0.2149058	total: 41.3ms	remaining: 25.9ms
83:	learn: 0.2144482	total: 41.7ms	remaining: 25.3ms
84:	learn: 0.2140869	total: 42.1ms	remaining: 24.7ms
85:	learn: 0.2136216	total: 42.5ms	remaining: 24.2ms
86:	learn: 0.2133117	total: 42.9ms	remaining: 23.7ms
87:	learn: 0.2130246	total: 43.3ms	remaining: 23.1ms
88:	learn: 0.2126292	total: 43.7ms	remaining: 22.6ms
89:	learn: 0.2123481	total: 44.1ms	remaining: 22ms
90:	learn: 0.2118870	total: 44.5ms	remaining: 21.5ms
91:	learn: 0.2116485	total: 44.9ms	remaining: 21ms
92:	learn: 0.2112696	total: 45.3ms	remaining: 20.5ms
93:	learn: 0.2109988	total: 45.7ms	remaining: 19.9ms
94:	learn: 0.2107099	total: 46.1ms	remaining: 19.4ms
95:	learn: 0.2102567	total: 46.5ms	remaining: 18.9ms
96:	learn: 0.2100664	total: 47ms	remaining: 18.4ms
97:	learn: 0.2098009	total: 47.4ms	remaining: 17.9ms
98:	learn: 0.2095010	total: 47.8ms	remaining: 17.4ms
99:	learn: 0.2092991	total: 48.2ms	remaining: 16.9ms
100:	learn: 0.2089232	total: 48.6ms	remaining: 16.4ms
101:	learn: 0.2086966	total: 49.3ms	remaining: 15.9ms
102:	learn: 0.2084586	total: 49.7ms	remaining: 15.4ms
103:	learn: 0.2082371	total: 50.1ms	remaining: 14.9ms
104:	learn: 0.2080122	total: 50.6ms	remaining: 14.4ms
105:	learn: 0.2076821	total: 51ms	remaining: 14ms
106:	learn: 0.2074858	total: 51.4ms	remaining: 13.5ms
107:	learn: 0.2072324	total: 51.9ms	remaining: 13ms
108:	learn: 0.2070295	total: 52.3ms	remaining: 12.5ms
109:	learn: 0.2067802	total: 52.7ms	remaining: 12ms
110:	learn: 0.2066511	total: 55ms	remaining: 11.9ms
111:	learn: 0.2063353	total: 55.4ms	remaining: 11.4ms
112:	learn: 0.2058897	total: 57.5ms	remaining: 11.2ms
113:	learn: 0.2057216	total: 57.9ms	remaining: 10.7ms
114:	learn: 0.2053956	total: 58.4ms	remaining: 10.2ms
115:	learn: 0.2051613	total: 58.8ms	remaining: 9.63ms
116:	learn: 0.2048693	total: 59.2ms	remaining: 9.11ms
117:	learn: 0.2046027	total: 59.7ms	remaining: 8.59ms
118:	learn: 0.2042936	total: 60.1ms	remaining: 8.07ms
119:	learn: 0.2040510	total: 60.5ms	remaining: 7.56ms
120:	learn: 0.2037716	total: 60.9ms	remaining: 7.05ms
121:	learn: 0.2036460	total: 61.4ms	remaining: 6.54ms
122:	learn: 0.2034127	total: 61.8ms	remaining: 6.03ms
123:	learn: 0.2031771	total: 62.2ms	remaining: 5.52ms
124:	learn: 0.2029526	total: 62.6ms	remaining: 5.01ms
125:	learn: 0.2028325	total: 63ms	remaining: 4.5ms
126:	learn: 0.2026988	total: 63.4ms	remaining: 4ms
127:	learn: 0.2025269	total: 63.9ms	remaining: 3.49ms
128:	learn: 0.2023516	total: 64.4ms	remaining: 2.99ms
129:	learn: 0.2021234	total: 64.8ms	remaining: 2.49ms
130:	learn: 0.2019558	total: 65.2ms	remaining: 1.99ms
131:	learn: 0.2017837	total: 65.6ms	remaining: 1.49ms
132:	learn: 0.2016438	total: 66ms	remaining: 992us
133:	learn: 0.2013360	total: 66.4ms	remaining: 495us
134:	learn: 0.2012184	total: 66.8ms	remaining: 0us

## Predict

In [18]:
preds_p = {}
for task in ['agnostic', 'aware']:
    preds_p['test-' + task] = models['val-' + task].predict(X['test-' + task])

    # Postprocessing
    np.clip(preds_p['test-' + task], 0.0, 1.0, out=preds_p['test-' + task])

    print(f'test-{task} - done!')

test-agnostic - done!
test-aware - done!

# Submit
## Form dataframe

In [19]:
submission = {}
for task in ['agnostic', 'aware']:
    submission[task] = pd.DataFrame({
        'id': X['test-' + task].index.to_list(),
        'label': preds_label['test-' + task],
        'p(Hallucination)': preds_p['test-' + task],
        })

submission['agnostic']

        id              label  p(Hallucination)
0        1  Not Hallucination          0.304244
1        2  Not Hallucination          0.481807
2        3  Not Hallucination          0.197527
3        6      Hallucination          1.000000
4        7      Hallucination          0.664864
...    ...                ...               ...
1495  2992  Not Hallucination          0.104505
1496  2993      Hallucination          0.763462
1497  2994  Not Hallucination          0.229331
1498  2996  Not Hallucination          0.199584
1499  2999  Not Hallucination          0.157373

[1500 rows x 3 columns]

In [20]:
submission['aware']

        id              label  p(Hallucination)
0        0  Not Hallucination          0.179973
1        4  Not Hallucination          0.308127
2        5      Hallucination          0.548142
3        9      Hallucination          0.698821
4       11  Not Hallucination          0.167704
...    ...                ...               ...
1495  2988      Hallucination          0.555414
1496  2991  Not Hallucination          0.248281
1497  2995  Not Hallucination          0.177197
1498  2997  Not Hallucination          0.177055
1499  2998      Hallucination          0.650719

[1500 rows x 3 columns]

## Save to json

In [21]:
for task in ['agnostic', 'aware']:
    json_file_path = SUBMISSION_PATH + 'test.model-' + task + '.json'

    # Check if file exists
    assert not os.path.exists(json_file_path), 'File already exists.'

    # Save to .json file
    submission[task].to_json(
        path_or_buf=json_file_path,
        orient='records',
    )

## Check file format

In [22]:
!python ./check_output.py {SUBMISSION_PATH}

all clear!

# Evaluate

In [23]:
!python ./score.py {SUBMISSION_PATH} {REFERENCE_PATH} {RESULT_PATH}

with open(RESULT_PATH) as fp:
    print(fp.read())

agnostic_acc:0.8133333333333334
agnostic_rho:0.7548934241737641
aware_acc:0.8
aware_rho:0.7146896895588751